import Cleanroom.Bli.BliTrajectory.Lemmas

/-!
# `bli-trajectory` · Partition: constraint 4 is the partition axiom (M4, T2)

Over an abstract state system `S` and market `P`, on a day `n ≥ 1` where `P_n` is a finite
world mixture on the algebra generated by the day-`n` small sentences and the day-`(n+1)` state
atoms (`bli-found`'s `CoherentOn`), constraint 2 holds at `(n, n+1)` on `smallSet n`, and the
day-`(n+1)` states are exclusive: **constraint 4 at `n` holds iff the day-`(n+1)` masses sum
to one** (`e4_iff_partition_mass`). Route: (⇒) constraint 4 at `⊤` with constraint 2 at `⊤`
(the tables' value at `⊤` is `1` on every charged state); (⇐) the law of total probability over
the partition inside each world, then constraint 2 — the residual mass off the partition vanishes.
Findings: constraint 4 adds nothing beyond the partition once `P_n` is a measure on the state
algebra (bli-soto-a-006 (i); bli-found F-11); `main.tex:444–445`'s "no-net-expected-update"
display is literally the law of total probability (bli-soto-a-006 (iii)). Not "new"; the row
is `C`.

Day `0`: `⊤ ∉ smallSet 0` (`sizeBound 0 = 2 < 4 = tokenSize ⊤`), so the (⇒) direction needs
`1 ≤ n` — stated, not hidden (bli-found F-9).
-/

namespace Cleanroom.Bli.BliTrajectory

open LogicalInduction LO.Propositional Finset
open Cleanroom.Bli.BliFound Cleanroom.Bli.BliFinite

open Classical

/-! ## World payouts -/

/-- A world's payout on a conjunction is the product of the payouts.
Source: none: infrastructure (FAF `PCWorld.holds_and`)
Kind: L
Fidelity: n/a -/
lemma payout_and (v : PCWorld) (φ ψ : Sentence) : v.payout (φ ⋏ ψ) = v.payout φ * v.payout ψ := by
  unfold PCWorld.payout
  by_cases hφ : v.Holds φ <;> by_cases hψ : v.Holds ψ <;> simp [PCWorld.holds_and, hφ, hψ]

/-- A world's payout on `⊤` is `1`.
Source: none: infrastructure (FAF `PCWorld.holds_top`)
Kind: L
Fidelity: n/a -/
lemma payout_top (v : PCWorld) : v.payout (⊤ : Sentence) = 1 := by
  unfold PCWorld.payout; rw [if_pos (PCWorld.holds_top v)]

/-- Payouts are `0` or `1`.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma payout_eq_zero_or_one (v : PCWorld) (φ : Sentence) : v.payout φ = 0 ∨ v.payout φ = 1 := by
  unfold PCWorld.payout; split_ifs <;> simp

/-- `⊤` is small from day `1` on (`tokenSize ⊤ = 4 ≤ sizeBound n`).
Source: none: infrastructure (bli-found F-9: day `0` is special)
Kind: L
Fidelity: n/a -/
lemma top_mem_smallSet {n : ℕ} (hn : 1 ≤ n) : (⊤ : Sentence) ∈ smallSet n := by
  rw [mem_smallSet]; unfold SmallOn; rw [tokenSize_verum]; exact four_le_sizeBound hn

/-- A day-`(n+1)` candidate's atom is among the state atoms up to day `n+1`.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma stateAtom_mem_stateAtomsUpTo (S : StateSystem) {n q : ℕ} (hq : q ∈ S.states (n + 1)) :
    stateAtom (n + 1) q ∈ stateAtomsUpTo S (n + 1) := by
  unfold stateAtomsUpTo
  rw [Finset.mem_biUnion]
  exact ⟨n + 1, Finset.mem_range.mpr (Nat.lt_succ_self _), Finset.mem_image_of_mem _ hq⟩

/-- The atoms of a generator lie in `pcpAtoms` at horizon `n+1`.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma atoms_subset_pcpAtoms (S : StateSystem) {n : ℕ} {ψ : Sentence}
    (h : ψ ∈ smallSet n ∪ stateAtomsUpTo S (n + 1)) :
    sentenceAtomCodes ψ ⊆ pcpAtoms S (fun _ => n + 1) n :=
  Finset.subset_biUnion_of_mem sentenceAtomCodes h

/-! ## T2 -/

/-- **`e4_iff_partition_mass` — constraint 4 ⟺ partition mass 1** over an abstract system, on a
day `n ≥ 1` where `P_n` is a world mixture on the algebra of the day-`n` small sentences and the
day-`(n+1)` state atoms (`CoherentOn D (pcpAtoms S (fun _ => n+1) n) (P n)` for any stage `D`),
under exclusivity of the day-`(n+1)` states and constraint 2 at `(n, n+1)` **on `smallSet n`**
(the scope `E2x` gives on `smallSet n ∩ Sminus (n+1) (n+1)`; stated at the scope the theorem
needs). Then `E4` at `n` ⟺ `∑_q P_n(σ_q) = 1`. (⇒) reads constraint 4 and constraint 2 at `⊤`;
(⇐) is the law of total probability over the partition inside each charged world.
Source: bli-soto-a-006 (i)/(iii); Appendix B (`main.tex:434–435`, `444–445`); bli-found F-11; mandate M4
Kind: C
Fidelity: exact (abstract; `1 ≤ n` for (⇒), coherence via FAF worlds)
Hyps: (a) coherence, exclusivity, constraint 2 on `smallSet n` (all explicit; `bli-found` objects) -/
theorem e4_iff_partition_mass (S : StateSystem) (P : History) (n : ℕ) (hn : 1 ≤ n)
    (D : Finset Sentence) (hcoh : CoherentOn D (pcpAtoms S (fun _ => n + 1) n) (P n))
    (hexcl : ∀ q₁ ∈ S.states (n + 1), ∀ q₂ ∈ S.states (n + 1), q₁ ≠ q₂ →
      P n (stateAtom (n + 1) q₁ ⋏ stateAtom (n + 1) q₂) = 0)
    (hE2 : ∀ q ∈ S.states (n + 1), ∀ φ ∈ smallSet n,
      P n (φ ⋏ stateAtom (n + 1) q) = S.val (n + 1) q φ * P n (stateAtom (n + 1) q)) :
    (∀ φ ∈ smallSet n,
        P n φ = ∑ q ∈ S.states (n + 1), P n (stateAtom (n + 1) q) * S.val (n + 1) q φ) ↔
      ∑ q ∈ S.states (n + 1), P n (stateAtom (n + 1) q) = 1 := by
  obtain ⟨k, W, w, -, hw, hwsum, hrep⟩ := hcoh
  have hrep' : ∀ ψ ∈ smallSet n ∪ stateAtomsUpTo S (n + 1),
      P n ψ = ∑ i, w i * (W i).payout ψ :=
    fun ψ hψ => hrep ψ (atoms_subset_pcpAtoms S hψ)
  have hrepσ : ∀ q ∈ S.states (n + 1),
      P n (stateAtom (n + 1) q) = ∑ i, w i * (W i).payout (stateAtom (n + 1) q) :=
    fun q hq => hrep' _ (Finset.mem_union_right _ (stateAtom_mem_stateAtomsUpTo S hq))
  have hatoms2 : ∀ φ ∈ smallSet n, ∀ q ∈ S.states (n + 1),
      sentenceAtomCodes (φ ⋏ stateAtom (n + 1) q) ⊆ pcpAtoms S (fun _ => n + 1) n := by
    intro φ hφ q hq
    rw [sentenceAtomCodes_and]
    exact Finset.union_subset (atoms_subset_pcpAtoms S (Finset.mem_union_left _ hφ))
      (atoms_subset_pcpAtoms S (Finset.mem_union_right _ (stateAtom_mem_stateAtomsUpTo S hq)))
  have hrepand : ∀ φ ∈ smallSet n, ∀ q ∈ S.states (n + 1),
      P n (φ ⋏ stateAtom (n + 1) q) =
        ∑ i, w i * ((W i).payout φ * (W i).payout (stateAtom (n + 1) q)) := by
    intro φ hφ q hq
    rw [hrep _ (hatoms2 φ hφ q hq)]
    simp only [payout_and]
  have htop : (⊤ : Sentence) ∈ smallSet n := top_mem_smallSet hn
  constructor
  · intro hE4
    have hPtop : P n ⊤ = 1 := by
      rw [hrep' ⊤ (Finset.mem_union_left _ htop)]
      simp only [payout_top, mul_one]; exact hwsum
    have hq : ∀ q ∈ S.states (n + 1),
        P n (stateAtom (n + 1) q) * S.val (n + 1) q ⊤ = P n (stateAtom (n + 1) q) := by
      intro q hq
      have h1 := hE2 q hq ⊤ htop
      have h2 : P n (⊤ ⋏ stateAtom (n + 1) q) = P n (stateAtom (n + 1) q) := by
        rw [hrepand ⊤ htop q hq, hrepσ q hq]
        simp only [payout_top, one_mul]
      rw [h2] at h1
      linarith [h1]
    have := hE4 ⊤ htop
    rw [hPtop, Finset.sum_congr rfl hq] at this
    exact this.symm
  · intro hmass φ hφ
    set ind : Fin k → ℕ → ℝ := fun i q => (W i).payout (stateAtom (n + 1) q) with hind
    -- each charged world holds at most one day-(n+1) state
    have hSle : ∀ i, 0 < w i → ∑ q ∈ S.states (n + 1), ind i q ≤ 1 := by
      intro i hwi
      have hcard :
          ((S.states (n + 1)).filter (fun q => (W i).Holds (stateAtom (n + 1) q))).card ≤ 1 := by
        rw [Finset.card_le_one]
        intro q₁ hq₁ q₂ hq₂
        rw [Finset.mem_filter] at hq₁ hq₂
        by_contra hne
        have hex := hexcl q₁ hq₁.1 q₂ hq₂.1 hne
        have hatoms : sentenceAtomCodes (stateAtom (n + 1) q₁ ⋏ stateAtom (n + 1) q₂) ⊆
            pcpAtoms S (fun _ => n + 1) n := by
          rw [sentenceAtomCodes_and]
          exact Finset.union_subset
            (atoms_subset_pcpAtoms S (Finset.mem_union_right _ (stateAtom_mem_stateAtomsUpTo S hq₁.1)))
            (atoms_subset_pcpAtoms S (Finset.mem_union_right _ (stateAtom_mem_stateAtomsUpTo S hq₂.1)))
        rw [hrep _ hatoms] at hex
        have hterm : 0 < w i * (W i).payout (stateAtom (n + 1) q₁ ⋏ stateAtom (n + 1) q₂) := by
          rw [payout_and]
          unfold PCWorld.payout
          rw [if_pos hq₁.2, if_pos hq₂.2]
          linarith
        have hnn : ∀ j ∈ (Finset.univ : Finset (Fin k)),
            0 ≤ w j * (W j).payout (stateAtom (n + 1) q₁ ⋏ stateAtom (n + 1) q₂) :=
          fun j _ => mul_nonneg (hw j) (payout_mem_Icc _ _).1
        have := Finset.single_le_sum
          (f := fun j => w j * (W j).payout (stateAtom (n + 1) q₁ ⋏ stateAtom (n + 1) q₂))
          hnn (Finset.mem_univ i)
        linarith
      have hsumcard : ∑ q ∈ S.states (n + 1), ind i q =
          (((S.states (n + 1)).filter (fun q => (W i).Holds (stateAtom (n + 1) q))).card : ℝ) := by
        simp only [hind, PCWorld.payout]
        rw [Finset.sum_boole]
      rw [hsumcard]; exact_mod_cast hcard
    have hswap : ∑ q ∈ S.states (n + 1), P n (stateAtom (n + 1) q) =
        ∑ i, w i * ∑ q ∈ S.states (n + 1), ind i q := by
      rw [Finset.sum_congr rfl (fun q hq => hrepσ q hq), Finset.sum_comm]
      exact Finset.sum_congr rfl fun i _ => by rw [Finset.mul_sum]
    have hzero : ∀ i, w i * (1 - ∑ q ∈ S.states (n + 1), ind i q) = 0 := by
      have hsum0 : ∑ i, w i * (1 - ∑ q ∈ S.states (n + 1), ind i q) = 0 := by
        simp only [mul_sub, mul_one, Finset.sum_sub_distrib, hwsum]
        rw [← hswap, hmass, sub_self]
      have hnn : ∀ i ∈ (Finset.univ : Finset (Fin k)),
          0 ≤ w i * (1 - ∑ q ∈ S.states (n + 1), ind i q) := by
        intro i _
        rcases (hw i).lt_or_eq with hwi | hwi
        · exact mul_nonneg (hw i) (by linarith [hSle i hwi])
        · rw [← hwi, zero_mul]
      exact fun i => (Finset.sum_eq_zero_iff_of_nonneg hnn).mp hsum0 i (Finset.mem_univ i)
    have hdecomp : ∀ i, w i * (W i).payout φ =
        w i * ∑ q ∈ S.states (n + 1), (W i).payout φ * ind i q := by
      intro i
      rcases (hw i).lt_or_eq with hwi | hwi
      · have hS : ∑ q ∈ S.states (n + 1), ind i q = 1 := by
          rcases mul_eq_zero.mp (hzero i) with h | h
          · linarith
          · linarith
        rw [← Finset.mul_sum, hS, mul_one]
      · rw [← hwi, zero_mul, zero_mul]
    calc P n φ = ∑ i, w i * (W i).payout φ := hrep' φ (Finset.mem_union_left _ hφ)
      _ = ∑ i, w i * ∑ q ∈ S.states (n + 1), (W i).payout φ * ind i q :=
          Finset.sum_congr rfl (fun i _ => hdecomp i)
      _ = ∑ q ∈ S.states (n + 1), ∑ i, w i * ((W i).payout φ * ind i q) := by
          simp only [Finset.mul_sum]; exact Finset.sum_comm
      _ = ∑ q ∈ S.states (n + 1), P n (φ ⋏ stateAtom (n + 1) q) :=
          Finset.sum_congr rfl (fun q hq => (hrepand φ hφ q hq).symm)
      _ = ∑ q ∈ S.states (n + 1), P n (stateAtom (n + 1) q) * S.val (n + 1) q φ :=
          Finset.sum_congr rfl (fun q hq => by rw [hE2 q hq φ hφ, mul_comm])

/-- **In B1 both sides hold outright**: constraint 4 (`bli_balance`, from `Kernel.balanced`) and
partition mass one (`bli_partition`, from `Kernel.sum_law`) — the redundancy finding in the
package's own object: once `𝐏_n` is the marginal of a kernel, constraint 4 is the balance field.
Source: bli-soto-a-006 (i); mandate M4
Kind: C
Fidelity: exact
Hyps: (a) `hQ` -/
theorem bli_e4_and_partition_mass {𝓜 : Mesh} (c : StateCoding 𝓜) (sk : Skeleton smallIndex 𝓜.d)
    (Q : RatHistory) (hQ : ∀ n φ, 0 ≤ Q n φ ∧ Q n φ ≤ 1) :
    E4 (bliStateSystem Q 𝓜 c) (bliHistory Q 𝓜 sk c) ∧
      ∀ n, ∑ q ∈ (bliStateSystem Q 𝓜 c).states (n + 1),
        bliHistory Q 𝓜 sk c n (stateAtom (n + 1) q) = 1 :=
  ⟨bli_balance c sk Q hQ, fun n => (bli_partition c sk Q n).1⟩

end Cleanroom.Bli.BliTrajectory
