"""A readable rendering of the whole slice, end to end.

`python3 src/trace.py TRACE.txt` writes the same text every time from the same
code, so the committed file is a replay rather than a transcript. Nothing here
computes anything the pipeline did not already compute: it reads runs and prints
them.
"""
from __future__ import annotations

import sys
from fractions import Fraction

import toy
import trajectories as T
from pipeline import deductively_inert
from standing import values_projection

Q = Fraction


def _pt(v) -> str:
    return "(" + ", ".join(str(x) for x in v) + ")"


def _row(row, coords) -> str:
    parts = [f"{c}*<{phi!r}>" for c, phi in zip(row.coefficients, coords) if c]
    return (" + ".join(parts) if parts else "0") + f" >= {row.rhs}"


def render_day(run, out, prefix: str = "  ") -> None:
    p = lambda line: out.append(prefix + line)
    p(f"day n = {run.day}   (LI precision k = n+1 = {run.day + 1})")
    p("O_n = " + ", ".join(f"{sid} carries {J.injunction_id}"
                           for sid, J in run.projection))
    for sid, J in run.projection:
        for k, ineq in enumerate(J.ineqs):
            p(f"    {sid}#{k}  {ineq!r}")
    if run.conflict.blocking:
        p(f"CONFLICT: {run.conflict.state}")
        for sid, msg in run.conflict.malformed:
            p(f"    {sid}: {msg}")
        for sid, cert in run.conflict.self_inconsistent:
            p(f"    {sid}: {cert!r}")
        for cert in (run.conflict.normatively_empty, run.conflict.incompatible):
            if cert is not None:
                p(f"    {cert!r}")
        if run.conflict.deductively_empty:
            p("    no world is consistent with Sigma_n")
        p("STOPS HERE: no region is emitted and no price is produced.")
        return
    p(f"fragment ({len(run.coords)} coordinates): "
      + ", ".join(repr(c) for c in run.coords))
    p("kappa_n(J) as rows over prices:")
    for row in run.compiled.rows:
        p(f"    [{row.standing_id}#{row.index} {row.label}] "
          + _row(row, run.coords))
    p("K^D_n generated by: " + ", ".join(_pt(v) for v in run.deductive_vertices))
    p("K_n  generated by: " + ", ".join(_pt(v) for v in run.region_vertices))
    p(f"deductively inert: {deductively_inert(run)}")

    c = run.charged
    p(f"live worlds (PC(Sigma_n) on the fragment): {len(run.live_worlds)}")
    if run.excluded_worlds:
        p("  excluded, with each one's total row deficit sum_j d_j(omega):")
        for point, total in run.excluded_worlds:
            p(f"      {_pt(point)}  {total}")
    else:
        p("  none excluded")
    p(f"D_n = max_omega sum_j d_j(omega) = {c.sharp}"
      f"      (conservative rowwise aggregate: {c.rowwise})")
    p(f"q_n = (eps + M) * D_n / delta = ({c.slack} + {c.volume}) * {c.sharp}"
      f" / {c.tolerance} = {c.charge}")
    p("traderization obligations:")
    for o in run.obligations:
        p(f"    {o.verdict:9} {o.name:24} {o.source}")
        if o.detail:
            p(f"              {o.detail}")
    if c.emitted:
        p(f"force emitted; account remaining {c.account_remaining}, "
          f"safety bound B = {c.safety_bound}")
    else:
        p(f"FORCE WITHHELD: {c.withheld}")
        p("  the injunction keeps its normative standing and receives no "
          "operative force at this date.")
    if run.prices:
        p("resulting price vector: " + _pt(run.prices))
        for name, value in run.readings:
            p(f"    {name} = {value}")
    else:
        p("no price produced.")


def render(out=None) -> str:
    out = [] if out is None else out
    p = out.append
    scene = toy.canonical()
    traj = scene["trajectory"]

    p("=" * 74)
    p("End-to-end vertical slice: the canonical trajectory")
    p("=" * 74)
    p("")
    p("  Gamma/settlement -> Sigma -> PC worlds -> reasons -> normative")
    p("  standing -> value exposure -> operative force -> K^N, K^D, K ->")
    p("  live-world deficit -> charge -> account -> prices.")
    p("")
    p("Value specifications, both frozen at admission:")
    for sid in traj.registry.known():
        spec = traj.registry.spec(sid)
        p(f"  {sid}: exposes {list(spec.queries())}"
          + (f", supersedes {list(spec.supersedes)}" if spec.supersedes else ""))
    p(f"  compileValue(v0, q) = {traj.X0.luv.name}"
      f"   certificate {traj.X0.code_witness}")
    p(f"  compileValue(v1, q) = {traj.X1.luv.name}"
      f"   certificate {traj.X1.code_witness}")
    p(f"  compileValue(v0, incomparable) = "
      f"{traj.registry.compile_value('v0', 'incomparable')}")
    p("")

    titles = {
        "A": "STAGE A  -- a thin seed issues PValue(v0) and one injunction",
        "B": "STAGE B  -- an outcome is read, settled, and v0 is superseded\n"
             "            by v1; the injunction is not touched",
        "C": "STAGE C  -- an explicit normative event replaces J0 by J1",
    }
    states = {"A": 2, "B": 5, "C": 7}
    for key in ("A", "B", "C"):
        p("-" * 74)
        for line in titles[key].splitlines():
            p(line)
        p("-" * 74)
        t = states[key]
        std = traj.history.std(t)
        p(f"  RI state t = {t}   GC and AC hold: {traj.history.good(t)}")
        p("  standing:")
        for x, state in sorted(std.items()):
            if x.startswith("auth:"):
                continue
            name = type(state.payload).__name__
            tag = getattr(state.payload, "spec_id", None)
            if tag is None:
                clause = getattr(state.payload, "clause", None)
                tag = getattr(clause, "injunction_id", "")
            p(f"      {x:8} {state.kind:11} {name}({tag})")
        p("  active value standing: "
          + ", ".join(f"{sid}->{v}" for sid, v in values_projection(std)))
        if key == "B":
            o = traj.outcomes[0]
            p(f"  raw outcome {o.id}: {o.content!r}")
            p("      a raw outcome is not a settlement and constrains no world")
        settled = [s.id for s in traj.history.settlements(t)]
        p(f"  settlement ledger L_t: {settled or 'empty'}")
        for sid in settled:
            r = traj.sem.reading(sid)
            p(f"      sem_L({sid}) = "
              + (", ".join(repr(s) for s in r.sentences) or "nothing")
              + f"    [{r.note}]")
        reasons = [e.id for e in traj.history.reasons(t)]
        p(f"  reason occurrences R_t: {reasons or 'none'}")
        events = [(a.id, a.tau) for a in traj.history.norm_events(t)]
        p(f"  normative events N_t: {events or 'none'}")
        stage = traj.stage(t)
        p(f"  Sigma_t: {len(stage.by_source('deductive'))} deductive, "
          f"{len(stage.entries) - len(stage.by_source('deductive'))} settled")
        p("")
        render_day(scene[key], out)
        p("")

    _rider(out, scene)
    return "\n".join(out) + "\n"


def _rider(out, scene) -> None:
    p = out.append
    a, b, c = scene["A"], scene["B"], scene["C"]

    p("-" * 74)
    p("WHERE SETTLEMENT CHANGES THE LIABILITY -- and where it does not")
    p("-" * 74)
    p("")
    p("At a fixed day, D_n is a maximum over the live worlds of a fixed row")
    p("system, so removing worlds cannot raise it. Across days the row system")
    p("itself moves, because E_n(X) is the precision-(n+1) threshold bundle,")
    p("and the two live-world sets are patterns over different fragments. The")
    p("cross-day comparison is not a monotonicity failure so much as a")
    p("comparison between objects of different types -- and the numbers move")
    p("the wrong way:")
    p("")
    _, _, runs = T.mesh_counterexample()
    p("  one frozen injunction Expect(X) <= 1/2, one stage settling X <= 1/2:")
    for n in sorted(runs):
        r = runs[n]
        p(f"    day {n} (k={n + 1}): fragment "
          + ", ".join(repr(x) for x in r.coords))
        p(f"              live worlds "
          + ", ".join(_pt(w) for w in r.live_worlds))
        p(f"              D_{n} = {r.sharp_deficit}   q_{n} = {r.charge}")
    p("")
    p("  A world obeying `X <= 1/2` reads X at 1/2 on the precision-2 mesh and")
    p("  at 2/3 on the precision-3 mesh, because the precision-k reading is")
    p("  ceil(x*k)/k and that is not monotone in k. A free day becomes a")
    p("  charged day with nothing about the record having been unsettled.")
    p("")

    p("-" * 74)
    p("FOUR CHARGED TRAJECTORIES")
    p("-" * 74)
    p("")
    for name, title in (
            ("settlement_closes_the_gap",
             "settlement removes every excluded world; the tail is zero"),
            ("pressure_decays",
             "eps+M decays; the region excludes a live world at every date"),
            ("tolerance_route",
             "delta loosens to its ceiling of 1, then the charge is constant"),
            ("nothing_decays",
             "nothing decays; the account is exhausted and force is withheld")):
        out_ = getattr(T, name)()
        p(f"  {name} -- {title}")
        p("     day |  eps+M  |   D_t   |  delta  |   q_t   | emitted | "
          "partial sum")
        sums = T.partial_sums(out_["charges"])
        for run, ch, total in zip(out_["runs"], out_["charges"], sums):
            p(f"     {run.day:>3} | {str(ch.slack + ch.volume):>7} | "
              f"{str(ch.sharp):>7} | {str(ch.tolerance):>7} | "
              f"{str(ch.charge):>7} | {str(ch.emitted):>7} | {total}")
        p(f"     account: capital {out_['account'].capital}, "
          f"remaining {out_['account'].remaining}")
        p("")
    p("  The first two converge and the last two do not. None of the four is a")
    p("  normative source anyone should believe in; what they show is that the")
    p("  mechanics run from normative standing to a cumulative account, and")
    p("  that the architecture withholds force rather than overspending.")
    p("")

    p("-" * 74)
    p("WHAT THE TRAJECTORY SHOWS")
    p("-" * 74)
    p(f"  A -> B: the active value specification changes (v0 -> v1) while the")
    p(f"          operative projection does not: "
      f"{[J.injunction_id for _, J in a.projection]}"
      f" -> {[J.injunction_id for _, J in b.projection]}.")
    p(f"          B's compiled fragment still names v0's thresholds:")
    p(f"          {[repr(x) for x in b.coords]}")
    p(f"  B -> C: an explicit normative event moves force:"
      f" {[J.injunction_id for _, J in b.projection]}"
      f" -> {[J.injunction_id for _, J in c.projection]},")
    p(f"          and only now does the fragment change to v1's thresholds:")
    p(f"          {[repr(x) for x in c.coords]}")
    p(f"  every day: admissibility fails and the region is not inert -- the")
    p(f"          two are the same condition, so no contentful injunction gets")
    p(f"          the unconditional branch. Each day is charged instead, and")
    p(f"          the prices below are produced only because the account paid.")
    p("")
    p("  The obligation this run does not discharge: that sum_t q_t stays")
    p("  finite for a normative source anyone would call legitimate. Four")
    p("  synthetic trajectories are exhibited above, two convergent and two")
    p("  not, and none of them is such a source.")


if __name__ == "__main__":
    text = render()
    if len(sys.argv) > 1:
        with open(sys.argv[1], "w") as fh:
            fh.write(text)
    else:
        sys.stdout.write(text)
