"""A readable rendering of the toy trajectory, end to end.

`python3 src/trace.py` writes the same text every time from the same code, so
the committed `TRACE.txt` is a replay rather than a transcript. Nothing here
computes: it reads a run and prints it.
"""
from __future__ import annotations

import sys
from fractions import Fraction

import toy
from pipeline import deductively_inert
from standing import values_projection


def _pt(v) -> str:
    return "(" + ", ".join(str(x) for x in v) + ")"


def _row(row, coords) -> str:
    parts = []
    for c, phi in zip(row.coefficients, coords):
        if c:
            parts.append(f"{c}*<{phi!r}>")
    body = " + ".join(parts) if parts else "0"
    return f"{body} >= {row.rhs}"


def render_day(run, out) -> None:
    p = out.append
    p(f"  day n = {run.day}   (LI precision k = n+1 = {run.day + 1})")
    p(f"  O_n = " + ", ".join(f"{sid} carries {J.injunction_id}"
                              for sid, J in run.projection))
    for sid, J in run.projection:
        for k, ineq in enumerate(J.ineqs):
            p(f"      {sid}#{k}  {ineq!r}")
    if run.conflict.blocking:
        p(f"  CONFLICT: {run.conflict.state}")
        for sid, msg in run.conflict.malformed:
            p(f"      {sid}: {msg}")
        for sid, cert in run.conflict.self_inconsistent:
            p(f"      {sid}: {cert!r}")
        if run.conflict.normatively_empty is not None:
            p(f"      {run.conflict.normatively_empty!r}")
        if run.conflict.incompatible is not None:
            p(f"      {run.conflict.incompatible!r}")
        if run.conflict.deductively_empty:
            p("      no world is consistent with Sigma_n")
        return
    p(f"  fragment ({len(run.coords)} coordinates): "
      + ", ".join(repr(c) for c in run.coords))
    p("  kappa_n(J) as rows over prices:")
    for row in run.compiled.rows:
        p(f"      [{row.standing_id}#{row.index} {row.label}] "
          + _row(row, run.coords))
    p("  K^D_n generated by: " + ", ".join(_pt(v)
                                           for v in run.deductive_vertices))
    p("  K_n  generated by: " + ", ".join(_pt(v) for v in run.region_vertices))
    p(f"  deductively inert: {deductively_inert(run)}")
    if run.excluded_worlds:
        p("  Sigma_n-consistent worlds the region excludes:")
        for point, deficit in run.excluded_worlds:
            p(f"      {_pt(point)}  worst row violation {deficit}")
        p(f"  aggregate exclusion depth d_n = {run.exclusion_depth}")
        p(f"  enforcement charge (eps + M) * d_n / delta = {run.charge}")
    else:
        p("  no stage-consistent world is excluded")
    p("  traderization obligations:")
    for o in run.obligations:
        p(f"      {o.verdict:9} {o.name:24} {o.source}")
        if o.detail:
            p(f"                {o.detail}")
    if run.prices:
        p("  resulting price vector: " + _pt(run.prices))
        for name, value in run.readings:
            p(f"      {name} = {value}")


def render(out=None) -> str:
    out = [] if out is None else out
    p = out.append
    scene = toy.canonical()
    traj = scene["trajectory"]

    p("=" * 74)
    p("End-to-end vertical slice: the canonical trajectory")
    p("=" * 74)
    p("")
    p("Value specifications, both frozen at admission:")
    for sid in traj.registry.known():
        spec = traj.registry.spec(sid)
        p(f"  {sid}: exposes {list(spec.queries())}"
          + (f", supersedes {list(spec.supersedes)}" if spec.supersedes else ""))
    p(f"  compileValue(v0, q) = {traj.X0.luv.name}"
      f"   certificate {traj.X0.code_witness}")
    p(f"  compileValue(v1, q) = {traj.X1.luv.name}"
      f"   certificate {traj.X1.code_witness}")
    p(f"  compileValue(v0, incomparable) = "
      f"{traj.registry.compile_value('v0', 'incomparable')}")
    p("")

    titles = {
        "A": "STAGE A  -- a thin seed issues PValue(v0) and one injunction",
        "B": "STAGE B  -- an outcome is settled and v0 is superseded by v1;\n"
             "            the injunction is not touched",
        "C": "STAGE C  -- an explicit normative event replaces J0 by J1",
    }
    states = {"A": 2, "B": 5, "C": 7}
    for key in ("A", "B", "C"):
        p("-" * 74)
        p(titles[key])
        p("-" * 74)
        t = states[key]
        std = traj.history.std(t)
        p(f"  RI state t = {t}   GC and AC hold: {traj.history.good(t)}")
        p("  standing:")
        for x, state in sorted(std.items()):
            if x.startswith("auth:"):
                continue
            name = type(state.payload).__name__
            tag = getattr(state.payload, "spec_id", None)
            if tag is None:
                clause = getattr(state.payload, "clause", None)
                tag = getattr(clause, "injunction_id", "")
            p(f"      {x:8} {state.kind:11} {name}({tag})")
        p("  active value standing: "
          + ", ".join(f"{sid}->{v}" for sid, v in values_projection(std)))
        settled = [s.id for s in traj.history.settlements(t)]
        p(f"  settlement ledger L_t: {settled or 'empty'}")
        for sid in settled:
            r = traj.sem.reading(sid)
            p(f"      sem_L({sid}) = "
              + (", ".join(repr(s) for s in r.sentences) or "nothing")
              + f"    [{r.note}]")
        stage = traj.stage(t)
        p(f"  Sigma_t: {len(stage.by_source('deductive'))} deductive, "
          f"{len(stage.entries) - len(stage.by_source('deductive'))} settled")
        p("")
        render_day(scene[key], out)
        p("")

    p("-" * 74)
    p("What the trajectory shows")
    p("-" * 74)
    a, b, c = scene["A"], scene["B"], scene["C"]
    p(f"  A -> B: the active value specification changes (v0 -> v1) while the")
    p(f"          operative projection does not: {[J.injunction_id for _, J in a.projection]}"
      f" -> {[J.injunction_id for _, J in b.projection]}.")
    p(f"          B's compiled fragment still names v0's thresholds:")
    p(f"          {[repr(x) for x in b.coords]}")
    p(f"  B -> C: an explicit normative event moves force:"
      f" {[J.injunction_id for _, J in b.projection]}"
      f" -> {[J.injunction_id for _, J in c.projection]},")
    p(f"          and only now does the fragment change to v1's thresholds:")
    p(f"          {[repr(x) for x in c.coords]}")
    p(f"  every day: admissibility fails and the region is not inert --")
    p(f"          the two are the same fact, and neither day gets the")
    p(f"          unconditional branch of the traderization theorem.")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    text = render()
    if len(sys.argv) > 1:
        with open(sys.argv[1], "w") as fh:
            fh.write(text)
    else:
        sys.stdout.write(text)
