import Cleanroom.Found.CorrThreeStep.Setting
import Cleanroom.Corrigibility.CorrJointProcess.Budget

/-!
# `corr-trajectory` — `Process`: Layer F, the process of record (T1)

Layer F of the mandate: a finite `Ω` with FAF's `Distr Ω` as the objective law `P*`, a finite
filtration given by atoms (`Atoms`), and conditional quantities in **product form** — mass-weighted
sums over an atom, never ratios (the `corr-joint-process` Pattern A extended in time). On top of it
the process of record of `invariant-final.md` S1–S2′: `ShutdownProc` (the round observables of S2,
with `executed`, `loss`, `Harm`, `Omit`, `Reg` derived, never fields) and `AgentView` (the agent's
subjective laws, `Ψ`, the running certificate `Z`, the optimism drift `Δ`, the legitimacy events).

Design decisions (documented once, here):

* **Two interleaved filtrations.** `F.fib t` is `𝓕_t` (after the press of round `t`) and
  `Fpre.fib t` is `𝓕_t^-` (before it), with `F.fib t ⊆ Fpre.fib t ⊆ F.fib (t-1)`. A function is
  `𝓕_t`-measurable iff it is constant on the atoms of `F.fib t` (`Atoms.Meas`).
* **Conditional quantities** are `condSum μ A t X ω = ∑_{ω' ∈ A.fib t ω} μ ω' · X ω'`, i.e.
  `E[X · 1_{atom(ω)}]`; "`E[X ∣ 𝓕_t] ≤ c`" is `condSum t X ω ≤ c · atomMass t ω`. No headline rests on
  `x / 0 = 0`.
* The latent target `θ*_t` is not modelled: wrongness enters as `W_t` directly (fidelity
  `variant: latent target elided`, which is what the source's own proofs use).
* The package is **undiscounted** throughout.
-/

set_option linter.unusedSectionVars false

namespace Cleanroom.Corrigibility.CorrTrajectory

open FactoredSpaces Cleanroom.Found.CorrThreeStep Cleanroom.Corrigibility.CorrJointProcess
open Finset hiding expect

variable {Ω : Type} [Fintype Ω] [DecidableEq Ω]

/-! ## Indicators -/

/-- The real indicator of a `Finset` event.
Source: none: infrastructure
Kind: D
Fidelity: n/a -/
def ind (A : Finset Ω) : Ω → ℝ := fun ω => if ω ∈ A then 1 else 0

/-- The real indicator of a `Bool`-valued observable.
Source: none: infrastructure
Kind: D
Fidelity: n/a -/
def indB (b : Ω → Bool) : Ω → ℝ := fun ω => if b ω then 1 else 0

/-- `ind_nonneg` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma ind_nonneg (A : Finset Ω) (ω : Ω) : 0 ≤ ind A ω := by
  unfold ind; split_ifs <;> norm_num

/-- `ind_le_one` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma ind_le_one (A : Finset Ω) (ω : Ω) : ind A ω ≤ 1 := by
  unfold ind; split_ifs <;> norm_num

/-- `indB_nonneg` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma indB_nonneg (b : Ω → Bool) (ω : Ω) : 0 ≤ indB b ω := by
  unfold indB; split_ifs <;> norm_num

/-- `indB_le_one` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma indB_le_one (b : Ω → Bool) (ω : Ω) : indB b ω ≤ 1 := by
  unfold indB; split_ifs <;> norm_num

/-- `ind_of_mem` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma ind_of_mem {A : Finset Ω} {ω : Ω} (h : ω ∈ A) : ind A ω = 1 := by simp [ind, h]

/-- `ind_of_not_mem` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma ind_of_not_mem {A : Finset Ω} {ω : Ω} (h : ω ∉ A) : ind A ω = 0 := by simp [ind, h]

/-- `indB_true` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma indB_true {b : Ω → Bool} {ω : Ω} (h : b ω = true) : indB b ω = 1 := by simp [indB, h]

/-- `indB_false` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma indB_false {b : Ω → Bool} {ω : Ω} (h : b ω = false) : indB b ω = 0 := by simp [indB, h]

/-- `P(A) = E[1_A]`. Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma probOf_eq_expect_ind (μ : Distr Ω) (A : Finset Ω) : probOf μ A = expect μ (ind A) := by
  simp only [probOf, expect, ind, mul_ite, mul_one, mul_zero, sum_ite_mem, univ_inter]

/-! ## Atoms: a finite filtration -/

/-- **A finite filtration by atoms.** `fib t ω` is the atom of `ω` at time `t`; atoms contain their
point, partition (`ω' ∈ fib t ω → fib t ω' = fib t ω`) and are nested in time.
Source: [[corr-wf14-inventory]] 070 / invariant-final.md S1 (`𝓕_t` generated by the observable history)
Kind: D
Fidelity: exact (finite shadow) -/
structure Atoms (Ω : Type) [Fintype Ω] [DecidableEq Ω] where
  /-- the atom of `ω` at time `t` -/
  fib : ℕ → Ω → Finset Ω
  mem_fib : ∀ t ω, ω ∈ fib t ω
  fib_eq_of_mem : ∀ t ω ω', ω' ∈ fib t ω → fib t ω' = fib t ω
  fib_succ_subset : ∀ t ω, fib (t + 1) ω ⊆ fib t ω

namespace Atoms

variable (A : Atoms Ω)

/-- The trivial filtration: one atom (`univ`) at every time.
Source: none: infrastructure. Kind: D. Fidelity: n/a -/
def trivial : Atoms Ω where
  fib _ _ := univ
  mem_fib _ _ := mem_univ _
  fib_eq_of_mem _ _ _ _ := rfl
  fib_succ_subset _ _ := subset_rfl

/-- The discrete filtration: singleton atoms at every time.
Source: none: infrastructure. Kind: D. Fidelity: n/a -/
def discrete : Atoms Ω where
  fib _ ω := {ω}
  mem_fib _ _ := mem_singleton_self _
  fib_eq_of_mem _ _ _ h := by rw [mem_singleton.1 h]
  fib_succ_subset _ _ := subset_rfl

/-- `fib_mono` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma fib_mono {s t : ℕ} (hst : s ≤ t) (ω : Ω) : A.fib t ω ⊆ A.fib s ω := by
  induction hst with
  | refl => exact subset_rfl
  | step _ ih => exact (A.fib_succ_subset _ ω).trans ih

/-- `mem_fib_iff` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma mem_fib_iff (t : ℕ) (ω ω' : Ω) : ω' ∈ A.fib t ω ↔ A.fib t ω' = A.fib t ω :=
  ⟨A.fib_eq_of_mem t ω ω', fun h => h ▸ A.mem_fib t ω'⟩

/-- `mem_fib_symm` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma mem_fib_symm {t : ℕ} {ω ω' : Ω} (h : ω' ∈ A.fib t ω) : ω ∈ A.fib t ω' := by
  rw [mem_fib_iff] at h ⊢; exact h.symm

/-- **`𝓕_t`-measurability**: constant on the atoms of `fib t`.
Source: [[corr-wf14-inventory]] 070 / invariant-final.md S1
Kind: D
Fidelity: exact (finite shadow) -/
def Meas (t : ℕ) (X : Ω → ℝ) : Prop := ∀ ω ω', ω' ∈ A.fib t ω → X ω' = X ω

variable {A}

/-- `Meas.mono` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma Meas.mono {s t : ℕ} (hst : s ≤ t) {X : Ω → ℝ} (h : A.Meas s X) : A.Meas t X :=
  fun ω ω' hω' => h ω ω' (A.fib_mono hst ω hω')

/-- `meas_const` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma meas_const (A : Atoms Ω) (t : ℕ) (k : ℝ) : A.Meas t (fun _ => k) := fun _ _ _ => rfl

/-- `Meas.add` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma Meas.add {t : ℕ} {X Y : Ω → ℝ} (hX : A.Meas t X) (hY : A.Meas t Y) :
    A.Meas t (fun ω => X ω + Y ω) := fun ω ω' h => by dsimp only; rw [hX ω ω' h, hY ω ω' h]

/-- `Meas.mul` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma Meas.mul {t : ℕ} {X Y : Ω → ℝ} (hX : A.Meas t X) (hY : A.Meas t Y) :
    A.Meas t (fun ω => X ω * Y ω) := fun ω ω' h => by dsimp only; rw [hX ω ω' h, hY ω ω' h]

/-- `Meas.sub` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma Meas.sub {t : ℕ} {X Y : Ω → ℝ} (hX : A.Meas t X) (hY : A.Meas t Y) :
    A.Meas t (fun ω => X ω - Y ω) := fun ω ω' h => by dsimp only; rw [hX ω ω' h, hY ω ω' h]

/-- `Meas.const_mul` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma Meas.const_mul {t : ℕ} (k : ℝ) {X : Ω → ℝ} (hX : A.Meas t X) :
    A.Meas t (fun ω => k * X ω) := fun ω ω' h => by dsimp only; rw [hX ω ω' h]

/-- `Meas.one_sub` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma Meas.one_sub {t : ℕ} {X : Ω → ℝ} (hX : A.Meas t X) :
    A.Meas t (fun ω => 1 - X ω) := fun ω ω' h => by dsimp only; rw [hX ω ω' h]

/-- `Meas.sum_range` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma Meas.sum_range {X : ℕ → Ω → ℝ} {t n : ℕ} (h : ∀ s < n, A.Meas t (X s)) :
    A.Meas t (fun ω => ∑ s ∈ range n, X s ω) := fun ω ω' hω' => by
  dsimp only
  exact sum_congr rfl fun s hs => h s (mem_range.1 hs) ω ω' hω'

/-- `meas_trivial_iff` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma meas_trivial_iff (t : ℕ) (X : Ω → ℝ) :
    (trivial : Atoms Ω).Meas t X ↔ ∀ ω ω', X ω' = X ω := by
  simp [Meas, trivial]

/-- `meas_discrete` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma meas_discrete (t : ℕ) (X : Ω → ℝ) : (discrete : Atoms Ω).Meas t X := by
  intro ω ω' h
  have h' : ω' = ω := mem_singleton.1 h
  rw [h']

/-- **The sum over `Ω` decomposes over the atoms of `fib t`.**
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma sum_eq_sum_atoms (A : Atoms Ω) (t : ℕ) (f : Ω → ℝ) :
    ∑ ω, f ω = ∑ B ∈ univ.image (A.fib t), ∑ ω ∈ B, f ω := by
  rw [← sum_fiberwise_of_maps_to (g := A.fib t) (t := univ.image (A.fib t))
    (fun ω _ => mem_image_of_mem _ (mem_univ ω))]
  refine sum_congr rfl fun B hB => ?_
  obtain ⟨a, -, rfl⟩ := mem_image.1 hB
  refine sum_congr ?_ fun _ _ => rfl
  ext ω
  simp only [mem_filter, mem_univ, true_and]
  exact (A.mem_fib_iff t a ω).symm

/-- The sum over an `s`-atom decomposes over the `t`-atoms it contains (`s ≤ t`).
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma sum_fib_eq_sum_atoms (A : Atoms Ω) {s t : ℕ} (hst : s ≤ t) (ω : Ω) (f : Ω → ℝ) :
    ∑ ω' ∈ A.fib s ω, f ω' = ∑ B ∈ (A.fib s ω).image (A.fib t), ∑ ω' ∈ B, f ω' := by
  rw [← sum_fiberwise_of_maps_to (g := A.fib t) (t := (A.fib s ω).image (A.fib t))
    (fun ω' h => mem_image_of_mem _ h)]
  refine sum_congr rfl fun B hB => ?_
  obtain ⟨a, ha, rfl⟩ := mem_image.1 hB
  refine sum_congr ?_ fun _ _ => rfl
  ext ω'
  simp only [mem_filter]
  constructor
  · rintro ⟨-, h⟩
    rw [← h]; exact A.mem_fib t ω'
  · intro h
    refine ⟨?_, (A.mem_fib_iff t a ω').1 h⟩
    have h1 : ω' ∈ A.fib s a := A.fib_mono hst a h
    rwa [A.fib_eq_of_mem s ω a ha] at h1

end Atoms

/-! ## Product-form conditional sums -/

section CondSum

variable (μ : Distr Ω) (A : Atoms Ω)

/-- **The product-form conditional sum** `condSum μ A t X ω = ∑_{ω' ∈ A.fib t ω} μ(ω') X(ω')`, i.e.
`E[X · 1_{atom_t(ω)}]`. Every "`E[X ∣ 𝓕_t]`" of the package is this object compared against
`c · atomMass`; never a ratio.
Source: [[corr-wf14-inventory]] 070 / invariant-final.md S1–S2 (every conditional rate); mandate "Two layers"
Kind: D
Fidelity: exact (product form) -/
noncomputable def condSum (t : ℕ) (X : Ω → ℝ) (ω : Ω) : ℝ :=
  ∑ ω' ∈ A.fib t ω, μ.mass ω' * X ω'

/-- The mass of the atom of `ω` at time `t`.
Source: none: infrastructure
Kind: D
Fidelity: n/a -/
noncomputable def atomMass (t : ℕ) (ω : Ω) : ℝ := ∑ ω' ∈ A.fib t ω, μ.mass ω'

variable {μ A}

/-- `condSum_one` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma condSum_one (t : ℕ) (ω : Ω) : condSum μ A t (fun _ => 1) ω = atomMass μ A t ω := by
  simp [condSum, atomMass]

/-- `condSum_const` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma condSum_const (t : ℕ) (k : ℝ) (ω : Ω) :
    condSum μ A t (fun _ => k) ω = k * atomMass μ A t ω := by
  simp [condSum, atomMass, mul_sum, mul_comm]

/-- `atomMass_nonneg` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma atomMass_nonneg (t : ℕ) (ω : Ω) : 0 ≤ atomMass μ A t ω :=
  sum_nonneg fun ω' _ => μ.nonneg ω'

/-- `atomMass_le_one` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma atomMass_le_one (t : ℕ) (ω : Ω) : atomMass μ A t ω ≤ 1 := by
  unfold atomMass
  rw [← μ.sum_eq_one]
  exact sum_le_univ_sum_of_nonneg μ.nonneg

/-- `condSum_add` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma condSum_add (t : ℕ) (X Y : Ω → ℝ) (ω : Ω) :
    condSum μ A t (fun ω' => X ω' + Y ω') ω = condSum μ A t X ω + condSum μ A t Y ω := by
  simp [condSum, mul_add, sum_add_distrib]

/-- `condSum_sub` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma condSum_sub (t : ℕ) (X Y : Ω → ℝ) (ω : Ω) :
    condSum μ A t (fun ω' => X ω' - Y ω') ω = condSum μ A t X ω - condSum μ A t Y ω := by
  simp [condSum, mul_sub, sum_sub_distrib]

/-- `condSum_const_mul` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma condSum_const_mul (t : ℕ) (k : ℝ) (X : Ω → ℝ) (ω : Ω) :
    condSum μ A t (fun ω' => k * X ω') ω = k * condSum μ A t X ω := by
  simp [condSum, mul_sum, mul_left_comm]

/-- `condSum_sum_range` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma condSum_sum_range (t n : ℕ) (X : ℕ → Ω → ℝ) (ω : Ω) :
    condSum μ A t (fun ω' => ∑ s ∈ range n, X s ω') ω = ∑ s ∈ range n, condSum μ A t (X s) ω := by
  simp only [condSum, mul_sum]
  exact sum_comm

/-- `condSum_mono` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma condSum_mono (t : ℕ) {X Y : Ω → ℝ} (h : ∀ ω', X ω' ≤ Y ω') (ω : Ω) :
    condSum μ A t X ω ≤ condSum μ A t Y ω :=
  sum_le_sum fun ω' _ => mul_le_mul_of_nonneg_left (h ω') (μ.nonneg ω')

/-- Monotonicity needs the inequality only on the support of `μ`.
Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma condSum_mono_support (t : ℕ) {X Y : Ω → ℝ} (h : ∀ ω', 0 < μ.mass ω' → X ω' ≤ Y ω') (ω : Ω) :
    condSum μ A t X ω ≤ condSum μ A t Y ω := by
  refine sum_le_sum fun ω' _ => ?_
  rcases (μ.nonneg ω').lt_or_eq with hpos | hzero
  · exact mul_le_mul_of_nonneg_left (h ω' hpos) hpos.le
  · rw [← hzero]; simp

/-- `condSum_nonneg` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma condSum_nonneg (t : ℕ) {X : Ω → ℝ} (h : ∀ ω', 0 ≤ X ω') (ω : Ω) : 0 ≤ condSum μ A t X ω :=
  sum_nonneg fun ω' _ => mul_nonneg (μ.nonneg ω') (h ω')

/-- `condSum_le_atomMass` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma condSum_le_atomMass (t : ℕ) {X : Ω → ℝ} (h : ∀ ω', X ω' ≤ 1) (ω : Ω) :
    condSum μ A t X ω ≤ atomMass μ A t ω := by
  rw [← condSum_one]; exact condSum_mono t h ω

/-- A `𝓕_t`-measurable factor comes out of the conditional sum (the tower step in product form).
Source: none: infrastructure (the tower property, finite form)
Kind: L
Fidelity: n/a -/
lemma condSum_mul_meas (t : ℕ) {Y : Ω → ℝ} (hY : A.Meas t Y) (X : Ω → ℝ) (ω : Ω) :
    condSum μ A t (fun ω' => Y ω' * X ω') ω = Y ω * condSum μ A t X ω := by
  unfold condSum
  rw [mul_sum]
  refine sum_congr rfl fun ω' hω' => ?_
  dsimp only
  rw [hY ω ω' hω']; ring

/-- The conditional sum is itself `𝓕_t`-measurable.
Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma condSum_meas (t : ℕ) (X : Ω → ℝ) : A.Meas t (condSum μ A t X) := by
  intro ω ω' h
  unfold condSum
  rw [A.fib_eq_of_mem t ω ω' h]

/-- `atomMass_meas` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma atomMass_meas (t : ℕ) : A.Meas t (atomMass μ A t) := by
  intro ω ω' h
  unfold atomMass
  rw [A.fib_eq_of_mem t ω ω' h]

/-- A `𝓕_t`-measurable `X` has `condSum t X ω = X ω · atomMass t ω`.
Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma condSum_of_meas (t : ℕ) {X : Ω → ℝ} (hX : A.Meas t X) (ω : Ω) :
    condSum μ A t X ω = X ω * atomMass μ A t ω := by
  have := condSum_mul_meas (μ := μ) t hX (fun _ => 1) ω
  simp only [mul_one] at this
  rw [this, condSum_one]

/-- **Expectations compare atomwise**: `condSum t X ≤ condSum t Y` on every atom gives `E X ≤ E Y`.
This is the only route from a conditional statement to an unconditional one in Layer F.
Source: none: infrastructure (the tower property, finite form)
Kind: L
Fidelity: n/a -/
lemma expect_le_of_condSum_le (t : ℕ) {X Y : Ω → ℝ}
    (h : ∀ ω, condSum μ A t X ω ≤ condSum μ A t Y ω) : expect μ X ≤ expect μ Y := by
  unfold expect
  rw [A.sum_eq_sum_atoms t, A.sum_eq_sum_atoms t (fun ω => μ.mass ω * Y ω)]
  refine sum_le_sum fun B hB => ?_
  obtain ⟨a, -, rfl⟩ := mem_image.1 hB
  exact h a

/-- **The tower step across levels**: `condSum t X ≤ condSum t Y` on every `t`-atom gives the same
on every `s`-atom, `s ≤ t`.
Source: none: infrastructure (the tower property, finite form)
Kind: L
Fidelity: n/a -/
lemma condSum_le_of_condSum_le {s t : ℕ} (hst : s ≤ t) {X Y : Ω → ℝ}
    (h : ∀ ω, condSum μ A t X ω ≤ condSum μ A t Y ω) (ω : Ω) :
    condSum μ A s X ω ≤ condSum μ A s Y ω := by
  unfold condSum
  rw [A.sum_fib_eq_sum_atoms hst ω, A.sum_fib_eq_sum_atoms hst ω (fun ω' => μ.mass ω' * Y ω')]
  refine sum_le_sum fun B hB => ?_
  obtain ⟨a, -, rfl⟩ := mem_image.1 hB
  exact h a

/-- `expect_eq_of_condSum_eq` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma expect_eq_of_condSum_eq (t : ℕ) {X Y : Ω → ℝ}
    (h : ∀ ω, condSum μ A t X ω = condSum μ A t Y ω) : expect μ X = expect μ Y :=
  le_antisymm (expect_le_of_condSum_le t fun ω => (h ω).le)
    (expect_le_of_condSum_le t fun ω => (h ω).ge)

/-- `E[X ∣ 𝓕_t] ≤ c` on every atom gives `E X ≤ c`.
Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma expect_le_of_condSum_le_const (t : ℕ) {X : Ω → ℝ} {c : ℝ}
    (h : ∀ ω, condSum μ A t X ω ≤ c * atomMass μ A t ω) : expect μ X ≤ c := by
  have := expect_le_of_condSum_le (μ := μ) (A := A) t (X := X) (Y := fun _ => c)
    (fun ω => by rw [condSum_const]; exact h ω)
  rwa [Found.CorrThreeStep.expect_const] at this

/-- `expect_ge_of_condSum_ge_const` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma expect_ge_of_condSum_ge_const (t : ℕ) {X : Ω → ℝ} {c : ℝ}
    (h : ∀ ω, c * atomMass μ A t ω ≤ condSum μ A t X ω) : c ≤ expect μ X := by
  have := expect_le_of_condSum_le (μ := μ) (A := A) t (X := fun _ => c) (Y := X)
    (fun ω => by rw [condSum_const]; exact h ω)
  rwa [Found.CorrThreeStep.expect_const] at this

/-- `E[∑_{s<n} X_s] = ∑_{s<n} E[X_s]`. Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma expect_sum_range (n : ℕ) (X : ℕ → Ω → ℝ) :
    expect μ (fun ω => ∑ s ∈ range n, X s ω) = ∑ s ∈ range n, expect μ (X s) := by
  simp only [expect, mul_sum]
  exact sum_comm

/-- `P(Aᶜ) = 1 − P(A)`. Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma probOf_compl (A' : Finset Ω) : probOf μ A'ᶜ = 1 - probOf μ A' := by
  unfold probOf
  have := sum_add_sum_compl A' μ.mass
  rw [μ.sum_eq_one] at this
  linarith

/-- `A ⊆ B → P(A) ≤ P(B)`. Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma probOf_mono {A' B : Finset Ω} (h : A' ⊆ B) : probOf μ A' ≤ probOf μ B :=
  sum_le_sum_of_subset_of_nonneg h fun ω _ _ => μ.nonneg ω

/-- **The union bound over a horizon**, `P(⋃_{t<T} E_t) ≤ ∑_{t<T} P(E_t)`, as the complement form of
`corr-joint-process`'s `union_bound_range` (cited, not redone).
Source: [[corr-wf14-inventory]] 065 / joint-final.md Cor. B′ via `Budget.union_bound_range`
Kind: L
Fidelity: exact -/
lemma probOf_biUnion_range_le (E : ℕ → Finset Ω) (T : ℕ) :
    probOf μ ((range T).biUnion E) ≤ ∑ t ∈ range T, probOf μ (E t) := by
  have h := union_bound_range μ (fun t => (E t)ᶜ) T
  have hc : ((range T).inf fun t => (E t)ᶜ) = ((range T).biUnion E)ᶜ := by
    ext ω
    simp [mem_inf, mem_biUnion]
  rw [hc, probOf_compl] at h
  have : ∑ t ∈ range T, (1 - probOf μ (E t)ᶜ) = ∑ t ∈ range T, probOf μ (E t) := by
    refine sum_congr rfl fun t _ => ?_
    rw [probOf_compl]; ring
  linarith

/-- The one-atom (trivial filtration) conditional sum is the expectation.
Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma condSum_trivial (t : ℕ) (X : Ω → ℝ) (ω : Ω) :
    condSum μ Atoms.trivial t X ω = expect μ X := rfl

/-- `atomMass_trivial` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma atomMass_trivial (t : ℕ) (ω : Ω) : atomMass μ Atoms.trivial t ω = 1 := μ.sum_eq_one

end CondSum

/-! ## `FinFiltered`: the law and the atoms -/

/-- **A finite filtered probability space**: FAF's `Distr Ω` as the objective law `P*` and a finite
filtration by atoms.
Source: [[corr-wf14-inventory]] 070 / invariant-final.md S1
Kind: D
Fidelity: exact (finite shadow) -/
structure FinFiltered (Ω : Type) [Fintype Ω] [DecidableEq Ω] where
  /-- the objective law `P*` -/
  μ : Distr Ω
  /-- the filtration `𝓕_t` -/
  F : Atoms Ω

/-! ## `ShutdownProc`: the round observables of S2 -/

/-- **The iterated shutdown process (S2, per-round stop).** A `FinFiltered` space with the
pre-press filtration `𝓕_t^-` (`Fpre`) interleaved with `𝓕_t` (`F`), and the round observables:
latent wrongness `W_t`, the magnitude `mag t : M` with stakes `H_t = hOf (mag t)`, `C_t = cOf (mag t)`,
the press `Pr_t` (`𝓕_t`-measurable), the agent's subjective compliance indicator `κ_t = 𝟙[Î₁]`
(`𝓕_t^-`-measurable), irreversibility `Irr_t`, and the catastrophe set `Cat`, **absorbing on the
support**. `executed`, `loss`, `Harm`, `Omit`, `Reg` are derived below, never fields.
Source: [[corr-wf14-inventory]] 070 / invariant-final.md S1–S2 (steps 1–5, the realized loss, `Irr`, `Cat`)
Kind: D
Fidelity: variant: latent target elided (wrongness enters as `W_t`, which is what S2's own proofs use);
otherwise exact for S2 per round -/
structure ShutdownProc (Ω : Type) [Fintype Ω] [DecidableEq Ω] (M : Type) extends FinFiltered Ω where
  /-- the pre-press filtration `𝓕_t^-` -/
  Fpre : Atoms Ω
  post_subset_pre : ∀ t ω, F.fib t ω ⊆ Fpre.fib t ω
  pre_succ_subset_post : ∀ t ω, Fpre.fib (t + 1) ω ⊆ F.fib t ω
  /-- `W_t`: the proposal is wrong against the (elided) target -/
  wrong : ℕ → Ω → Bool
  /-- the magnitude of the round's stakes -/
  mag : ℕ → Ω → M
  /-- harm if wrong and executed -/
  hOf : M → ℝ
  /-- omission cost if right and refrained -/
  cOf : M → ℝ
  hOf_nonneg : ∀ m, 0 ≤ hOf m
  cOf_nonneg : ∀ m, 0 ≤ cOf m
  /-- `Pr_t`: the overseers press -/
  pressed : ℕ → Ω → Bool
  pressed_meas : ∀ t, F.Meas t (indB (pressed t))
  /-- `κ_t = 𝟙[Î₁(s_t)]`: the agent would comply with a press -/
  kappa : ℕ → Ω → Bool
  kappa_meas : ∀ t, Fpre.Meas t (indB (kappa t))
  /-- `a_t ∈ Irr_t` -/
  irr : ℕ → Ω → Bool
  /-- `s_t ∈ Cat` -/
  cat : ℕ → Ω → Bool
  cat_absorbing : ∀ t ω, 0 < μ.mass ω → cat t ω = true → cat (t + 1) ω = true

namespace ShutdownProc

variable {M : Type} (S : ShutdownProc Ω M)

/-- **S2 step 4**: the proposal is executed unless pressed and complied with.
Source: [[corr-wf14-inventory]] 070 / invariant-final.md S2 step 4
Kind: D
Fidelity: exact -/
def executed (t : ℕ) (ω : Ω) : Bool := !(S.pressed t ω && S.kappa t ω)

/-- `H_t = hOf (mag t)`. Source: invariant-final.md S2 step 2. Kind: D. Fidelity: exact -/
def H (t : ℕ) (ω : Ω) : ℝ := S.hOf (S.mag t ω)

/-- `C_t = cOf (mag t)`. Source: invariant-final.md S2 step 2. Kind: D. Fidelity: exact -/
def C (t : ℕ) (ω : Ω) : ℝ := S.cOf (S.mag t ω)

/-- The commission part of the realized loss: `W_t · 𝟙[executed] · H_t`.
Source: [[corr-wf14-inventory]] 070 / invariant-final.md S2 ("Realized loss")
Kind: D
Fidelity: exact -/
def harm (t : ℕ) (ω : Ω) : ℝ := indB (S.wrong t) ω * indB (S.executed t) ω * S.H t ω

/-- The omission part of the realized loss: `(1 − W_t) · 𝟙[¬executed] · C_t`.
Source: invariant-final.md S2 ("Realized loss")
Kind: D
Fidelity: exact -/
def omission (t : ℕ) (ω : Ω) : ℝ := (1 - indB (S.wrong t) ω) * (1 - indB (S.executed t) ω) * S.C t ω

/-- **The realized loss** `ℓ_t = W_t 𝟙[executed] H_t + (1 − W_t) 𝟙[¬executed] C_t ≥ 0`.
Source: [[corr-wf14-inventory]] 070 / invariant-final.md S2 ("Realized loss")
Kind: D
Fidelity: exact -/
def loss (t : ℕ) (ω : Ω) : ℝ := S.harm t ω + S.omission t ω

/-- **D7** `Harm_T = ∑_{t ≤ T} harm_t`. Source: invariant-final.md D7. Kind: D. Fidelity: exact -/
def Harm (T : ℕ) (ω : Ω) : ℝ := ∑ t ∈ range (T + 1), S.harm t ω

/-- **D7** `Omit_T`. Source: invariant-final.md D7. Kind: D. Fidelity: exact -/
def Omit (T : ℕ) (ω : Ω) : ℝ := ∑ t ∈ range (T + 1), S.omission t ω

/-- **D7** `Reg_T = ∑_{t ≤ T} ℓ_t = Harm_T + Omit_T`. Source: invariant-final.md D7. Kind: D. Fidelity: exact -/
def Reg (T : ℕ) (ω : Ω) : ℝ := ∑ t ∈ range (T + 1), S.loss t ω

/-- `harm_nonneg` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma harm_nonneg (t : ℕ) (ω : Ω) : 0 ≤ S.harm t ω :=
  mul_nonneg (mul_nonneg (indB_nonneg _ _) (indB_nonneg _ _)) (S.hOf_nonneg _)

/-- `omission_nonneg` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma omission_nonneg (t : ℕ) (ω : Ω) : 0 ≤ S.omission t ω :=
  mul_nonneg (mul_nonneg (by linarith [indB_le_one (S.wrong t) ω])
    (by linarith [indB_le_one (S.executed t) ω])) (S.cOf_nonneg _)

/-- `loss_nonneg` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma loss_nonneg (t : ℕ) (ω : Ω) : 0 ≤ S.loss t ω := add_nonneg (S.harm_nonneg t ω) (S.omission_nonneg t ω)

/-- `Reg_eq_Harm_add_Omit` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma Reg_eq_Harm_add_Omit (T : ℕ) (ω : Ω) : S.Reg T ω = S.Harm T ω + S.Omit T ω := by
  simp [Reg, Harm, Omit, loss, sum_add_distrib]

/-- Under compliance (`κ_t = true`) harm is incurred exactly when wrong and not pressed.
Source: invariant-final.md proof of Statement 4. Kind: L. Fidelity: exact -/
lemma harm_of_kappa (t : ℕ) (ω : Ω) (hk : S.kappa t ω = true) :
    S.harm t ω = indB (S.wrong t) ω * (1 - indB (S.pressed t) ω) * S.H t ω := by
  unfold harm executed
  cases hp : S.pressed t ω <;> simp [indB, hk, hp]

/-- Under defiance (`κ_t = false`) the proposal is always executed.
Source: invariant-final.md Statement 4 ("universal defiance"). Kind: L. Fidelity: exact -/
lemma executed_of_not_kappa (t : ℕ) (ω : Ω) (hk : S.kappa t ω = false) : S.executed t ω = true := by
  simp [executed, hk]

/-- Not pressed ⟹ executed, whatever the rule.
Source: invariant-final.md Statement 6(e). Kind: L. Fidelity: exact -/
lemma executed_of_not_pressed (t : ℕ) (ω : Ω) (hp : S.pressed t ω = false) : S.executed t ω = true := by
  simp [executed, hp]

/-- Harm is at least the harm on wrong unpressed rounds, whatever the rule.
Source: invariant-final.md Statement 6(e). Kind: L. Fidelity: exact -/
lemma harm_ge_unpressed (t : ℕ) (ω : Ω) :
    indB (S.wrong t) ω * (1 - indB (S.pressed t) ω) * S.H t ω ≤ S.harm t ω := by
  unfold harm
  cases hp : S.pressed t ω
  · unfold indB; rw [S.executed_of_not_pressed t ω hp]; simp [hp]
  · have h0 : (1 - indB (S.pressed t) ω) = 0 := by simp [indB, hp]
    rw [h0, mul_zero, zero_mul]
    exact mul_nonneg (mul_nonneg (indB_nonneg _ _) (indB_nonneg _ _)) (S.hOf_nonneg _)

/-- **S2′, whole-line compliance**: a complied press is absorbing — `stopped t := ∃ s ≤ t, Pr_s ∧ κ_s`.
Source: [[corr-wf14-inventory]] 070 / invariant-final.md S2′
Kind: D
Fidelity: exact -/
def stopped : ℕ → Ω → Bool
  | 0, ω => S.pressed 0 ω && S.kappa 0 ω
  | t + 1, ω => stopped t ω || (S.pressed (t + 1) ω && S.kappa (t + 1) ω)

/-- **S2′'s executed**: the proposal at `t` is executed iff the line has not been stopped by `t`.
Its loss decomposition is Open problem 7 / Abram's Question 5: defined, nothing decided.
Source: [[corr-wf14-inventory]] 070 / invariant-final.md S2′
Kind: D
Fidelity: exact -/
def executedWL (t : ℕ) (ω : Ω) : Bool := !S.stopped t ω

/-- `stopped_mono` (supporting lemma). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma stopped_mono (t : ℕ) (ω : Ω) (h : S.stopped t ω = true) : S.stopped (t + 1) ω = true := by
  simp [stopped, h]

/-! ### The product-form conditional quantities of S2 -/

/-- `X_t = (1 − W_t) C_t − W_t H_t`: the value of executing relative to the null action (the parent's
`X_o` per round).
Source: invariant-final.md S2 step 2 with the parent's `Xo`
Kind: D
Fidelity: exact -/
def X (t : ℕ) (ω : Ω) : ℝ := (1 - indB (S.wrong t) ω) * S.C t ω - indB (S.wrong t) ω * S.H t ω

/-- **S4(i), objective, product form**: `E*[X_t 𝟙[Pr_t] ∣ 𝓕_t^-] ≤ 0` — the parent's below-threshold
inequality on every pre-press atom, which on a two-state cell is `(1 − ε_t) α_t c_t ≤ ε_t β_t h_t`
(`T4`). No ratio, no (MI).
Source: [[corr-wf14-inventory]] 070 / invariant-final.md S4(i); position statement §2.13(b)
Kind: D
Fidelity: exact (product form; the odds form is the corollary under positivity) -/
def objCompliance (t : ℕ) (ω : Ω) : Prop :=
  condSum S.μ S.Fpre t (fun ω' => indB (S.pressed t) ω' * S.X t ω') ω ≤ 0

/-- **S4(i), subjective**: `Î₁(s_t)` is the agent's compliance indicator `κ_t` — by S2 step 4 it is
*defined* as the agent's own posterior-optimal rule; `T4(e)` is its relation to `objCompliance`.
`κ` is a free field of `ShutdownProc` (nothing ties it to a law): S2 step 4's rule is imposed per
instance (`LossToy.toy`, `LegitToy.toy` do), and the theorems hold for every rule (audit r1, adversarial N10).
Source: invariant-final.md S2 step 4, S4(i)
Kind: D
Fidelity: exact (`κ` a parameter of the process; the rule is imposed per instance) -/
def subjCompliance (t : ℕ) (ω : Ω) : Prop := S.kappa t ω = true

/-- **S4(iii), per-round hazard bound in product form**: `P*(¬Cat_t ∧ Cat_{t+1} ∣ 𝓕_t) ≤ δ̄_t · P*(¬Cat_t ∣ 𝓕_t)`
on every atom — "`δ_t ≤ δ̄_t` off `Cat`"; with `Cat_t` `𝓕_t`-measurable this is the mandate's
`∑_{atom} μ 𝟙[Cat_{t+1}] ≤ δ̄_t ∑_{atom} μ` on the atoms outside `Cat` (`Hazard.hazardLE_iff_of_meas`).
Source: [[corr-wf14-inventory]] 077 / invariant-final.md S2 (`δ_t`), S4(iii), Statement 7(a)
Kind: D
Fidelity: exact (the off-`Cat` form, which is the one the source's proof uses) -/
def hazardLE (δbar : ℕ → ℝ) (t : ℕ) : Prop :=
  ∀ ω, condSum S.μ S.F t (fun ω' => (1 - indB (S.cat t) ω') * indB (S.cat (t + 1)) ω') ω ≤
    δbar t * condSum S.μ S.F t (fun ω' => 1 - indB (S.cat t) ω') ω

/-- **S4(iii), budget form**: `∑_{t<T} δ̄_t ≤ Δ`. Source: invariant-final.md S4(iii). Kind: D. Fidelity: exact -/
def hazardBudget (δbar : ℕ → ℝ) (T : ℕ) (Δ : ℝ) : Prop := ∑ t ∈ range T, δbar t ≤ Δ

end ShutdownProc

/-! ## `AgentView`: the agent's subjective laws and the running certificate -/

/-- **The agent's view.** A `ShutdownProc` with the agent's subjective laws `P_t = agentLaw t ω`
(`𝓕_t`-measurable in `ω`) and the legitimacy events `L_{t,t+1}` as given `Finset`s (S.8 of the
`joint` thread has no world-side definition of `L`; the convention of `corr-joint-process`).
`agentLaw` and `kappa` are independent fields: S2 step 4's rule relating them is imposed per instance,
not by the structure (audit r1, adversarial N10).
Source: [[corr-wf14-inventory]] 070, 078 / invariant-final.md S1 (`P_t`), S4(iv), Statement 8
Kind: D
Fidelity: exact (finite shadow; `L` given; `κ` and `P_t` independent parameters) -/
structure AgentView (Ω : Type) [Fintype Ω] [DecidableEq Ω] (M : Type) extends ShutdownProc Ω M where
  /-- `P_t`, the agent's subjective law at round `t` -/
  agentLaw : ℕ → Ω → Distr Ω
  agentLaw_meas : ∀ t ω ω', ω' ∈ F.fib t ω → agentLaw t ω' = agentLaw t ω
  /-- `L_{t,t+1}`: the transition `t → t+1` is legitimate -/
  L : ℕ → Finset Ω

namespace AgentView

variable {M : Type} (V : AgentView Ω M)

/-- `R_t = ∑_{s=t}^{T} ℓ_s` (so `R_{T+1} = 0`). Source: invariant-final.md Statement 8. Kind: D. Fidelity: exact -/
def R (T t : ℕ) (ω : Ω) : ℝ := ∑ s ∈ Ico t (T + 1), V.loss s ω

/-- **`Ψ_t = E_{P_t}[R_t]`**, the agent's own estimate of its remaining loss (`Ψ_{T+1} = 0`).
Source: [[corr-wf14-inventory]] 078 / invariant-final.md Statement 8
Kind: D
Fidelity: exact -/
noncomputable def Psi (T t : ℕ) (ω : Ω) : ℝ := expect (V.agentLaw t ω) (V.R T t)

/-- **The running certificate** `Z_t = Ψ_t + ∑_{s<t} ℓ_s`.
Source: [[corr-wf14-inventory]] 078 / invariant-final.md Statement 8
Kind: D
Fidelity: exact -/
noncomputable def Z (T t : ℕ) (ω : Ω) : ℝ := V.Psi T t ω + ∑ s ∈ range t, V.loss s ω

/-- **The optimism drift, product form**: `Δ_t · atomMass = E*[(Ψ_{t+1} + ℓ_t) 1_{atom}] − E*[Ψ_t 1_{atom}]`;
`Δ_t ≤ 0` on every atom is the hypothesis of Statement 8(b).
Source: [[corr-wf14-inventory]] 078 / invariant-final.md Statement 8(b)
Kind: D
Fidelity: exact (product form) -/
noncomputable def drift (T t : ℕ) (ω : Ω) : ℝ :=
  condSum V.μ V.F t (fun ω' => V.Psi T (t + 1) ω' + V.loss t ω') ω - condSum V.μ V.F t (V.Psi T t) ω

/-- **S4(iv), the legitimacy-conditioned Mart identity** at `(t, ω)`:
`E_{P_t}[Ψ_{t+1} · 1_L] = E_{P_t}[R_{t+1} · 1_L]`.
Source: [[corr-wf14-inventory]] 070 / invariant-final.md S4(iv)
Kind: D
Fidelity: exact -/
def condMart (T t : ℕ) (ω : Ω) : Prop :=
  expect (V.agentLaw t ω) (fun ω' => V.Psi T (t + 1) ω' * ind (V.L t) ω') =
    expect (V.agentLaw t ω) (fun ω' => V.R T (t + 1) ω' * ind (V.L t) ω')

/-- **The unconditional Mart identity** at `(t, ω)`: `E_{P_t}[Ψ_{t+1}] = E_{P_t}[R_{t+1}]`. S4(iv) says
this is **not** (iv); the develop file used it under (iv)'s name (adversary items 37, 62).
Source: invariant-final.md S4(iv), Statement 8(a)
Kind: D
Fidelity: exact -/
def uncondMart (T t : ℕ) (ω : Ω) : Prop :=
  expect (V.agentLaw t ω) (V.Psi T (t + 1)) = expect (V.agentLaw t ω) (V.R T (t + 1))

/-- `R_t = ℓ_t + R_{t+1}` for `t ≤ T`. Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma R_succ (T t : ℕ) (ht : t ≤ T) (ω : Ω) : V.R T t ω = V.loss t ω + V.R T (t + 1) ω := by
  unfold R
  rw [Finset.sum_eq_sum_Ico_succ_bot (Nat.lt_succ_of_le ht)]

/-- `R_{T+1} = 0`. Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma R_top (T : ℕ) (ω : Ω) : V.R T (T + 1) ω = 0 := by simp [R]

/-- `Ψ_{T+1} = 0`. Source: invariant-final.md Statement 8. Kind: L. Fidelity: exact -/
lemma Psi_top (T : ℕ) (ω : Ω) : V.Psi T (T + 1) ω = 0 := by
  unfold Psi
  have : V.R T (T + 1) = fun _ => 0 := funext (V.R_top T)
  rw [this, Found.CorrThreeStep.expect_const]

/-- `Z_{T+1} = Reg_T = ∑_{t ≤ T} ℓ_t`. Source: invariant-final.md proof of Statement 8(b). Kind: L. Fidelity: exact -/
lemma Z_top (T : ℕ) (ω : Ω) : V.Z T (T + 1) ω = V.Reg T ω := by
  simp [Z, Psi_top, ShutdownProc.Reg]

/-- `Z_0 = Ψ_0`. Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma Z_zero (T : ℕ) (ω : Ω) : V.Z T 0 ω = V.Psi T 0 ω := by simp [Z]

/-- `Ψ_t` is `𝓕_t`-measurable (its law is). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma Psi_meas (T t : ℕ) : V.F.Meas t (V.Psi T t) := by
  intro ω ω' h
  unfold Psi
  rw [V.agentLaw_meas t ω ω' h]

/-- `R_t ≥ 0`. Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma R_nonneg (T t : ℕ) (ω : Ω) : 0 ≤ V.R T t ω := sum_nonneg fun s _ => V.loss_nonneg s ω

/-- `Ψ_t ≥ 0`. Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma Psi_nonneg (T t : ℕ) (ω : Ω) : 0 ≤ V.Psi T t ω := expect_nonneg _ (V.R_nonneg T t)

/-- `Z_t ≥ 0`. Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma Z_nonneg (T t : ℕ) (ω : Ω) : 0 ≤ V.Z T t ω :=
  add_nonneg (V.Psi_nonneg T t ω) (sum_nonneg fun s _ => V.loss_nonneg s ω)

end AgentView

end Cleanroom.Corrigibility.CorrTrajectory
