import Cleanroom.Bli.BliRvcUi.Rvc.Antitone
import Cleanroom.Bli.BliFinite.Coherence
import Cleanroom.Bli.BliFound.Tags

/-!
# `bli-rvc-ui` · Rvc/Finite: real-value coherence (B) is coherence on the threshold atoms (T2.1–T2.2)

**The claim (T2.1, load-bearing; M8 / I9's positive half).** Threshold beliefs about one real
variable are consistent with one distribution on `[0,1]` (`RVC_B`) **iff** they extend to a
valuation satisfying Appendix B's two coherence axioms (`bli-finite`'s `TwoAxiomCoherent`) on the
algebra generated by the threshold atoms, relative to the monotonicity and range facts. So
D-RVC(B) is not a new constraint: it is propositional coherence relative to the right finite stage.

**Route.** Both directions go through the antitone characterization (`Rvc/Antitone.lean`):

* two axioms ⟹ antitone: non-negativity, `V ≤ 1`, monotonicity along a stage implication
  (`TwoAxiomCoherent.mono`), stage tautologies price `1`, stage contradictions price `0`
  (`bli-finite`'s consequence lemmas). No injectivity needed.
* antitone ⟹ two axioms: the rational mixture of point values becomes a rational probability on
  FAF's `FiniteWorld B` (one finite world per point, holding `X.gt r` iff `r < x`), which is a
  world marginal supported on worlds holding the facts; `bli-finite`'s
  `twoAxiom_of_worldMarginal` (Paul's `2^N`-worlds table) closes. This direction needs the
  thresholds to be **distinct atoms** (`hatom`, `hinj`), discharged by every fresh-atom witness and
  by every FAF quote LUV (a single quotation atom per threshold, injective in `r`).

The equivalence is stated with "extends to" on the two-axiom side, because `RVC_B` constrains `V`
on the threshold atoms only while the two axioms constrain the whole generated algebra
(`bli-finite`'s `coherentOn_iff_twoAxiom` has the same shape). The one-way
`rvcB_of_twoAxiom` needs no injectivity.

**Witnesses (T2.2).** `R = {1/4, 1/2, 3/4}`, `V = (3/4, 1/2, 1/4)` is `RVC_B` with the mixture
exhibited; `V = (1/4, 1/2, 3/4)` is not, and admits no two-axiom extension: the definition
excludes something.
-/

namespace Cleanroom.Bli.BliRvcUi

open LogicalInduction LO.Propositional Finset BoolPCWorld Cleanroom.Bli.BliFinite Cleanroom.Bli.BliFound

/-! ## The antitone characterization transfers along agreement on the thresholds -/

/-- Two valuations agreeing on the threshold atoms have the same antitone characterization.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma thresholdAntitone_congr {K : Type*} [Field K] [LinearOrder K] [IsStrictOrderedRing K]
    {V V' : Sentence → K} {X : LUV} {R : Finset ℚ} (h : ∀ r ∈ R, V' (X.gt r) = V (X.gt r)) :
    ThresholdAntitone V' X R ↔ ThresholdAntitone V X R := by
  unfold ThresholdAntitone
  constructor
  · rintro ⟨h0, h1, h2, h3⟩
    exact ⟨fun r hr => h r hr ▸ h0 r hr, fun r hr r' hr' hlt => h r hr ▸ h r' hr' ▸ h1 r hr r' hr' hlt,
      fun r hr hlt => h r hr ▸ h2 r hr hlt, fun r hr hle => h r hr ▸ h3 r hr hle⟩
  · rintro ⟨h0, h1, h2, h3⟩
    exact ⟨fun r hr => h r hr ▸ h0 r hr, fun r hr r' hr' hlt => h r hr ▸ h r' hr' ▸ h1 r hr r' hr' hlt,
      fun r hr hlt => h r hr ▸ h2 r hr hlt, fun r hr hle => h r hr ▸ h3 r hr hle⟩

/-! ## Two axioms ⟹ antitone -/

/-- `genBy_gt`.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma genBy_gt {X : LUV} {R : Finset ℚ} {r : ℚ} (hr : r ∈ R) :
    GenBy (thresholdAtoms X R) (X.gt r) :=
  GenBy.base (mem_thresholdAtoms.mpr ⟨r, hr, rfl⟩)

/-- **The two axioms on the threshold algebra, relative to the monotonicity and range facts, force
the antitone characterization.** No injectivity of the thresholds is needed.
Source: mandate T2.1 (⟹); bli-slides-014 (B); bli-soto-a-051
Kind: P
Fidelity: exact
Hyps: (a) -/
theorem thresholdAntitone_of_twoAxiom {V : Sentence → ℚ} {X : LUV} {R : Finset ℚ}
    (h : TwoAxiomCoherent V (thresholdAtoms X R) (monoFacts X R ∪ rangeFacts X R)) :
    ThresholdAntitone V X R := by
  refine ⟨fun r hr => ⟨h.1 _ (genBy_gt hr), h.le_one (genBy_gt hr)⟩,
    fun r hr r' hr' hlt => ?_, fun r hr hlt => ?_, fun r hr hle => ?_⟩
  · refine h.mono (genBy_gt hr) (genBy_gt hr') fun v hv hgt => ?_
    exact (hv _ (Finset.mem_union_left _ (monoFact_mem hr hr' hlt))) hgt
  · exact h.2.1 _ (genBy_gt hr) fun v hv =>
      hv _ (Finset.mem_union_right _ (rangeFact_neg_mem hr hlt))
  · refine h.contradiction_zero (genBy_gt hr) fun v hv hgt => ?_
    exact (PCWorld.holds_neg v _).mp (hv _ (Finset.mem_union_right _ (rangeFact_one_mem hr hle))) hgt

/-- **`RVC_B` from the two axioms** (one way, no injectivity): a valuation satisfying Appendix B's
axioms on the threshold algebra relative to the monotonicity and range facts is, on the
thresholds, the profile of a finite mixture of point values.
Source: mandate T2.1 (⟹); [[bli-program]] M8
Kind: C
Fidelity: exact
Hyps: (a) -/
theorem rvcB_of_twoAxiom {V : Sentence → ℚ} {X : LUV} {R : Finset ℚ}
    (h : TwoAxiomCoherent V (thresholdAtoms X R) (monoFacts X R ∪ rangeFacts X R)) :
    RVC_B (fun φ => (V φ : ℝ)) X R :=
  rvcB_iff_antitone.mpr (thresholdAntitone_cast_iff.mpr (thresholdAntitone_of_twoAxiom h))

/-! ## Antitone ⟹ a two-axiom extension (through finite worlds) -/

section Worlds

variable {X : LUV} {R : Finset ℚ}

/-- The finite world of a point value `x`: holds the atom of `X.gt r` (for `r ∈ R`) iff `r < x`.
Source: mandate T2.1 route ("a cut-pattern is a point value")
Kind: D
Fidelity: n/a -/
noncomputable def pointWorld (X : LUV) (R : Finset ℚ) (B : ℕ) (x : ℚ) : FiniteWorld B :=
  fun a => decide (∃ r ∈ R, X.gt r = Formula.atom a.1 ∧ r < x)

/-- The atom bound covering the threshold atoms.
Source: none: infrastructure
Kind: D
Fidelity: n/a -/
def thresholdBound (X : LUV) (R : Finset ℚ) : ℕ := (thresholdAtoms X R).sup atomBound

/-- The atom code of a threshold lies below the bound.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma atom_lt_thresholdBound {r : ℚ} (hr : r ∈ R) {a : ℕ} (ha : X.gt r = Formula.atom a) :
    a < thresholdBound X R := by
  have h : atomBound (X.gt r) ≤ (thresholdAtoms X R).sup atomBound :=
    Finset.le_sup (f := atomBound) (mem_thresholdAtoms.mpr ⟨r, hr, rfl⟩)
  rw [ha] at h
  simp only [atomBound] at h
  unfold thresholdBound
  omega

/-- The point world holds `X.gt r`, `r ∈ R`, iff `r < x` (thresholds are distinct atoms).
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma holds_pointWorld_gt (hatom : ∀ r ∈ R, ∃ a, X.gt r = Formula.atom a)
    (hinj : ∀ r ∈ R, ∀ r' ∈ R, X.gt r = X.gt r' → r = r') (x : ℚ) {r : ℚ} (hr : r ∈ R) :
    (worldOf (pointWorld X R (thresholdBound X R) x)).Holds (X.gt r) ↔ r < x := by
  obtain ⟨a, ha⟩ := hatom r hr
  have hlt : a < thresholdBound X R := atom_lt_thresholdBound hr ha
  rw [ha, worldOf, ← eval_eq_true_iff_holds]
  simp only [eval, FiniteWorld.toBoolPCWorld, hlt, dite_true, pointWorld, decide_eq_true_eq]
  constructor
  · rintro ⟨r', hr', hr'a, hlt'⟩
    have : r' = r := hinj r' hr' r hr (hr'a.trans ha.symm)
    exact this ▸ hlt'
  · intro hlt'
    exact ⟨r, hr, ha, hlt'⟩

/-- A point world with `0 ≤ x ≤ 1` holds the monotonicity and range facts.
Source: mandate T2.1 route
Kind: L
Fidelity: n/a -/
lemma pointWorld_consistent (hatom : ∀ r ∈ R, ∃ a, X.gt r = Formula.atom a)
    (hinj : ∀ r ∈ R, ∀ r' ∈ R, X.gt r = X.gt r' → r = r') {x : ℚ} (hx0 : 0 ≤ x) (hx1 : x ≤ 1) :
    (worldOf (pointWorld X R (thresholdBound X R) x)).ConsistentWith
      (monoFacts X R ∪ rangeFacts X R) := by
  intro φ hφ
  rw [Finset.mem_union] at hφ
  rcases hφ with hφ | hφ
  · obtain ⟨r, hr, r', hr', hlt, rfl⟩ := mem_monoFacts.mp hφ
    change (worldOf (pointWorld X R (thresholdBound X R) x)).Holds (X.gt r) →
      (worldOf (pointWorld X R (thresholdBound X R) x)).Holds (X.gt r')
    intro hgt
    rw [holds_pointWorld_gt hatom hinj x hr] at hgt
    rw [holds_pointWorld_gt hatom hinj x hr']
    exact lt_trans hlt hgt
  · rcases mem_rangeFacts.mp hφ with ⟨r, hr, hlt, rfl⟩ | ⟨r, hr, hle, rfl⟩
    · rw [holds_pointWorld_gt hatom hinj x hr]
      exact lt_of_lt_of_le hlt hx0
    · rw [PCWorld.holds_neg, holds_pointWorld_gt hatom hinj x hr]
      exact not_lt.mpr (le_trans hx1 hle)

/-- `payoutRat` of a point world on a threshold is the indicator `[r < x]`.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma payoutRat_pointWorld_gt (hatom : ∀ r ∈ R, ∃ a, X.gt r = Formula.atom a)
    (hinj : ∀ r ∈ R, ∀ r' ∈ R, X.gt r = X.gt r' → r = r') (x : ℚ) {r : ℚ} (hr : r ∈ R) :
    (pointWorld X R (thresholdBound X R) x).payoutRat (X.gt r) = if r < x then 1 else 0 := by
  have h := holds_pointWorld_gt hatom hinj x hr
  rw [worldOf, ← eval_eq_true_iff_holds] at h
  unfold FiniteWorld.payoutRat
  by_cases hlt : r < x
  · rw [if_pos hlt, if_pos (h.mpr hlt)]
  · rw [if_neg hlt, if_neg (fun he => hlt (h.mp he))]

end Worlds

/-- **An antitone threshold profile extends to a two-axiom-coherent valuation** relative to the
monotonicity and range facts, when the thresholds are distinct atoms. The extension is the world
marginal of the rational mixture of point worlds.
Source: mandate T2.1 (⟸); bli-finite `twoAxiom_of_worldMarginal`
Kind: P
Fidelity: exact
Hyps: (a) `hatom`/`hinj` (thresholds are distinct atoms) are the witnesses' data -/
theorem exists_twoAxiom_of_thresholdAntitone {V : Sentence → ℚ} {X : LUV} {R : Finset ℚ}
    (hatom : ∀ r ∈ R, ∃ a, X.gt r = Formula.atom a)
    (hinj : ∀ r ∈ R, ∀ r' ∈ R, X.gt r = X.gt r' → r = r') (h : ThresholdAntitone V X R) :
    ∃ V' : Sentence → ℚ, (∀ r ∈ R, V' (X.gt r) = V (X.gt r)) ∧
      TwoAxiomCoherent V' (thresholdAtoms X R) (monoFacts X R ∪ rangeFacts X R) := by
  classical
  obtain ⟨m, hm, htot, hV⟩ := exists_mixture_of_thresholdAntitone h
  set B := thresholdBound X R with hB
  let U : Fin m.length → FiniteWorld B := fun i => pointWorld X R B (m.get i).1
  let w : FiniteWorld B → ℚ := fun u => ∑ i, if u = U i then (m.get i).2 else 0
  have hw0 : ∀ u, 0 ≤ w u := fun u => Finset.sum_nonneg fun i _ => by
    split_ifs
    · exact (hm _ (List.get_mem m i)).2.2
    · exact le_rfl
  have hw1 : ∑ u, w u = 1 := by
    show ∑ u, ∑ i, (if u = U i then (m.get i).2 else 0) = 1
    rw [Finset.sum_comm]
    simp only [Finset.sum_ite_eq', Finset.mem_univ, if_true]
    rw [sum_fin_get (fun p : ℚ × ℚ => p.2) m]
    exact htot
  have hwD : ∀ u, w u ≠ 0 → (worldOf u).ConsistentWith (monoFacts X R ∪ rangeFacts X R) := by
    intro u hu
    obtain ⟨i, -, hi⟩ := Finset.exists_ne_zero_of_sum_ne_zero hu
    have hui : u = U i := by
      by_contra hne
      exact hi (if_neg hne)
    rw [hui]
    exact pointWorld_consistent hatom hinj (hm _ (List.get_mem m i)).1 (hm _ (List.get_mem m i)).2.1
  refine ⟨fun φ => ∑ u, w u * u.payoutRat φ, fun r hr => ?_, ?_⟩
  · show ∑ u, (∑ i, if u = U i then (m.get i).2 else 0) * u.payoutRat (X.gt r) = V (X.gt r)
    simp_rw [Finset.sum_mul]
    rw [Finset.sum_comm]
    simp only [ite_mul, zero_mul, Finset.sum_ite_eq', Finset.mem_univ, if_true]
    rw [hV r hr, mixMass]
    simp only [Rat.cast_id]
    rw [← sum_fin_get (fun p : ℚ × ℚ => if r < p.1 then p.2 else 0) m]
    apply Finset.sum_congr rfl
    intro i _
    rw [payoutRat_pointWorld_gt hatom hinj _ hr]
    split_ifs <;> simp
  · exact twoAxiom_of_worldMarginal ⟨w, hw0, hw1, hwD, fun _ _ => rfl⟩

/-- **T2.1 — `RVC_B` ⟺ a two-axiom-coherent extension on the threshold algebra relative to the
monotonicity and range facts** (load-bearing). Real-value coherence (B) of one variable *is*
propositional coherence on its threshold atoms, given the process's monotonicity and range facts.
Source: bli-slides-014 (B); bli-soto-a-051; bli-paper-048; [[bli-program]] M8; [[bli-program-desiderata]] D-RVC(B)
Kind: P
Fidelity: exact (finite-mixture reading of (B); "extends to" on the two-axiom side, as the axioms
constrain the whole generated algebra)
Hyps: (a) `hatom`/`hinj` (thresholds are pairwise distinct atoms; discharged by the fresh-atom
witnesses and by FAF's quote LUVs) -/
theorem rvcB_iff_twoAxiom {V : Sentence → ℚ} {X : LUV} {R : Finset ℚ}
    (hatom : ∀ r ∈ R, ∃ a, X.gt r = Formula.atom a)
    (hinj : ∀ r ∈ R, ∀ r' ∈ R, X.gt r = X.gt r' → r = r') :
    (∃ V' : Sentence → ℚ, (∀ r ∈ R, V' (X.gt r) = V (X.gt r)) ∧
      TwoAxiomCoherent V' (thresholdAtoms X R) (monoFacts X R ∪ rangeFacts X R)) ↔
    RVC_B (fun φ => (V φ : ℝ)) X R := by
  constructor
  · rintro ⟨V', hagree, hV'⟩
    have h := (thresholdAntitone_congr hagree).mp (thresholdAntitone_of_twoAxiom hV')
    exact rvcB_iff_antitone.mpr (thresholdAntitone_cast_iff.mpr h)
  · intro h
    exact exists_twoAxiom_of_thresholdAntitone hatom hinj
      (thresholdAntitone_cast_iff.mp (rvcB_iff_antitone.mp h))

/-! ## T2.2 — witnesses -/

/-- A threshold family of fresh atoms (family `8`, day `0`, slot `3`): the variable of the T2.2
witnesses. Thresholds are pairwise distinct atoms.
Source: mandate T2.2 (registry: family `8` = RVC witness thresholds)
Kind: D
Fidelity: n/a -/
def witLuv : LUV where
  gt r := freshAtom 8 (Nat.pair 0 (Nat.pair 3 (Encodable.encode r)))

/-- `witLuv_gt_atom`.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma witLuv_gt_atom (r : ℚ) : ∃ a, witLuv.gt r = Formula.atom a := ⟨_, rfl⟩

/-- `witLuv_gt_inj`.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma witLuv_gt_inj {r r' : ℚ} (h : witLuv.gt r = witLuv.gt r') : r = r' := by
  have h' := (freshAtom_inj.mp h).2
  rw [Nat.pair_eq_pair, Nat.pair_eq_pair] at h'
  exact Encodable.encode_inj.mp h'.2.2

/-- The witness thresholds `{1/4, 1/2, 3/4}`.
Source: mandate T2.2
Kind: D
Fidelity: n/a -/
def witR : Finset ℚ := {1/4, 1/2, 3/4}

/-- The decreasing profile `(3/4, 1/2, 1/4)` on the witness thresholds (`0` elsewhere).
Source: mandate T2.2
Kind: D
Fidelity: n/a -/
noncomputable def witV : Sentence → ℚ := fun φ =>
  if φ = witLuv.gt (1/4) then 3/4 else if φ = witLuv.gt (1/2) then 1/2
  else if φ = witLuv.gt (3/4) then 1/4 else 0

/-- The increasing profile `(1/4, 1/2, 3/4)`.
Source: mandate T2.2
Kind: D
Fidelity: n/a -/
noncomputable def witV' : Sentence → ℚ := fun φ =>
  if φ = witLuv.gt (1/4) then 1/4 else if φ = witLuv.gt (1/2) then 1/2
  else if φ = witLuv.gt (3/4) then 3/4 else 0

/-- `witLuv_gt_ne`: distinct thresholds give distinct sentences (for the concrete values).
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma witLuv_gt_ne {r r' : ℚ} (h : r ≠ r') : witLuv.gt r ≠ witLuv.gt r' :=
  fun he => h (witLuv_gt_inj he)

/-- **`rvcB_witness` (N+)**: the decreasing profile is `RVC_B`, with the mixture exhibited —
mass `1/4` at each of the points `0`, `3/8`, `5/8`, `1` (never on a threshold).
Source: mandate T2.2
Kind: N+
Fidelity: exact -/
theorem rvcB_witness : RVC_B (fun φ => (witV φ : ℝ)) witLuv witR := by
  refine ⟨4, ![0, 3/8, 5/8, 1], ![1/4, 1/4, 1/4, 1/4], ?_, ?_, ?_, ?_⟩
  · intro i; fin_cases i <;> norm_num
  · intro i; fin_cases i <;> norm_num
  · simp [Fin.sum_univ_four]; norm_num
  · intro r hr
    simp only [witR, Finset.mem_insert, Finset.mem_singleton] at hr
    have h12 : witLuv.gt (1/2) ≠ witLuv.gt (1/4) := witLuv_gt_ne (by norm_num)
    have h34 : witLuv.gt (3/4) ≠ witLuv.gt (1/4) := witLuv_gt_ne (by norm_num)
    have h34' : witLuv.gt (3/4) ≠ witLuv.gt (1/2) := witLuv_gt_ne (by norm_num)
    rcases hr with rfl | rfl | rfl
    · simp only [witV, if_true]
      norm_num [Fin.sum_univ_four]
    · simp only [witV]
      rw [if_neg h12]
      simp only [if_true]
      norm_num [Fin.sum_univ_four]
    · simp only [witV]
      rw [if_neg h34, if_neg h34']
      simp only [if_true]
      norm_num [Fin.sum_univ_four]

/-- **`rvcB_fails_increasing` (N−)**: the increasing profile is not `RVC_B` (it violates the antitone
clause at `1/4 < 1/2`), and admits no two-axiom-coherent extension relative to the monotonicity
facts — the definition excludes something.
Source: mandate T2.2
Kind: N-
Fidelity: exact -/
theorem rvcB_fails_increasing :
    ¬ RVC_B (fun φ => (witV' φ : ℝ)) witLuv witR ∧
    ¬ ∃ V' : Sentence → ℚ, (∀ r ∈ witR, V' (witLuv.gt r) = witV' (witLuv.gt r)) ∧
      TwoAxiomCoherent V' (thresholdAtoms witLuv witR) (monoFacts witLuv witR ∪ rangeFacts witLuv witR) := by
  have hnot : ¬ RVC_B (fun φ => (witV' φ : ℝ)) witLuv witR := by
    intro h
    have hanti := (thresholdAntitone_of_rvcB h).2.1 (1/2) (by simp [witR]) (1/4) (by simp [witR])
      (by norm_num)
    have h12 : witLuv.gt (1/2) ≠ witLuv.gt (1/4) := witLuv_gt_ne (by norm_num)
    simp only [witV'] at hanti
    rw [if_neg h12] at hanti
    simp only [if_true] at hanti
    norm_num at hanti
  refine ⟨hnot, fun h => hnot ?_⟩
  exact (rvcB_iff_twoAxiom (fun r _ => witLuv_gt_atom r) (fun r _ r' _ h => witLuv_gt_inj h)).mp h

end Cleanroom.Bli.BliRvcUi
