"""Finite witnesses for the role-parametric answerability prosecution.

This is exploration code, not a promoted specification.  It intentionally keeps
the account checker smaller than the interpersonal standing wrapper.
"""
from __future__ import annotations

from dataclasses import dataclass, replace
from typing import Callable, Iterable, Mapping


Party = str
LiabilityId = str
CertificateId = str


@dataclass(frozen=True, order=True)
class Event:
    actor: Party
    kind: str
    counterparty: Party | None = None


Trace = tuple[Event, ...]
Language = frozenset[Trace]


def prefixes(trace: Trace) -> frozenset[Trace]:
    return frozenset(trace[:i] for i in range(len(trace) + 1))


def safety_language(*maximal_traces: Trace) -> Language:
    """The finite prefix closure generated by the displayed maximal traces."""
    out: set[Trace] = set()
    for trace in maximal_traces:
        out.update(prefixes(trace))
    return frozenset(out)


def derivative(language: Language, event: Event) -> Language:
    return frozenset(trace[1:] for trace in language if trace and trace[0] == event)


def meet(languages: Iterable[Language]) -> Language:
    items = tuple(languages)
    if not items:
        raise ValueError("an account meet needs at least one language")
    out = set(items[0])
    for language in items[1:]:
        out.intersection_update(language)
    return frozenset(out)


@dataclass(frozen=True)
class Liability:
    ident: LiabilityId
    respondent: Party
    specification: Language


@dataclass(frozen=True)
class Certificate:
    ident: CertificateId
    move: Event


@dataclass(frozen=True)
class PublicState:
    standing_certificates: frozenset[CertificateId]
    transfer_grants: frozenset[tuple[LiabilityId, Party, Party]] = frozenset()
    rewrite_grants: frozenset[tuple[LiabilityId, Party]] = frozenset()


@dataclass(frozen=True)
class Rewrite:
    move: Event
    certificate: Certificate
    # Each pair is (old liability id, successor liability ids).  An empty tuple
    # is a closure and therefore also needs a separately scoped witness.
    coverage: tuple[tuple[LiabilityId, tuple[LiabilityId, ...]], ...]
    closed: tuple[tuple[LiabilityId, str], ...] = ()


def check_rewrite(
    old: Mapping[LiabilityId, Liability],
    new: Mapping[LiabilityId, Liability],
    rewrite: Rewrite,
    public: PublicState,
    top_after_move: Language = frozenset({()}),
) -> tuple[str, ...]:
    """Check authorization, lineage, role transfer, and per-input transport."""
    errors: list[str] = []
    if rewrite.certificate.move != rewrite.move:
        errors.append("certificate.move_mismatch")
    if rewrite.certificate.ident not in public.standing_certificates:
        errors.append("certificate.not_standing")

    coverage = dict(rewrite.coverage)
    closed = dict(rewrite.closed)
    if set(coverage) != set(old):
        errors.append("lineage.input_not_total")

    sponsored: set[LiabilityId] = set()
    for old_id, parent in old.items():
        child_ids = coverage.get(old_id, ())
        if not child_ids and old_id not in closed:
            errors.append(f"lineage.forgotten:{old_id}")
            continue
        if (
            rewrite.move.actor != parent.respondent
            and (old_id, rewrite.move.actor) not in public.rewrite_grants
        ):
            errors.append(f"actor.not_respondent:{old_id}")

        child_languages: list[Language] = []
        for child_id in child_ids:
            if child_id not in new:
                errors.append(f"lineage.unknown_child:{child_id}")
                continue
            sponsored.add(child_id)
            child = new[child_id]
            child_languages.append(child.specification)
            if child.respondent != parent.respondent:
                grant = (old_id, parent.respondent, child.respondent)
                if grant not in public.transfer_grants:
                    errors.append(f"role.transfer_unauthorized:{old_id}")

        residual = derivative(parent.specification, rewrite.move)
        if child_languages:
            if not meet(child_languages).issubset(residual):
                errors.append(f"semantic.transport:{old_id}")
        elif residual != top_after_move:
            errors.append(f"semantic.unbacked_closure:{old_id}")

    if sponsored != set(new):
        errors.append("lineage.unsponsored_output")
    return tuple(errors)


def joint_transport_only(
    old: Mapping[LiabilityId, Liability],
    new: Mapping[LiabilityId, Liability],
    event: Event,
) -> bool:
    """The rejected global rule, retained solely to exhibit laundering."""
    return meet(x.specification for x in new.values()).issubset(
        meet(derivative(x.specification, event) for x in old.values())
    )


@dataclass(frozen=True)
class StandingWrapper:
    """The interpersonal layer deliberately absent from ``check_rewrite``."""

    holders: frozenset[tuple[Party, LiabilityId]] = frozenset()
    audiences: frozenset[tuple[Party, LiabilityId]] = frozenset()
    visible: frozenset[tuple[Party, str]] = frozenset()
    challenge_rights: frozenset[tuple[Party, LiabilityId]] = frozenset()
    recognized_standing: frozenset[CertificateId] = frozenset()


def answerable_to(
    party: Party,
    liability: Liability,
    certificate: Certificate,
    account_id: str,
    wrapper: StandingWrapper,
) -> bool:
    has_relational_standing = (
        (party, liability.ident) in wrapper.holders
        or (party, liability.ident) in wrapper.audiences
    )
    return (
        has_relational_standing
        and (party, certificate.ident) in wrapper.visible
        and (party, account_id) in wrapper.visible
        and (party, liability.ident) in wrapper.challenge_rights
    )


@dataclass(frozen=True)
class ReasonViews:
    private: tuple[tuple[Party, frozenset[CertificateId]], ...]
    recognized: frozenset[CertificateId]

    def private_stands(self, party: Party, certificate: CertificateId) -> bool:
        return certificate in dict(self.private)[party]


def raise_challenge(views: ReasonViews) -> ReasonViews:
    """A challenge record alone has no constitutive effect on standing."""
    return views


def adjudicate(
    views: ReasonViews, certificate: CertificateId, successful: bool
) -> ReasonViews:
    recognized = set(views.recognized)
    if successful:
        recognized.discard(certificate)
    return replace(views, recognized=frozenset(recognized))


def basis_losses(
    before: ReasonViews, after: ReasonViews, used: frozenset[CertificateId]
) -> frozenset[CertificateId]:
    return frozenset((before.recognized - after.recognized) & used)


def private_basis_verdicts(
    views: ReasonViews, certificate: CertificateId
) -> frozenset[bool]:
    return frozenset(certificate in standing for _, standing in views.private)


def relabel_event(event: Event, rename: Mapping[Party, Party]) -> Event:
    return Event(
        rename.get(event.actor, event.actor),
        event.kind,
        None if event.counterparty is None else rename.get(event.counterparty, event.counterparty),
    )


def relabel_language(language: Language, rename: Mapping[Party, Party]) -> Language:
    return frozenset(tuple(relabel_event(event, rename) for event in trace) for trace in language)


def relabel_liability(liability: Liability, rename: Mapping[Party, Party]) -> Liability:
    return Liability(
        liability.ident,
        rename.get(liability.respondent, liability.respondent),
        relabel_language(liability.specification, rename),
    )


def relabel_public(public: PublicState, rename: Mapping[Party, Party]) -> PublicState:
    return PublicState(
        public.standing_certificates,
        frozenset(
            (ident, rename.get(source, source), rename.get(target, target))
            for ident, source, target in public.transfer_grants
        ),
        frozenset(
            (ident, rename.get(actor, actor))
            for ident, actor in public.rewrite_grants
        ),
    )


def relabel_rewrite(rewrite: Rewrite, rename: Mapping[Party, Party]) -> Rewrite:
    move = relabel_event(rewrite.move, rename)
    certificate = Certificate(rewrite.certificate.ident, move)
    return Rewrite(move, certificate, rewrite.coverage, rewrite.closed)


def factorizes(
    reason_trace: object,
    policies: Iterable[object],
    response: Callable[[object, object], object],
) -> bool:
    outputs = {response(reason_trace, policy) for policy in policies}
    return len(outputs) <= 1
