import Mathlib.MeasureTheory.Function.ConditionalExpectation.PullOut
import Mathlib.MeasureTheory.Function.ConditionalExpectation.Real

/-!
# Gallow's theorem without finiteness (S1), over Mathlib's `condExp`

Package `lit-weatherson-frames` (faf-cleanroom run, 2026-09-30). The paper's remark (l. 52) that
Gallow's result "does not make any finiteness assumptions": over a probability space `(Ω, μ)`,
bounded measurable experts `A, B` and an integrable target `Y`, deference is
`μ[Y | σ(A)] =ᵐ A`, and fixed linear pooling is `μ[Y | σ(A) ⊔ σ(B)] =ᵐ λ A + (1 − λ) B`. The
proof is the finite one: the tower property gives `μ[B | σ(A)] =ᵐ A`, pull-out gives
`∫ A B = ∫ A²`, symmetrically `∫ A B = ∫ B²`, so `∫ (A − B)² = 0` and `A =ᵐ B`. This module
imports measure theory and is kept out of the core's import graph except through the root.
-/

namespace Cleanroom.Lit.LitWeathersonFrames

open MeasureTheory Filter

noncomputable section

variable {Ω : Type} [m0 : MeasurableSpace Ω] {μ : Measure Ω} [IsProbabilityMeasure μ]

/-- The σ-algebra generated by a real random variable, `σ(A) = comap A borel`.
Source: mandate S1
Kind: D
Fidelity: exact -/
abbrev gen (A : Ω → ℝ) : MeasurableSpace Ω := MeasurableSpace.comap A (inferInstance : MeasurableSpace ℝ)

/-- `σ(A) ≤ m0` for measurable `A`.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
theorem gen_le {A : Ω → ℝ} (hA : Measurable A) : gen A ≤ m0 := measurable_iff_comap_le.mp hA

/-- `A` is `σ(A)`-strongly measurable.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
theorem gen_stronglyMeasurable (A : Ω → ℝ) : StronglyMeasurable[gen A] A :=
  (comap_measurable A).stronglyMeasurable

/-- A bounded measurable function is integrable against a probability measure.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
theorem integrable_of_bounded {A : Ω → ℝ} (hA : Measurable A) {M : ℝ} (hM : ∀ ω, |A ω| ≤ M) :
    Integrable A μ :=
  (integrable_const M).mono' hA.aestronglyMeasurable (ae_of_all _ fun ω => by
    rw [Real.norm_eq_abs]; exact hM ω)

/-- Cancelling a nonzero scalar in an a.e. equality.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
theorem ae_eq_of_smul_ae_eq {f g : Ω → ℝ} {c : ℝ} (hc : c ≠ 0) (h : c • f =ᵐ[μ] c • g) :
    f =ᵐ[μ] g := by
  filter_upwards [h] with ω hω
  simp only [Pi.smul_apply, smul_eq_mul] at hω
  exact mul_left_cancel₀ hc hω

/-- **The one-sided step of Gallow's proof, measure-theoretically**: if `μ[Y | σ(A)] =ᵐ A` and
`μ[Y | σ(A) ⊔ σ(B)] =ᵐ λ A + (1 − λ) B` with `λ ≠ 1`, then `μ[B | σ(A)] =ᵐ A` (tower property
and linearity).
Source: mandate S1 (route)
Kind: L
Fidelity: n/a -/
theorem condExp_expert_of_pool {A B Y : Ω → ℝ} (hA : Measurable A) (hB : Measurable B)
    (hAi : Integrable A μ) (hBi : Integrable B μ) {lam : ℝ} (h1 : lam ≠ 1)
    (hdA : μ[Y | gen A] =ᵐ[μ] A)
    (hpool : μ[Y | gen A ⊔ gen B] =ᵐ[μ] lam • A + (1 - lam) • B) :
    μ[B | gen A] =ᵐ[μ] A := by
  have hmA : gen A ≤ m0 := gen_le hA
  have hmAB : gen A ⊔ gen B ≤ m0 := sup_le (gen_le hA) (gen_le hB)
  have hAle : gen A ≤ gen A ⊔ gen B := le_sup_left
  -- tower: μ[μ[Y | mAB] | mA] =ᵐ μ[Y | mA] =ᵐ A
  have hT : μ[μ[Y | gen A ⊔ gen B] | gen A] =ᵐ[μ] A :=
    (condExp_condExp_of_le hAle hmAB).trans hdA
  have hT' : μ[lam • A + (1 - lam) • B | gen A] =ᵐ[μ] A :=
    (condExp_congr_ae hpool.symm).trans hT
  -- linearity
  have hlin : μ[lam • A + (1 - lam) • B | gen A] =ᵐ[μ] lam • A + (1 - lam) • μ[B | gen A] := by
    refine (condExp_add (hAi.smul lam) (hBi.smul (1 - lam)) (gen A)).trans ?_
    refine (condExp_smul lam A (gen A)).add (condExp_smul (1 - lam) B (gen A)) |>.trans ?_
    rw [condExp_of_stronglyMeasurable hmA (gen_stronglyMeasurable A) hAi]
  have hkey : (1 - lam) • μ[B | gen A] =ᵐ[μ] (1 - lam) • A := by
    filter_upwards [hlin, hT'] with ω h₁ h₂
    simp only [Pi.add_apply, Pi.smul_apply, smul_eq_mul] at h₁ h₂ ⊢
    linarith
  exact ae_eq_of_smul_ae_eq (sub_ne_zero.mpr (Ne.symm h1)) hkey

/-- `∫ A · B = ∫ A · A` when `μ[B | σ(A)] =ᵐ A` (pull-out property).
Source: mandate S1 (route)
Kind: L
Fidelity: n/a -/
theorem integral_mul_eq_of_condExp {A B : Ω → ℝ} (hA : Measurable A) {M : ℝ}
    (hM : ∀ ω, |A ω| ≤ M) (hBi : Integrable B μ) (h : μ[B | gen A] =ᵐ[μ] A) :
    ∫ ω, A ω * B ω ∂μ = ∫ ω, A ω * A ω ∂μ := by
  have hmA : gen A ≤ m0 := gen_le hA
  have hABi : Integrable (fun ω => A ω * B ω) μ :=
    hBi.bdd_mul hA.aestronglyMeasurable (ae_of_all _ fun ω => by
      rw [Real.norm_eq_abs]; exact hM ω)
  have hpull : μ[(fun ω => A ω * B ω) | gen A] =ᵐ[μ] fun ω => A ω * (μ[B | gen A]) ω :=
    condExp_mul_of_stronglyMeasurable_left (gen_stronglyMeasurable A) hABi hBi
  calc ∫ ω, A ω * B ω ∂μ = ∫ ω, (μ[(fun ω => A ω * B ω) | gen A]) ω ∂μ :=
        (integral_condExp hmA).symm
    _ = ∫ ω, A ω * (μ[B | gen A]) ω ∂μ := integral_congr_ae hpull
    _ = ∫ ω, A ω * A ω ∂μ := integral_congr_ae (by
        filter_upwards [h] with ω hω
        rw [hω])

/-- **S1. Gallow's theorem over a probability space** (no finiteness): for bounded measurable
experts `A, B` and any target `Y`, if `μ[Y | σ(A)] =ᵐ A`, `μ[Y | σ(B)] =ᵐ B` and
`μ[Y | σ(A) ⊔ σ(B)] =ᵐ λ A + (1 − λ) B` with `λ ∉ {0, 1}`, then `A =ᵐ B`.
Source: [[Deference and Infinite Frames]] §1 ll. 45–52 (Gallow 2018; "does not make any
finiteness assumptions"); inventory 021 (general case); mandate S1
Kind: P
Fidelity: stronger: `λ ∉ {0,1}`, any target `Y`, bounded (rather than `[0,1]`-valued) experts
Hyps: (a) all — the three conditional-expectation identities are the theorem's own hypotheses -/
theorem gallow_condExp {A B Y : Ω → ℝ} (hA : Measurable A) (hB : Measurable B)
    {MA MB : ℝ} (hMA : ∀ ω, |A ω| ≤ MA) (hMB : ∀ ω, |B ω| ≤ MB)
    {lam : ℝ} (h0 : lam ≠ 0) (h1 : lam ≠ 1)
    (hdA : μ[Y | gen A] =ᵐ[μ] A) (hdB : μ[Y | gen B] =ᵐ[μ] B)
    (hpool : μ[Y | gen A ⊔ gen B] =ᵐ[μ] lam • A + (1 - lam) • B) : A =ᵐ[μ] B := by
  have hAi : Integrable A μ := integrable_of_bounded hA hMA
  have hBi : Integrable B μ := integrable_of_bounded hB hMB
  -- the two one-sided identities
  have hBA : μ[B | gen A] =ᵐ[μ] A := condExp_expert_of_pool hA hB hAi hBi h1 hdA hpool
  have hAB : μ[A | gen B] =ᵐ[μ] B := by
    have hpool' : μ[Y | gen B ⊔ gen A] =ᵐ[μ] (1 - lam) • B + (1 - (1 - lam)) • A := by
      rw [sup_comm]
      refine hpool.trans (ae_of_all _ fun ω => ?_)
      simp only [Pi.add_apply, Pi.smul_apply, smul_eq_mul]; ring
    exact condExp_expert_of_pool hB hA hBi hAi (by intro h; apply h0; linarith) hdB hpool'
  have e1 : ∫ ω, A ω * B ω ∂μ = ∫ ω, A ω * A ω ∂μ := integral_mul_eq_of_condExp hA hMA hBi hBA
  have e2 : ∫ ω, B ω * A ω ∂μ = ∫ ω, B ω * B ω ∂μ := integral_mul_eq_of_condExp hB hMB hAi hAB
  -- integrability of the products
  have hAA : Integrable (fun ω => A ω * A ω) μ :=
    hAi.bdd_mul hA.aestronglyMeasurable (ae_of_all _ fun ω => by rw [Real.norm_eq_abs]; exact hMA ω)
  have hBB : Integrable (fun ω => B ω * B ω) μ :=
    hBi.bdd_mul hB.aestronglyMeasurable (ae_of_all _ fun ω => by rw [Real.norm_eq_abs]; exact hMB ω)
  have hABi : Integrable (fun ω => A ω * B ω) μ :=
    hBi.bdd_mul hA.aestronglyMeasurable (ae_of_all _ fun ω => by rw [Real.norm_eq_abs]; exact hMA ω)
  have hBAi : Integrable (fun ω => B ω * A ω) μ :=
    hAi.bdd_mul hB.aestronglyMeasurable (ae_of_all _ fun ω => by rw [Real.norm_eq_abs]; exact hMB ω)
  -- ∫ (A − B)² = (∫ A A − ∫ A B) + (∫ B B − ∫ B A) = 0
  have hsq : Integrable (fun ω => (A ω - B ω) ^ 2) μ := by
    have : (fun ω => (A ω - B ω) ^ 2) =
        fun ω => (A ω * A ω - A ω * B ω) + (B ω * B ω - B ω * A ω) := by
      funext ω; ring
    rw [this]
    exact (hAA.sub hABi).add (hBB.sub hBAi)
  have hzero : ∫ ω, (A ω - B ω) ^ 2 ∂μ = 0 := by
    have : (fun ω => (A ω - B ω) ^ 2) =
        fun ω => (A ω * A ω - A ω * B ω) + (B ω * B ω - B ω * A ω) := by
      funext ω; ring
    have i1 : Integrable (fun ω => A ω * A ω - A ω * B ω) μ := hAA.sub hABi
    have i2 : Integrable (fun ω => B ω * B ω - B ω * A ω) μ := hBB.sub hBAi
    rw [this, integral_add i1 i2, integral_sub hAA hABi, integral_sub hBB hBAi, e1, e2]
    ring
  have hae := (integral_eq_zero_iff_of_nonneg (fun ω => sq_nonneg (A ω - B ω)) hsq).mp hzero
  filter_upwards [hae] with ω hω
  simp only [Pi.zero_apply] at hω
  exact sub_eq_zero.mp (pow_eq_zero_iff (n := 2) (by norm_num) |>.mp hω)

end

end Cleanroom.Lit.LitWeathersonFrames
