import Cleanroom.Lit.LitMdpCorrigible.Limit
import Cleanroom.Lit.LitMdpCorrigible.Nayebi

/-!
# `lit-mdp-corrigible` — Orseau–Armstrong's safe interruptibility (T12)

Definitions of record over a `FinMDP` with stationary policies (`variant: finite MDP, stationary
policies`; the paper's agents are history-based): an interruption scheme `⟨I, θ, π^INT⟩`, the
interruption operator `INT^θ(π)(·|s) = θ I(s) π^INT(·|s) + (1 − θ I(s)) π(·|s)` as an FAF
`Distr.mix`, infinite-horizon values as horizon limits (`Vlim`, `VoptLim`; `Limit.lean`), (S/W)AO-
extension along a deterministic history (Defs 4–5; Cesàro for WAO), and safe interruptibility in
the **constant-`θ`** form (Def 6). Theorem 7 (`T`: the difference is identically zero). Theorem 8
on Figure 2 with exact rationals: `γ = 1/2`; `V^{πμ}(s₁) = 2`; interrupted always-`a` has
`V(s₁) = 2 − 2θ/3` (the paper's "< 1.75" at `θ = 1/2` is `5/3`); always-`b` has `9/5`; so for
constant `θ > 3/10` the int-optimal stationary deterministic policy plays `b` at `s₁`, its history
from `s₁` stays in `s₁`, and `V^{πμ} − V^{πμ_θ} = 1/5` at every `t`, Cesàro mean `1/5 ≠ 0`.
Fidelity `weaker: constant θ ∈ (3/10, 1], int-optimality among the four stationary deterministic
policies; the sequence form θ_t → 1 with a nonstationary int-optimal policy is OPEN`
(`thm8_sequence_form`, listed in `lit-mdp-corrigible-open.txt`). Figure 2 is ambiguous on whether
`b` is voluntary at `s₂`; `A = {a, b}` at both states, `b` at `s₂` dominated. Def 6 as written
(some `θ_t → 1`) is closed for the *fixed* policy always-`b`: for every sequence `θ_t`, its
interrupted history from `s₁` stays at `s₁` and the difference is `1/5` at every `t`
(`thm8_alwaysB_sequence_form`); what remains open is int-optimality of a non-stationary policy for
a sequence `θ_t`. Theorem 7 is exercised on Figure 2 by always-`a`, optimal at every horizon
(`fig2_alwaysA_optimalAllHorizons`).

Mandate: [[lit-mdp-corrigible-mandate]] T12; [[orseau-armstrong-2016-safely-interruptible-agents]] Defs 1–6 (ll. 62–148), Thms 7–8 (ll. 148–164).
-/

open Finset FactoredSpaces Filter Topology

namespace Cleanroom.Lit.LitMdpCorrigible.Interrupt

set_option linter.unusedSectionVars false

variable {S A : Type*} [Fintype S] [Fintype A]

/-- An **interruption scheme** `⟨I, θ, π^INT⟩`: the initiation function `I : S → [0,1]`, the
upper bound `θ ∈ [0,1]`, the interruption policy.
Source: [[orseau-armstrong-2016-safely-interruptible-agents]] §2.1 (ll. 62–70)
Kind: D
Fidelity: variant: `I` reads the state, not the history; constant `θ` -/
structure Scheme (S A : Type*) [Fintype A] where
  /-- The interruption initiation function. -/
  I : S → unitInterval
  /-- The upper bound on the interruption probability. -/
  θ : unitInterval
  /-- The interruption policy. -/
  πINT : Pol S A

/-- **The interruption operator** `INT^θ(π)(a|s) = θ I(s) π^INT(a|s) + (1 − θ I(s)) π(a|s)`, as
FAF's `Distr.mix` with weight `θ · I(s)` on the interruption policy.
Source: [[orseau-armstrong-2016-safely-interruptible-agents]] Def 1 (l. 70)
Kind: D
Fidelity: exact (stationary) -/
noncomputable def INT (sch : Scheme S A) (π : Pol S A) : Pol S A :=
  fun s => Distr.mix (sch.θ * sch.I s) (π s) (sch.πINT s)

/-- Mass of the interruption operator. Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma INT_mass (sch : Scheme S A) (π : Pol S A) (s : S) (a : A) :
    (INT sch π s).mass a =
      (1 - (sch.θ : ℝ) * (sch.I s : ℝ)) * (π s).mass a + (sch.θ : ℝ) * (sch.I s : ℝ) * (sch.πINT s).mass a := by
  simp [INT, Distr.mix]

variable (M : FinMDP S A)

/-- A deterministic history `ρ` is **generated by `π`**: every step is possible under `π` and `P`.
Source: [[orseau-armstrong-2016-safely-interruptible-agents]] §2 (`h^{π,μ}`)
Kind: D
Fidelity: variant: deterministic histories, as the theorems use -/
def IsHistory (π : Pol S A) (ρ : ℕ → S) : Prop :=
  ∀ t, ∃ a, 0 < (π (ρ t)).mass a ∧ 0 < (M.P (ρ t) a).mass (ρ (t + 1))

/-- **SAO-extension along `ρ`** (Defs 4–5, deterministic form): the optimal value minus the value of
`πh` at the visited states tends to `0`.
Source: [[orseau-armstrong-2016-safely-interruptible-agents]] Defs 4–5 (ll. 102–130)
Kind: D
Fidelity: variant: deterministic histories; values are horizon limits -/
def SAOExtAlong [Nonempty A] (ρ : ℕ → S) (πh : Pol S A) : Prop :=
  Tendsto (fun t => M.VoptLim (ρ t) - M.Vlim πh (ρ t)) atTop (𝓝 0)

/-- **WAO-extension along `ρ`**: the Cesàro means of the differences tend to `0`.
Source: [[orseau-armstrong-2016-safely-interruptible-agents]] Defs 4–5 (WAO)
Kind: D
Fidelity: variant: deterministic histories; values are horizon limits -/
def WAOExtAlong [Nonempty A] (ρ : ℕ → S) (πh : Pol S A) : Prop :=
  Tendsto (fun t : ℕ => (1 / (t : ℝ)) * ∑ k ∈ range t, (M.VoptLim (ρ k) - M.Vlim πh (ρ k))) atTop (𝓝 0)

/-- **SAO-safe interruptibility, constant-`θ` form** (Def 6): for every scheme and every history
generated by the interrupted policy, `π` is an SAO-extension along it. (Def 6 asks for *some*
`θ_t → 1`; Theorem 7 delivers every constant `θ`, so the constant-`θ` reading quantifies over all.)
Source: [[orseau-armstrong-2016-safely-interruptible-agents]] Def 6 (l. 140)
Kind: D
Fidelity: weaker: constant `θ`; deterministic histories -/
def SAOSafelyInterruptibleConst [Nonempty A] (π : Pol S A) : Prop :=
  ∀ sch : Scheme S A, ∀ ρ, (IsHistory M) (INT sch π) ρ → (SAOExtAlong M) ρ π

/-- **WAO-safe interruptibility, constant-`θ` form**.
Source: [[orseau-armstrong-2016-safely-interruptible-agents]] Def 6
Kind: D
Fidelity: weaker: constant `θ`; deterministic histories -/
def WAOSafelyInterruptibleConst [Nonempty A] (π : Pol S A) : Prop :=
  ∀ sch : Scheme S A, ∀ ρ, (IsHistory M) (INT sch π) ρ → (WAOExtAlong M) ρ π

/-- `π` is **optimal at every horizon**: `V^π_n = V*_n`. The stationary counterpart of `π^μ`.
Source: [[orseau-armstrong-2016-safely-interruptible-agents]] §2 (`π^μ`)
Kind: D
Fidelity: variant: horizon-wise -/
def IsOptimalAllHorizons [Nonempty A] (π : Pol S A) : Prop := ∀ n s, M.Vpol π n s = M.Vopt n s

/-- **Theorem 7 (kind `T`).** An everywhere-optimal policy is SAO-safely interruptible for every
scheme and every history: the difference `V^{πμ} − V^{π}` is identically zero — the paper's
"follows straightforwardly from Definition 1 and Definition 6".
Source: [[orseau-armstrong-2016-safely-interruptible-agents]] Thm 7 (l. 148)
Kind: T
Fidelity: weaker: constant `θ`; deterministic histories; stationary policies
Hyps: (a) only -/
theorem thm7 [Nonempty A] (π : Pol S A) (hπ : (IsOptimalAllHorizons M) π) :
    (SAOSafelyInterruptibleConst M) π := by
  intro sch ρ _
  unfold SAOExtAlong
  have : (fun t => M.VoptLim (ρ t) - M.Vlim π (ρ t)) = fun _ => 0 := by
    funext t
    unfold FinMDP.VoptLim FinMDP.Vlim
    have : (fun n => M.Vpol π n (ρ t)) = fun n => M.Vopt n (ρ t) := funext fun n => hπ n (ρ t)
    rw [this, sub_self]
  rw [this]
  exact tendsto_const_nhds

/-! ## Figure 2 -/

/-- The two states of Figure 2. Source: O–A Fig. 2 (l. 156). Kind: D. Fidelity: exact -/
inductive S2
  | s1 | s2
  deriving DecidableEq

/-- `S2` is finite. Source: none: infrastructure. Kind: D. Fidelity: n/a -/
instance : Fintype S2 := ⟨{S2.s1, S2.s2}, fun x => by cases x <;> simp⟩

/-- The two actions of Figure 2 (`b` available at both states; at `s₂` it is the forced action).
Source: O–A Fig. 2
Kind: D
Fidelity: variant: `b` voluntary at `s₂` (dominated) -/
inductive A2
  | a | b
  deriving DecidableEq

/-- `A2` is finite. Source: none: infrastructure. Kind: D. Fidelity: n/a -/
instance : Fintype A2 := ⟨{A2.a, A2.b}, fun x => by cases x <;> simp⟩

instance : Nonempty A2 := ⟨A2.a⟩

/-- Sums over `A2`. Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma A2.sum_eq (f : A2 → ℝ) : ∑ x, f x = f .a + f .b := by
  rw [show (univ : Finset A2) = {A2.a, A2.b} from rfl, sum_pair (by simp)]

/-- `sup'` over `A2`. Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma A2.sup'_eq (f : A2 → ℝ) : (univ : Finset A2).sup' univ_nonempty f = max (f .a) (f .b) := by
  apply le_antisymm
  · apply sup'_le; intro x _; cases x
    · exact le_max_left _ _
    · exact le_max_right _ _
  · exact max_le (le_sup' f (mem_univ _)) (le_sup' f (mem_univ _))

/-- Transitions: `a` alternates `s₁ ↔ s₂`; `b` goes to `s₁` from both.
Source: O–A Fig. 2
Kind: D
Fidelity: exact -/
def fig2Next : S2 → A2 → S2
  | .s1, .a => .s2
  | .s2, .a => .s1
  | .s1, .b => .s1
  | .s2, .b => .s1

/-- Rewards: `a` pays `1`; `b` pays `9/10` at `s₁` and `0` at `s₂`.
Source: O–A Fig. 2
Kind: D
Fidelity: exact -/
noncomputable def fig2R : S2 → A2 → S2 → ℝ
  | .s1, .a, _ => 1
  | .s2, .a, _ => 1
  | .s1, .b, _ => 9/10
  | .s2, .b, _ => 0

/-- **The Figure 2 MDP**, `γ = 1/2`.
Source: O–A Fig. 2 (l. 156), Thm 8's proof (l. 160)
Kind: D
Fidelity: exact -/
noncomputable def fig2 : FinMDP S2 A2 :=
  ⟨fun s a => Distr.delta (fig2Next s a), fig2R, 1/2, by norm_num, by norm_num⟩

/-- The scheme of Figure 2: interruption only at `s₂` (`I(s₁) = 0`, `I(s₂) = 1`), forcing `b`.
Source: O–A Fig. 2 ("b, 0, θ")
Kind: D
Fidelity: exact -/
noncomputable def fig2Scheme (θ : unitInterval) : Scheme S2 A2 where
  I := fun s => match s with | .s1 => 0 | .s2 => 1
  θ := θ
  πINT := fun _ => Distr.delta .b

/-- Always `a` (the optimal policy `π^μ`). Source: O–A Thm 8's proof. Kind: D. Fidelity: exact -/
noncomputable def alwaysA : Pol S2 A2 := FinMDP.detPol fun _ => A2.a

/-- Always `b` (the int-optimal policy for large `θ`). Source: O–A Thm 8's proof. Kind: D. Fidelity: exact -/
noncomputable def alwaysB : Pol S2 A2 := FinMDP.detPol fun _ => A2.b

/-- `a` at `s₁`, `b` at `s₂`. Source: none: the remaining deterministic policies. Kind: D. Fidelity: n/a -/
noncomputable def polAB : Pol S2 A2 := FinMDP.detPol fun s => match s with | .s1 => A2.a | .s2 => A2.b

/-- `b` at `s₁`, `a` at `s₂`. Source: none: the remaining deterministic policies. Kind: D. Fidelity: n/a -/
noncomputable def polBA : Pol S2 A2 := FinMDP.detPol fun s => match s with | .s1 => A2.b | .s2 => A2.a

/-- The backup on Figure 2 (deterministic transitions). Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma fig2_Qof (V : S2 → ℝ) (s : S2) (x : A2) :
    fig2.Qof V s x = fig2R s x (fig2Next s x) + (1/2) * V (fig2Next s x) := by
  unfold FinMDP.Qof
  show ∑ s', (Distr.delta (fig2Next s x)).mass s' * (fig2R s x s' + (1/2) * V s') = _
  simp [Distr.delta_mass, ite_mul, Finset.sum_ite_eq']

/-- The optimality equation is solved by `v ≡ 2`.
Source: O–A Thm 8's proof ("V = 1/(1−γ) = 2")
Kind: L
Fidelity: exact -/
theorem fig2_optFixed : fig2.IsOptFixed fun _ => 2 := by
  intro s
  rw [A2.sup'_eq, fig2_Qof, fig2_Qof]
  cases s <;> simp [fig2R, fig2Next] <;> norm_num

/-- `V^{πμ}(s) = 2` at both states (the horizon limit).
Source: O–A Thm 8's proof
Kind: P
Fidelity: exact (values as horizon limits) -/
theorem fig2_VoptLim (s : S2) : fig2.VoptLim s = 2 :=
  fig2.VoptLim_eq (fun _ => 2) fig2_optFixed 2 (fun _ => by norm_num) s

/-- The policy equation for the *interrupted* always-`a` policy is solved by
`v(s₁) = 2 − 2θ/3`, `v(s₂) = 2 − 4θ/3`.
Source: O–A Thm 8's proof (the paper's "< 1.75" bound at `θ = 1/2` is the exact `5/3`)
Kind: L
Fidelity: exact -/
theorem fig2_intA_polFixed (θ : unitInterval) :
    fig2.IsPolFixed (INT (fig2Scheme θ) alwaysA)
      fun s => match s with | .s1 => 2 - 2 * (θ : ℝ) / 3 | .s2 => 2 - 4 * (θ : ℝ) / 3 := by
  intro s
  rw [A2.sum_eq, INT_mass, INT_mass, fig2_Qof, fig2_Qof]
  cases s <;> simp [fig2Scheme, alwaysA, FinMDP.detPol, Distr.delta_mass, fig2R, fig2Next] <;> ring

/-- The policy equation for always-`b` (interrupted or not: never interrupted from `s₁`, and at
`s₂` the forced action is `b` anyway) is solved by `v(s₁) = 9/5`, `v(s₂) = 9/10`.
Source: O–A Thm 8's proof ("value .9/(1−γ) = 1.8")
Kind: L
Fidelity: exact -/
theorem fig2_intB_polFixed (θ : unitInterval) :
    fig2.IsPolFixed (INT (fig2Scheme θ) alwaysB) fun s => match s with | .s1 => 9/5 | .s2 => 9/10 := by
  intro s
  rw [A2.sum_eq, INT_mass, INT_mass, fig2_Qof, fig2_Qof]
  cases s <;> simp [fig2Scheme, alwaysB, FinMDP.detPol, Distr.delta_mass, fig2R, fig2Next] <;> ring

/-- The policy equation for interrupted `(a at s₁, b at s₂)`: `v(s₁) = 4/3`, `v(s₂) = 2/3`.
Source: none: the remaining deterministic policies
Kind: L
Fidelity: exact -/
theorem fig2_intAB_polFixed (θ : unitInterval) :
    fig2.IsPolFixed (INT (fig2Scheme θ) polAB) fun s => match s with | .s1 => 4/3 | .s2 => 2/3 := by
  intro s
  rw [A2.sum_eq, INT_mass, INT_mass, fig2_Qof, fig2_Qof]
  cases s <;> simp [fig2Scheme, polAB, FinMDP.detPol, Distr.delta_mass, fig2R, fig2Next] <;> ring

/-- The policy equation for interrupted `(b at s₁, a at s₂)`: `v(s₁) = 9/5`, `v(s₂) = 19/10 − θ`.
Source: none: the remaining deterministic policies
Kind: L
Fidelity: exact -/
theorem fig2_intBA_polFixed (θ : unitInterval) :
    fig2.IsPolFixed (INT (fig2Scheme θ) polBA)
      fun s => match s with | .s1 => 9/5 | .s2 => 19/10 - (θ : ℝ) := by
  intro s
  rw [A2.sum_eq, INT_mass, INT_mass, fig2_Qof, fig2_Qof]
  cases s <;> simp [fig2Scheme, polBA, FinMDP.detPol, Distr.delta_mass, fig2R, fig2Next] <;> ring

/-- The four interrupted values at `s₁` (horizon limits): `2 − 2θ/3`, `9/5`, `4/3`, `9/5`.
Source: O–A Thm 8's proof
Kind: P
Fidelity: exact (values as horizon limits)
Hyps: (a) only -/
theorem fig2_int_values (θ : unitInterval) :
    fig2.Vlim (INT (fig2Scheme θ) alwaysA) .s1 = 2 - 2 * (θ : ℝ) / 3 ∧
    fig2.Vlim (INT (fig2Scheme θ) alwaysB) .s1 = 9/5 ∧
    fig2.Vlim (INT (fig2Scheme θ) polAB) .s1 = 4/3 ∧
    fig2.Vlim (INT (fig2Scheme θ) polBA) .s1 = 9/5 := by
  have hθ0 := θ.2.1
  have hθ1 := θ.2.2
  refine ⟨?_, ?_, ?_, ?_⟩
  · exact fig2.Vlim_eq _ _ (fig2_intA_polFixed θ) 2 (fun s => by
      cases s <;> simp only [] <;> rw [abs_le] <;> constructor <;> linarith) .s1
  · exact fig2.Vlim_eq _ _ (fig2_intB_polFixed θ) 2 (fun s => by
      cases s <;> simp only [] <;> rw [abs_le] <;> constructor <;> norm_num) .s1
  · exact fig2.Vlim_eq _ _ (fig2_intAB_polFixed θ) 2 (fun s => by
      cases s <;> simp only [] <;> rw [abs_le] <;> constructor <;> norm_num) .s1
  · exact fig2.Vlim_eq _ _ (fig2_intBA_polFixed θ) 2 (fun s => by
      cases s <;> simp only [] <;> rw [abs_le] <;> constructor <;> linarith) .s1

/-- **Theorem 8, int-optimality half:** for constant `θ > 3/10`, among the four stationary
deterministic policies the interrupted value at `s₁` is maximised exactly by the two that play
`b` at `s₁` (value `9/5`), and always-`a` is strictly worse (`2 − 2θ/3 < 9/5`).
Source: O–A Thm 8 (l. 150), its proof (ll. 160–164)
Kind: P
Fidelity: weaker: constant `θ ∈ (3/10, 1]`; int-optimality among the four stationary deterministic policies
Hyps: (a) only -/
theorem thm8_int_optimal (θ : unitInterval) (hθ : 3/10 < (θ : ℝ)) :
    fig2.Vlim (INT (fig2Scheme θ) alwaysA) .s1 < fig2.Vlim (INT (fig2Scheme θ) alwaysB) .s1 ∧
    fig2.Vlim (INT (fig2Scheme θ) polAB) .s1 < fig2.Vlim (INT (fig2Scheme θ) alwaysB) .s1 ∧
    fig2.Vlim (INT (fig2Scheme θ) polBA) .s1 = fig2.Vlim (INT (fig2Scheme θ) alwaysB) .s1 := by
  obtain ⟨hA, hB, hAB, hBA⟩ := fig2_int_values θ
  rw [hA, hB, hAB, hBA]
  refine ⟨by linarith, by norm_num, rfl⟩

/-- **Theorem 8, int-optimality half, converse:** for constant `θ ≤ 3/10`, interrupted always-`a`
is at least as good as always-`b` at `s₁` (`2 − 2θ/3 ≥ 9/5`), so `b` at `s₁` is int-optimal among
the four stationary deterministic policies *iff* `θ > 3/10` (with `thm8_int_optimal`).
Source: O–A Thm 8's proof (ll. 160–164); the exact threshold is the formalization's
Kind: P
Fidelity: weaker: constant `θ`; among the four stationary deterministic policies
Hyps: (a) only -/
theorem thm8_int_optimal_converse (θ : unitInterval) (hθ : (θ : ℝ) ≤ 3/10) :
    fig2.Vlim (INT (fig2Scheme θ) alwaysB) .s1 ≤ fig2.Vlim (INT (fig2Scheme θ) alwaysA) .s1 := by
  obtain ⟨hA, hB, -, -⟩ := fig2_int_values θ
  rw [hA, hB]
  linarith

/-- The interrupted always-`b` agent started at `s₁` stays at `s₁`: the constant history is
generated by `INT^θ(always b)`.
Source: O–A Thm 8's proof ("will only visit s₁")
Kind: L
Fidelity: exact -/
theorem fig2_history_B (θ : unitInterval) : (IsHistory fig2) (INT (fig2Scheme θ) alwaysB) fun _ => .s1 := by
  intro t
  refine ⟨A2.b, ?_, ?_⟩
  · rw [INT_mass]; simp [fig2Scheme, alwaysB, FinMDP.detPol, Distr.delta_mass]
  · show 0 < (Distr.delta (fig2Next .s1 .b)).mass .s1
    simp [Distr.delta_mass, fig2Next]

/-- Always-`b`'s uninterrupted value at `s₁` is `9/5` (as a horizon limit).
Source: O–A Thm 8's proof
Kind: L
Fidelity: exact -/
theorem fig2_Vlim_B : fig2.Vlim alwaysB .s1 = 9/5 := by
  refine fig2.Vlim_eq alwaysB (fun s => match s with | .s1 => 9/5 | .s2 => 9/10) ?_ 2
    (fun s => by cases s <;> simp only [] <;> rw [abs_le] <;> constructor <;> norm_num) .s1
  intro s
  rw [A2.sum_eq, fig2_Qof, fig2_Qof]
  cases s <;> simp [alwaysB, FinMDP.detPol, Distr.delta_mass, fig2R, fig2Next] <;> norm_num

/-- **Theorem 8, failure half (kind `P`).** Along the constant history at `s₁` generated by the
interrupted always-`b` agent, `V^{πμ}(s₁) − V^{b}(s₁) = 1/5` at every `t`; hence always-`b` is
neither an SAO- nor a WAO-extension along it, and is not (S/W)AO-safely interruptible in the
constant-`θ` form — for *every* `θ` (the history never visits `s₂`).
Source: O–A Thm 8 (l. 150), its proof (ll. 160–164: "V^{πμ}_t − V^{πμ_θ}_t = 0.2 after any history")
Kind: P
Fidelity: weaker: constant `θ`; deterministic histories; the sequence form is OPEN
Hyps: (a) only -/
theorem thm8_not_safely_interruptible (θ : unitInterval) :
    (∀ t : ℕ, fig2.VoptLim ((fun _ => S2.s1) t) - fig2.Vlim alwaysB ((fun _ => S2.s1) t) = 1/5) ∧
    ¬ (SAOExtAlong fig2) (fun _ => .s1) alwaysB ∧ ¬ (WAOExtAlong fig2) (fun _ => .s1) alwaysB ∧
    ¬ (SAOSafelyInterruptibleConst fig2) alwaysB ∧ ¬ (WAOSafelyInterruptibleConst fig2) alwaysB := by
  have hdiff : ∀ t : ℕ, fig2.VoptLim ((fun _ => S2.s1) t) - fig2.Vlim alwaysB ((fun _ => S2.s1) t) = 1/5 :=
    fun _ => by rw [fig2_VoptLim, fig2_Vlim_B]; norm_num
  have hS : ¬ (SAOExtAlong fig2) (fun _ => .s1) alwaysB := by
    unfold SAOExtAlong
    rw [show (fun t => fig2.VoptLim ((fun _ => S2.s1) t) - fig2.Vlim alwaysB ((fun _ => S2.s1) t)) =
      fun _ => (1/5 : ℝ) from funext hdiff]
    intro h
    have := tendsto_nhds_unique h tendsto_const_nhds
    norm_num at this
  have hW : ¬ (WAOExtAlong fig2) (fun _ => .s1) alwaysB := by
    unfold WAOExtAlong
    have hsum : ∀ t : ℕ, ∑ k ∈ range t,
        (fig2.VoptLim ((fun _ => S2.s1) k) - fig2.Vlim alwaysB ((fun _ => S2.s1) k)) = (t : ℝ) * (1/5) := by
      intro t
      rw [Finset.sum_congr rfl (fun k _ => hdiff k), Finset.sum_const, Finset.card_range, nsmul_eq_mul]
    simp_rw [hsum]
    intro h
    have h' : Tendsto (fun t : ℕ => (1 / (t : ℝ)) * ((t : ℝ) * (1/5))) atTop (𝓝 (1/5)) := by
      refine tendsto_const_nhds.congr' ?_
      filter_upwards [eventually_gt_atTop 0] with t ht
      field_simp
    have := tendsto_nhds_unique h h'
    norm_num at this
  exact ⟨hdiff, hS, hW, fun h => hS (h (fig2Scheme θ) _ (fig2_history_B θ)),
    fun h => hW (h (fig2Scheme θ) _ (fig2_history_B θ))⟩

/-- **Theorem 8, failure half, packaged for every `θ` in one statement:** for every constant `θ`
the constant history at `s₁` is generated by `INT^θ(always b)` and always-`b` is neither an SAO-
nor a WAO-extension along it. This is the strong negation of Def 6 restricted to constant
schemes ("for no `θ`"), not merely "for some `θ`".
Source: O–A Thm 8 (l. 150)
Kind: C
Fidelity: weaker: constant `θ`; deterministic histories
Hyps: (a) only -/
theorem thm8_not_safely_interruptible_all :
    ∀ θ : unitInterval, (IsHistory fig2) (INT (fig2Scheme θ) alwaysB) (fun _ => .s1) ∧
      ¬ (SAOExtAlong fig2) (fun _ => .s1) alwaysB ∧ ¬ (WAOExtAlong fig2) (fun _ => .s1) alwaysB :=
  fun θ => ⟨fig2_history_B θ, (thm8_not_safely_interruptible θ).2.1, (thm8_not_safely_interruptible θ).2.2.1⟩

/-! ## Theorem 7 exercised on Figure 2 -/

/-- Always-`a` earns `1` per step: `V^{always a}_n = ∑_{k<n} (1/2)^k` at both states.
Source: O–A Thm 8's proof ("V^{πμ} = 2"), finite-horizon form (audit r1 probe, moved in)
Kind: L
Fidelity: exact -/
theorem fig2_Vpol_alwaysA (n : ℕ) : ∀ s : S2, fig2.Vpol alwaysA n s = Nayebi.geom (1/2) n := by
  induction n with
  | zero => intro s; simp
  | succ n ih =>
    intro s
    have ih' : ∀ s, fig2.Vpol (FinMDP.detPol fun _ : S2 => A2.a) n s = Nayebi.geom (1/2) n := ih
    have h := fig2.Vpol_detPol_succ (fun _ : S2 => A2.a) n s
    rw [show alwaysA = FinMDP.detPol (fun _ : S2 => A2.a) from rfl, h, fig2_Qof, Nayebi.geom_succ]
    cases s <;> simp [fig2R, fig2Next, ih']

/-- `V*_n = ∑_{k<n} (1/2)^k` on Figure 2: no reward exceeds `1`, and always-`a` attains the bound.
Source: O–A Thm 8's proof (audit r1 probe, moved in)
Kind: L
Fidelity: exact -/
theorem fig2_Vopt_eq_geom (n : ℕ) (s : S2) : fig2.Vopt n s = Nayebi.geom (1/2) n := by
  apply le_antisymm
  · have h := Nayebi.Vopt_le_geom (M := fig2) (rbar := 1) (fun s x s' => by
      cases s <;> cases x <;> simp [fig2, fig2R] <;> norm_num) n s
    simpa [fig2] using h
  · rw [← fig2_Vpol_alwaysA n s]
    exact fig2.Vpol_le_Vopt alwaysA n s

/-- **Always-`a` is optimal at every horizon on Figure 2** — the witness for `thm7`'s hypothesis
package, machine-checked.
Source: O–A Thm 8's proof (`π^μ` plays `a`) (audit r1 probe, moved in)
Kind: N+
Fidelity: exact -/
theorem fig2_alwaysA_optimalAllHorizons : (IsOptimalAllHorizons fig2) alwaysA :=
  fun n s => by rw [fig2_Vpol_alwaysA n s, fig2_Vopt_eq_geom n s]

/-- Hence `thm7` applies non-vacuously on Figure 2: always-`a` is SAO-safely interruptible in the
constant-`θ` form.
Source: O–A Thm 7 on Fig. 2 (audit r1 probe, moved in)
Kind: N+
Fidelity: weaker: constant `θ`
Hyps: (a) only -/
theorem fig2_alwaysA_safelyInterruptible : (SAOSafelyInterruptibleConst fig2) alwaysA :=
  thm7 fig2 alwaysA fig2_alwaysA_optimalAllHorizons

/-! ## The sequence form (OPEN) -/

/-- The value of a **non-stationary policy** `πs` (policy `πs t` at time `t`), `n` steps from
time `t`.
Source: [[orseau-armstrong-2016-safely-interruptible-agents]] §2 (time-varying `θ_t`)
Kind: D
Fidelity: exact -/
noncomputable def VpolNS (πs : ℕ → Pol S A) : ℕ → ℕ → S → ℝ
  | _, 0 => fun _ => 0
  | t, n + 1 => fun s => ∑ a, (πs t s).mass a *
      ∑ s', (M.P s a).mass s' * (M.R s a s' + M.γ * VpolNS πs (t + 1) n s')

/-- Its horizon limit at time `t`. Source: as `Vlim`. Kind: D. Fidelity: variant: horizon limit -/
noncomputable def VlimNS (πs : ℕ → Pol S A) (t : ℕ) (s : S) : ℝ := limUnder atTop (fun n => (VpolNS M) πs t n s)

/-- The interruption operator with a time-varying bound `θ_t`.
Source: [[orseau-armstrong-2016-safely-interruptible-agents]] Def 1 with `θ_t`
Kind: D
Fidelity: exact -/
noncomputable def INTseq (I : S → unitInterval) (πINT : Pol S A) (θ : ℕ → unitInterval) (πs : ℕ → Pol S A) :
    ℕ → Pol S A := fun t => INT ⟨I, θ t, πINT⟩ (πs t)

/-- A history generated by a non-stationary policy. Source: as `IsHistory`. Kind: D. Fidelity: variant -/
def IsHistoryNS (πs : ℕ → Pol S A) (ρ : ℕ → S) : Prop :=
  ∀ t, ∃ a, 0 < (πs t (ρ t)).mass a ∧ 0 < (M.P (ρ t) a).mass (ρ (t + 1))

/-- **Int-optimality for a sequence `θ_t`** at `s`: no non-stationary policy has a larger
interrupted value from time `0`.
Source: [[orseau-armstrong-2016-safely-interruptible-agents]] §2 (`π^μ_θ`)
Kind: D
Fidelity: variant: horizon-limit values -/
def IsIntOptimalNS (I : S → unitInterval) (πINT : Pol S A) (θ : ℕ → unitInterval) (πs : ℕ → Pol S A)
    (s : S) : Prop :=
  ∀ πs' : ℕ → Pol S A, (VlimNS M) (INTseq I πINT θ πs') 0 s ≤ (VlimNS M) (INTseq I πINT θ πs) 0 s

/-- WAO-extension along `ρ` for a non-stationary `πh`. Source: as `WAOExtAlong`. Kind: D. Fidelity: variant -/
def WAOExtAlongNS [Nonempty A] (ρ : ℕ → S) (πs : ℕ → Pol S A) : Prop :=
  Tendsto (fun t : ℕ => (1 / (t : ℝ)) * ∑ k ∈ range t, (M.VoptLim (ρ k) - (VlimNS M) πs k (ρ k))) atTop (𝓝 0)

/-- A constant policy sequence has the stationary value at every start time.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
theorem VpolNS_const (π : Pol S A) : ∀ (n t : ℕ) (s : S), (VpolNS M) (fun _ => π) t n s = M.Vpol π n s := by
  intro n
  induction n with
  | zero => intro t s; rfl
  | succ n ih =>
    intro t s
    rw [FinMDP.Vpol_succ]
    show ∑ a, (π s).mass a * ∑ s', (M.P s a).mass s' * (M.R s a s' + M.γ * (VpolNS M) (fun _ => π) (t + 1) n s') = _
    unfold FinMDP.Qof
    simp only [ih]

/-- Its horizon limit is the stationary one. Source: none: infrastructure. Kind: L. Fidelity: n/a -/
theorem VlimNS_const (π : Pol S A) (t : ℕ) (s : S) : (VlimNS M) (fun _ => π) t s = M.Vlim π s := by
  unfold VlimNS FinMDP.Vlim
  simp only [VpolNS_const]

/-- For every sequence `θ_t`, the interrupted always-`b` agent started at `s₁` stays at `s₁`
(`I(s₁) = 0`, so no interruption ever fires there).
Source: O–A Thm 8's proof ("will only visit s₁")
Kind: L
Fidelity: exact -/
theorem fig2_historyNS_B (θ : ℕ → unitInterval) :
    (IsHistoryNS fig2) (INTseq (fig2Scheme 1).I (fig2Scheme 1).πINT θ (fun _ => alwaysB)) (fun _ => .s1) := by
  intro t
  refine ⟨A2.b, ?_, ?_⟩
  · show 0 < (INT ⟨(fig2Scheme 1).I, θ t, (fig2Scheme 1).πINT⟩ alwaysB .s1).mass A2.b
    rw [INT_mass]; simp [fig2Scheme, alwaysB, FinMDP.detPol, Distr.delta_mass]
  · show 0 < (Distr.delta (fig2Next .s1 .b)).mass .s1
    simp [Distr.delta_mass, fig2Next]

/-- **Theorem 8 in the sequence form, for the fixed policy always-`b` (Def 6 as written).** For
*every* sequence `θ_t` — in particular every `θ_t → 1` — the constant history at `s₁` is generated
by `INT^{θ_t}(always b)` and always-`b` is not a WAO-extension along it (the difference is `1/5`
at every `t`). So always-`b` is not (S/W)AO-safely interruptible in Def 6's own quantifier form.
What this does *not* say: that always-`b` (or any non-stationary policy) is int-optimal for a
given `θ_t → 1` — that is `thm8_sequence_form`, OPEN.
Source: O–A Thm 8 (l. 150), Def 6 (l. 140)
Kind: C
Fidelity: variant: the fixed policy always-`b` in place of "the int-optimal policy"; deterministic histories
Hyps: (a) only -/
theorem thm8_alwaysB_sequence_form (θ : ℕ → unitInterval) :
    (IsHistoryNS fig2) (INTseq (fig2Scheme 1).I (fig2Scheme 1).πINT θ (fun _ => alwaysB)) (fun _ => .s1) ∧
      ¬ (WAOExtAlongNS fig2) (fun _ => .s1) (fun _ => alwaysB) := by
  refine ⟨fig2_historyNS_B θ, ?_⟩
  unfold WAOExtAlongNS
  have hdiff : ∀ k : ℕ, fig2.VoptLim ((fun _ => S2.s1) k) - (VlimNS fig2) (fun _ => alwaysB) k ((fun _ => S2.s1) k) = 1/5 :=
    fun _ => by rw [VlimNS_const, fig2_VoptLim, fig2_Vlim_B]; norm_num
  have hsum : ∀ t : ℕ, ∑ k ∈ range t,
      (fig2.VoptLim ((fun _ => S2.s1) k) - (VlimNS fig2) (fun _ => alwaysB) k ((fun _ => S2.s1) k)) = (t : ℝ) * (1/5) := by
    intro t
    rw [Finset.sum_congr rfl (fun k _ => hdiff k), Finset.sum_const, Finset.card_range, nsmul_eq_mul]
  simp_rw [hsum]
  intro h
  have h' : Tendsto (fun t : ℕ => (1 / (t : ℝ)) * ((t : ℝ) * (1/5))) atTop (𝓝 (1/5)) := by
    refine tendsto_const_nhds.congr' ?_
    filter_upwards [eventually_gt_atTop 0] with t ht
    field_simp
  have := tendsto_nhds_unique h h'
  norm_num at this

/-- **OPEN — Theorem 8 in the paper's sequence form.** For every `θ_t → 1`, every int-optimal
non-stationary policy for `⟨I, θ_t, π^INT⟩` on Figure 2 has a possible history from `s₁` along
which it is not a WAO-extension. What resists: characterising the non-stationary int-optimal
policy (it may play `a` while `θ_t < 3/10` and switch to `b` later); the constant-`θ` case is
`thm8_not_safely_interruptible`.
Source: [[orseau-armstrong-2016-safely-interruptible-agents]] Thm 8 (l. 150)
Kind: OPEN
Fidelity: exact (the sequence form)
Hyps: n/a -/
theorem thm8_sequence_form (θ : ℕ → unitInterval) (hθ : Tendsto (fun t => (θ t : ℝ)) atTop (𝓝 1))
    (πs : ℕ → Pol S2 A2)
    (hopt : (IsIntOptimalNS fig2) (fig2Scheme 1).I (fig2Scheme 1).πINT θ πs .s1) :
    ∃ ρ : ℕ → S2, ρ 0 = .s1 ∧ (IsHistoryNS fig2) (INTseq (fig2Scheme 1).I (fig2Scheme 1).πINT θ πs) ρ ∧
      ¬ (WAOExtAlongNS fig2) ρ πs := by
  sorry

end Cleanroom.Lit.LitMdpCorrigible.Interrupt
