import Cleanroom.Bli.BliFinite.Index
import LogicalInduction.Framework.BooleanWorlds
import Mathlib.Algebra.BigOperators.Ring.Finset
import Mathlib.Algebra.Order.BigOperators.Group.Finset

/-!
# `bli-finite` · Coherence: the two axioms, world marginals, `CoherentOn` (T3, part 1)

Appendix B (bli-paper-030) calls a price assignment *propositionally coherent* when (i) every
propositional tautology has price 1 and (ii) disjoint disjunctions add. **The paper omits
non-negativity / the `[0,1]` range**, and without it signed valuations satisfy both axioms
(`twoAxiom_signed_counterexample`, `CoherenceExamples.lean`); the definition of record adds
the clause. The axioms are quantified over the algebra `GenBy A` generated by a finite set
`A` — quantifying over the given sentences only is vacuous
(`twoAxiom_on_given_sentences_only_not_coherent`).

This file: the definitions, the consequences derivable from the axioms alone (contradictions
price 0, `V φ + V (∼φ) = 1`, respect for `D`-equivalence, monotonicity, `V ≤ 1`), the easy
direction "a world marginal satisfies the axioms", and `CoherentOn` for tables. The hard
direction (finite de Finetti) is `DeFinetti.lean`.

Convention (mandate design decision 8): worlds are FAF's `FiniteWorld B`, read as `PCWorld`s
through `toBoolPCWorld.toPCWorld`, which reads atoms `≥ B` as `false`; every statement whose
truth depends on that carries `hB : ∀ φ ∈ A ∪ D, atomBound φ ≤ B`.
-/

namespace Cleanroom.Bli.BliFinite

open LogicalInduction LO.Propositional Finset BoolPCWorld

/-! ## The generated algebra -/

/-- The propositional algebra generated by a finite set of sentences: closure under `⊥`, `⋏`,
`⋎`, `🡒` (hence `∼φ = φ 🡒 ⊥` and `⊤ = ⊥ 🡒 ⊥`).
Source: bli-paper-030 (the axioms range over "propositional" combinations); mandate T3
Kind: D
Fidelity: exact -/
inductive GenBy (A : Finset Sentence) : Sentence → Prop
  | base {φ : Sentence} : φ ∈ A → GenBy A φ
  | falsum : GenBy A ⊥
  | and {φ ψ : Sentence} : GenBy A φ → GenBy A ψ → GenBy A (φ ⋏ ψ)
  | or {φ ψ : Sentence} : GenBy A φ → GenBy A ψ → GenBy A (φ ⋎ ψ)
  | imp {φ ψ : Sentence} : GenBy A φ → GenBy A ψ → GenBy A (φ 🡒 ψ)

namespace GenBy

variable {A : Finset Sentence}

/-- `⊤ = ⊥ 🡒 ⊥` is generated.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma verum : GenBy A ⊤ := GenBy.imp GenBy.falsum GenBy.falsum

/-- Negations of generated sentences are generated.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma neg {φ : Sentence} (h : GenBy A φ) : GenBy A (∼φ) := GenBy.imp h GenBy.falsum

/-- Right-associated conjunctions of generated sentences are generated.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma sentenceConjunction {l : List Sentence} (h : ∀ φ ∈ l, GenBy A φ) :
    GenBy A (LogicalInduction.sentenceConjunction l) := by
  induction l with
  | nil => exact verum
  | cons φ l ih =>
      exact GenBy.and (h φ (List.mem_cons_self ..)) (ih fun ψ hψ => h ψ (List.mem_cons_of_mem _ hψ))

/-- Right-associated disjunctions of generated sentences are generated.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma sentenceDisjunction {l : List Sentence} (h : ∀ φ ∈ l, GenBy A φ) :
    GenBy A (LogicalInduction.sentenceDisjunction l) := by
  induction l with
  | nil => exact falsum
  | cons φ l ih =>
      exact GenBy.or (h φ (List.mem_cons_self ..)) (ih fun ψ hψ => h ψ (List.mem_cons_of_mem _ hψ))

end GenBy

/-- **Substitution on the generated algebra**: two worlds agreeing on `A` agree on `GenBy A`.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma holds_congr_of_genBy {A : Finset Sentence} {v v' : PCWorld}
    (h : ∀ φ ∈ A, (v.Holds φ ↔ v'.Holds φ)) : ∀ {φ : Sentence}, GenBy A φ → (v.Holds φ ↔ v'.Holds φ)
  | _, GenBy.base hφ => h _ hφ
  | _, GenBy.falsum => Iff.rfl
  | _, GenBy.and hφ hψ => by
      have := holds_congr_of_genBy h hφ
      have := holds_congr_of_genBy h hψ
      show (v.Holds _ ∧ v.Holds _) ↔ (v'.Holds _ ∧ v'.Holds _)
      rw [holds_congr_of_genBy h hφ, holds_congr_of_genBy h hψ]
  | _, GenBy.or hφ hψ => by
      show (v.Holds _ ∨ v.Holds _) ↔ (v'.Holds _ ∨ v'.Holds _)
      rw [holds_congr_of_genBy h hφ, holds_congr_of_genBy h hψ]
  | _, GenBy.imp hφ hψ => by
      show (v.Holds _ → v.Holds _) ↔ (v'.Holds _ → v'.Holds _)
      rw [holds_congr_of_genBy h hφ, holds_congr_of_genBy h hψ]

/-! ## `D`-consequence -/

/-- `φ` holds in every world consistent with `D` (a `D`-tautology; with `D = ∅`, a propositional
tautology).
Source: bli-paper-030 ("propositional tautology")
Kind: D
Fidelity: exact (relativized to `D`) -/
def DTaut (D : Finset Sentence) (φ : Sentence) : Prop :=
  ∀ v : PCWorld, v.ConsistentWith D → v.Holds φ

/-- `φ` fails in every world consistent with `D` (a `D`-contradiction).
Source: bli-paper-030 ("propositional contradiction")
Kind: D
Fidelity: exact (relativized to `D`) -/
def DContra (D : Finset Sentence) (φ : Sentence) : Prop :=
  ∀ v : PCWorld, v.ConsistentWith D → ¬ v.Holds φ

/-- `φ` and `ψ` agree in every world consistent with `D`.
Source: none: infrastructure
Kind: D
Fidelity: n/a -/
def DEquiv (D : Finset Sentence) (φ ψ : Sentence) : Prop :=
  ∀ v : PCWorld, v.ConsistentWith D → (v.Holds φ ↔ v.Holds ψ)

/-! ## The two axioms (plus non-negativity) -/

/-- **Appendix B's two coherence axioms, plus non-negativity**, over the algebra generated by
`A`, relative to a finite stage `D` (with `D = ∅`: the paper's pair verbatim, plus the clause
the paper omits — bli-paper-030's flag). (i) `0 ≤ V φ`; (ii) `D`-tautologies have price 1;
(iii) `D`-disjoint disjunctions add.
Source: bli-paper-030 (`main.tex:412–421`); bli-slides-003; bli-soto-a-001
Kind: D
Fidelity: variant: non-negativity added, `D`-relativized, quantified over `GenBy A` (all
disclosed) -/
def TwoAxiomCoherent (V : Sentence → ℚ) (A D : Finset Sentence) : Prop :=
  (∀ φ, GenBy A φ → 0 ≤ V φ) ∧
  (∀ φ, GenBy A φ → DTaut D φ → V φ = 1) ∧
  (∀ φ ψ, GenBy A φ → GenBy A ψ → DContra D (φ ⋏ ψ) → V (φ ⋎ ψ) = V φ + V ψ)

/-- The paper's two axioms **without** non-negativity (the refuted object of
`twoAxiom_signed_counterexample`).
Source: bli-paper-030 (verbatim pair, `D`-relativized)
Kind: D
Fidelity: exact (the paper's pair) -/
def TwoAxiomNoNonneg (V : Sentence → ℚ) (A D : Finset Sentence) : Prop :=
  (∀ φ, GenBy A φ → DTaut D φ → V φ = 1) ∧
  (∀ φ ψ, GenBy A φ → GenBy A ψ → DContra D (φ ⋏ ψ) → V (φ ⋎ ψ) = V φ + V ψ)

/-- The three clauses quantified over the **given sentences only** (the refuted object of
`twoAxiom_on_given_sentences_only_not_coherent`).
Source: bli-soto-a-001 (the reading "on the sentences in play")
Kind: D
Fidelity: exact (the vacuous reading) -/
def TwoAxiomOnGiven (V : Sentence → ℚ) (A D : Finset Sentence) : Prop :=
  (∀ φ ∈ A, 0 ≤ V φ) ∧
  (∀ φ ∈ A, DTaut D φ → V φ = 1) ∧
  (∀ φ ∈ A, ∀ ψ ∈ A, DContra D (φ ⋏ ψ) → V (φ ⋎ ψ) = V φ + V ψ)

/-! ## Consequences of the axioms alone -/

section Consequences

variable {V : Sentence → ℚ} {A D : Finset Sentence} (hV : TwoAxiomCoherent V A D)
include hV

/-- `V φ + V (∼φ) = 1` (bli-paper-030's second consequence).
Source: bli-paper-030
Kind: L
Fidelity: exact -/
lemma TwoAxiomCoherent.neg_add {φ : Sentence} (hφ : GenBy A φ) : V φ + V (∼φ) = 1 := by
  have hcontra : DContra D (φ ⋏ ∼φ) := by
    intro v _ h
    rw [PCWorld.holds_and, PCWorld.holds_neg] at h
    exact h.2 h.1
  have htaut : DTaut D (φ ⋎ ∼φ) := by
    intro v _
    rw [PCWorld.holds_or, PCWorld.holds_neg]
    exact em _
  rw [← hV.2.2 φ (∼φ) hφ hφ.neg hcontra]
  exact hV.2.1 _ (GenBy.or hφ hφ.neg) htaut

/-- `V ⊤ = 1`.
Source: bli-paper-030
Kind: L
Fidelity: exact -/
lemma TwoAxiomCoherent.verum : V ⊤ = 1 :=
  hV.2.1 _ GenBy.verum fun v _ => PCWorld.holds_top v

/-- `V ⊥ = 0`.
Source: bli-paper-030 (first consequence, at `⊥`)
Kind: L
Fidelity: exact -/
lemma TwoAxiomCoherent.falsum : V ⊥ = 0 := by
  have h := hV.neg_add GenBy.falsum
  have : V (∼(⊥ : Sentence)) = V ⊤ := rfl
  rw [this, hV.verum] at h
  linarith

/-- `V` respects `D`-equivalence on the generated algebra.
Source: none: infrastructure (needed for the de Finetti direction)
Kind: L
Fidelity: n/a -/
lemma TwoAxiomCoherent.eq_of_dequiv {φ ψ : Sentence} (hφ : GenBy A φ) (hψ : GenBy A ψ)
    (h : DEquiv D φ ψ) : V φ = V ψ := by
  have hcontra : DContra D (φ ⋏ ∼ψ) := by
    intro v hv hh
    rw [PCWorld.holds_and, PCWorld.holds_neg] at hh
    exact hh.2 ((h v hv).mp hh.1)
  have htaut : DTaut D (φ ⋎ ∼ψ) := by
    intro v hv
    rw [PCWorld.holds_or, PCWorld.holds_neg]
    by_cases hp : v.Holds ψ
    · exact Or.inl ((h v hv).mpr hp)
    · exact Or.inr hp
  have h1 := hV.2.2 φ (∼ψ) hφ hψ.neg hcontra
  have h2 := hV.2.1 _ (GenBy.or hφ hψ.neg) htaut
  have h3 := hV.neg_add hψ
  linarith

/-- `D`-contradictions have price 0 (bli-paper-030's first consequence, `D`-relativized).
Source: bli-paper-030
Kind: L
Fidelity: exact -/
lemma TwoAxiomCoherent.contradiction_zero {φ : Sentence} (hφ : GenBy A φ) (h : DContra D φ) :
    V φ = 0 := by
  rw [hV.eq_of_dequiv hφ GenBy.falsum (fun v hv => ⟨fun hh => (h v hv hh).elim, fun hh => hh.elim⟩)]
  exact hV.falsum

/-- Prices are at most 1.
Source: bli-paper-030 flag (the `[0,1]` range follows once non-negativity is added)
Kind: L
Fidelity: exact -/
lemma TwoAxiomCoherent.le_one {φ : Sentence} (hφ : GenBy A φ) : V φ ≤ 1 := by
  have := hV.neg_add hφ
  have := hV.1 _ hφ.neg
  linarith

/-- Monotonicity under `D`-consequence.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma TwoAxiomCoherent.mono {φ ψ : Sentence} (hφ : GenBy A φ) (hψ : GenBy A ψ)
    (h : ∀ v : PCWorld, v.ConsistentWith D → v.Holds φ → v.Holds ψ) : V φ ≤ V ψ := by
  have hχ : GenBy A (ψ ⋏ ∼φ) := GenBy.and hψ hφ.neg
  have hcontra : DContra D (φ ⋏ (ψ ⋏ ∼φ)) := by
    intro v _ hh
    rw [PCWorld.holds_and, PCWorld.holds_and, PCWorld.holds_neg] at hh
    exact hh.2.2 hh.1
  have hequiv : DEquiv D (φ ⋎ (ψ ⋏ ∼φ)) ψ := by
    intro v hv
    rw [PCWorld.holds_or, PCWorld.holds_and, PCWorld.holds_neg]
    constructor
    · rintro (hh | hh)
      · exact h v hv hh
      · exact hh.1
    · intro hh
      by_cases hp : v.Holds φ
      · exact Or.inl hp
      · exact Or.inr ⟨hh, hp⟩
  have h1 := hV.2.2 φ (ψ ⋏ ∼φ) hφ hχ hcontra
  have h2 := hV.eq_of_dequiv (GenBy.or hφ hχ) hψ hequiv
  have h3 := hV.1 _ hχ
  linarith

end Consequences

/-! ## Worlds and payouts -/

/-- The `PCWorld` read off a finite world (atoms `≥ B` read `false`).
Source: FAF `BooleanWorlds` (`toBoolPCWorld`, `toPCWorld`)
Kind: D
Fidelity: exact -/
abbrev worldOf {B : ℕ} (u : FiniteWorld B) : PCWorld := u.toBoolPCWorld.toPCWorld

open Classical in
/-- The rational payout is the indicator of truth in `worldOf u`.
Source: FAF `eval_eq_true_iff_holds`
Kind: L
Fidelity: n/a -/
lemma payoutRat_eq_ite {B : ℕ} (u : FiniteWorld B) (φ : Sentence) :
    u.payoutRat φ = if (worldOf u).Holds φ then 1 else 0 := by
  unfold FiniteWorld.payoutRat
  by_cases h : (worldOf u).Holds φ
  · rw [if_pos h, if_pos ((eval_eq_true_iff_holds _ _).mpr h)]
  · rw [if_neg h, if_neg (fun he => h ((eval_eq_true_iff_holds _ _).mp he))]

/-- Payouts are nonnegative.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma payoutRat_nonneg {B : ℕ} (u : FiniteWorld B) (φ : Sentence) : 0 ≤ u.payoutRat φ := by
  rw [payoutRat_eq_ite]; split_ifs <;> norm_num

/-- Payouts are at most one.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma payoutRat_le_one {B : ℕ} (u : FiniteWorld B) (φ : Sentence) : u.payoutRat φ ≤ 1 := by
  rw [payoutRat_eq_ite]; split_ifs <;> norm_num

/-- Payout `1` where the world holds the sentence.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma payoutRat_of_holds {B : ℕ} {u : FiniteWorld B} {φ : Sentence} (h : (worldOf u).Holds φ) :
    u.payoutRat φ = 1 := by
  rw [payoutRat_eq_ite, if_pos h]

/-- Payout `0` where the world does not hold the sentence.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma payoutRat_of_not_holds {B : ℕ} {u : FiniteWorld B} {φ : Sentence}
    (h : ¬ (worldOf u).Holds φ) : u.payoutRat φ = 0 := by
  rw [payoutRat_eq_ite, if_neg h]

/-- Payouts of a disjoint disjunction add.
Source: FAF `PCWorld.holds_or`/`holds_and`
Kind: L
Fidelity: n/a -/
lemma payoutRat_or_of_disjoint {B : ℕ} {u : FiniteWorld B} {φ ψ : Sentence}
    (h : ¬ (worldOf u).Holds (φ ⋏ ψ)) :
    u.payoutRat (φ ⋎ ψ) = u.payoutRat φ + u.payoutRat ψ := by
  rw [PCWorld.holds_and] at h
  rw [payoutRat_eq_ite, payoutRat_eq_ite, payoutRat_eq_ite, PCWorld.holds_or]
  by_cases hφ : (worldOf u).Holds φ <;> by_cases hψ : (worldOf u).Holds ψ <;> simp_all

/-- Truth in the restricted world agrees with truth in the original world on sentences within
the atom bound (FAF's `eval_toBoolPCWorld_restrict`).
Source: FAF `eval_toBoolPCWorld_restrict`, `ofPCWorld_toPCWorld`
Kind: L
Fidelity: n/a -/
lemma holds_worldOf_restrict (v : PCWorld) {B : ℕ} {φ : Sentence} (hφ : atomBound φ ≤ B) :
    (worldOf (FiniteWorld.restrict (ofPCWorld v) B)).Holds φ ↔ v.Holds φ := by
  have h1 := eval_toBoolPCWorld_restrict (ofPCWorld v) B φ hφ
  have h2 := eval_eq_true_iff_holds (FiniteWorld.restrict (ofPCWorld v) B).toBoolPCWorld φ
  have h3 := eval_eq_true_iff_holds (ofPCWorld v) φ
  rw [ofPCWorld_toPCWorld] at h3
  rw [← h2, h1, h3]

/-! ## World marginals -/

/-- `V` is, on `GenBy A`, the marginal of a rational probability on `FiniteWorld B` supported on
`D`-consistent worlds.
Source: bli-soto-a-001 (Soto PDF 05 Def 1); bli-slides-003 (Paul's `2^N`-worlds table)
Kind: D
Fidelity: exact -/
def IsWorldMarginal (V : Sentence → ℚ) (A D : Finset Sentence) (B : ℕ) : Prop :=
  ∃ w : FiniteWorld B → ℚ, (∀ u, 0 ≤ w u) ∧ ∑ u, w u = 1 ∧
    (∀ u, w u ≠ 0 → (worldOf u).ConsistentWith D) ∧
    ∀ φ, GenBy A φ → V φ = ∑ u, w u * u.payoutRat φ

/-- **The easy direction (⟸): a world marginal satisfies the two axioms and non-negativity.**
This is Paul's `2^N`-worlds betting table (bli-slides-003), finite additivity of a mixture of
`{0,1}` payouts. Needs no atom bound.
Source: bli-slides-003; bli-soto-a-001
Kind: P
Fidelity: exact
Hyps: (a) none -/
theorem twoAxiom_of_worldMarginal {V : Sentence → ℚ} {A D : Finset Sentence} {B : ℕ}
    (h : IsWorldMarginal V A D B) : TwoAxiomCoherent V A D := by
  obtain ⟨w, hw0, hw1, hwD, hV⟩ := h
  refine ⟨fun φ hφ => ?_, fun φ hφ ht => ?_, fun φ ψ hφ hψ hc => ?_⟩
  · rw [hV φ hφ]
    exact Finset.sum_nonneg fun u _ => mul_nonneg (hw0 u) (payoutRat_nonneg u φ)
  · rw [hV φ hφ, ← hw1]
    apply Finset.sum_congr rfl
    intro u _
    by_cases hu : w u = 0
    · rw [hu, zero_mul]
    · rw [payoutRat_of_holds (ht _ (hwD u hu)), mul_one]
  · rw [hV _ (GenBy.or hφ hψ), hV φ hφ, hV ψ hψ, ← Finset.sum_add_distrib]
    apply Finset.sum_congr rfl
    intro u _
    by_cases hu : w u = 0
    · rw [hu, zero_mul, zero_mul, zero_mul, add_zero]
    · rw [payoutRat_or_of_disjoint (hc _ (hwD u hu)), mul_add]

/-! ## Coherence of tables -/

/-- **Propositional coherence of a table** relative to a finite stage `D`, with atom bound `B`:
the table is the marginal of a rational probability on `FiniteWorld B` supported on
`D`-consistent worlds (finite de Finetti form, [[bli-program]] F4). The world type is FAF's
`FiniteWorld B` read as a `PCWorld` through `toBoolPCWorld.toPCWorld` (atoms `≥ B` read
`false`); use it with `hB : ∀ φ ∈ 𝒮.S m ∪ D, atomBound φ ≤ B`, else a `D` mentioning atoms
beyond `B` is silently decided.
Source: bli-paper-030; bli-soto-a-001; [[bli-program]] §2.2 (`CoherentOn`)
Kind: D
Fidelity: exact (world-marginal reading; the two-axiom reading is `coherentOn_iff_twoAxiom`) -/
def CoherentOn {𝒮 : SmallIndex} {m : ℕ} (t : Table 𝒮 m) (D : Finset Sentence) (B : ℕ) : Prop :=
  ∃ w : FiniteWorld B → ℚ, (∀ u, 0 ≤ w u) ∧ ∑ u, w u = 1 ∧
    (∀ u, w u ≠ 0 → (worldOf u).ConsistentWith D) ∧
    ∀ φ : ↥(𝒮.S m), t φ = ∑ u, w u * u.payoutRat φ.1

/-- A coherent table lies in the unit cube.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma CoherentOn.inUnit {𝒮 : SmallIndex} {m : ℕ} {t : Table 𝒮 m} {D : Finset Sentence} {B : ℕ}
    (h : CoherentOn t D B) : t.InUnit := by
  obtain ⟨w, hw0, hw1, -, ht⟩ := h
  intro φ
  rw [ht φ]
  constructor
  · exact Finset.sum_nonneg fun u _ => mul_nonneg (hw0 u) (payoutRat_nonneg u _)
  · calc ∑ u, w u * u.payoutRat φ.1 ≤ ∑ u, w u :=
          Finset.sum_le_sum fun u _ => mul_le_of_le_one_right (hw0 u) (payoutRat_le_one u _)
      _ = 1 := hw1

end Cleanroom.Bli.BliFinite
