import Cleanroom.Bli.BliFinite.Coherence

/-!
# `bli-finite` · DeFinetti: the two axioms ⟺ a world marginal (T3, part 2, load-bearing)

**The claim.** A valuation satisfying Appendix B's two coherence axioms (plus non-negativity)
on the algebra generated by a finite set `A`, relative to a stage `D`, is the marginal of a
rational probability on FAF's finite worlds `FiniteWorld B` supported on `D`-consistent
worlds — and conversely (`Coherence.lean`). The paper asserts the two readings coincide
("amount to the Kolmogorov axioms with only finite additivity", bli-soto-a-001); this proves it.

**Route (⟹).** The `2^{|A|}` *types* `s : ↥A → Bool` index the complete conjunctions `chi s`
(each `φ ∈ A` or its negation), which are in `GenBy A`. From the axioms alone: `V` respects
`D`-equivalence, `V ⊥ = 0`, and a disjunction over a duplicate-free list of types prices as the
sum. Every `φ ∈ GenBy A` is equivalent in all worlds to the disjunction of the types satisfying
it, so `V φ = ∑_{s ⊨ φ} V (chi s)`. Then spread each `V (chi s)` **uniformly** over the
`D`-consistent finite worlds of type `s` (when there are none, `chi s` is a `D`-contradiction
and `V (chi s) = 0` — this is where the atom bound `hB` enters: a `D`-consistent `PCWorld` of
type `s` restricts to a `D`-consistent finite world of type `s`).
-/

namespace Cleanroom.Bli.BliFinite

open LogicalInduction LO.Propositional Finset BoolPCWorld Classical

section Types

variable (A : Finset Sentence)

/-- The **`A`-type** of a world: which sentences of `A` it holds.
Source: none: infrastructure (mandate T3 route: "the `2^{|A|}` complete conjunctions")
Kind: D
Fidelity: n/a -/
noncomputable def typeOf (v : PCWorld) : ↥A → Bool := fun φ => decide (v.Holds φ.1)

/-- Two worlds have the same type iff they agree on `A`.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma typeOf_eq_iff {v v' : PCWorld} :
    typeOf A v = typeOf A v' ↔ ∀ φ ∈ A, (v.Holds φ ↔ v'.Holds φ) := by
  constructor
  · intro h φ hφ
    have := congrFun h ⟨φ, hφ⟩
    simpa [typeOf] using this
  · intro h
    funext φ
    simp [typeOf, h φ.1 φ.2]

/-- The **complete conjunction** of a type: every `φ ∈ A`, or its negation, as `s` says.
Source: mandate T3 route (`χ_σ`)
Kind: D
Fidelity: n/a -/
noncomputable def chi (s : ↥A → Bool) : Sentence :=
  LogicalInduction.sentenceConjunction (A.attach.toList.map fun φ => if s φ then φ.1 else ∼φ.1)

/-- Complete conjunctions are generated by `A`.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma genBy_chi (s : ↥A → Bool) : GenBy A (chi A s) := by
  apply GenBy.sentenceConjunction
  intro ψ hψ
  rw [List.mem_map] at hψ
  obtain ⟨φ, -, rfl⟩ := hψ
  split_ifs
  · exact GenBy.base φ.2
  · exact (GenBy.base φ.2).neg

/-- A world holds `chi s` iff its type is `s`.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma holds_chi_iff (v : PCWorld) (s : ↥A → Bool) : v.Holds (chi A s) ↔ typeOf A v = s := by
  unfold chi
  rw [holds_sentenceConjunction, List.forall_mem_map]
  constructor
  · intro h
    funext φ
    have hφ := h φ (Finset.mem_toList.mpr (Finset.mem_attach _ _))
    simp only [typeOf]
    cases hs : s φ
    · simp only [hs, Bool.false_eq_true, if_false, PCWorld.holds_neg] at hφ
      exact decide_eq_false hφ
    · simp only [hs, if_true] at hφ
      exact decide_eq_true hφ
  · intro h φ _
    have hφ := congrFun h φ
    simp only [typeOf] at hφ
    cases hs : s φ
    · rw [hs] at hφ
      simp only [Bool.false_eq_true, if_false, PCWorld.holds_neg]
      exact of_decide_eq_false hφ
    · rw [hs] at hφ
      simp only [if_true]
      exact of_decide_eq_true hφ

/-- `Sat s φ`: some world of type `s` holds `φ`.
Source: none: infrastructure
Kind: D
Fidelity: n/a -/
def Sat (s : ↥A → Bool) (φ : Sentence) : Prop := ∃ v : PCWorld, typeOf A v = s ∧ v.Holds φ

/-- On the generated algebra, satisfaction is a property of the type.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma sat_typeOf_iff {v : PCWorld} {φ : Sentence} (hφ : GenBy A φ) :
    Sat A (typeOf A v) φ ↔ v.Holds φ := by
  constructor
  · rintro ⟨v', hv', h⟩
    exact (holds_congr_of_genBy ((typeOf_eq_iff A).mp hv') hφ).mp h
  · intro h
    exact ⟨v, rfl, h⟩

/-- The disjunction of the complete conjunctions of a list of types.
Source: none: infrastructure
Kind: D
Fidelity: n/a -/
noncomputable def typesDisj (L : List (↥A → Bool)) : Sentence :=
  LogicalInduction.sentenceDisjunction (L.map (chi A))

/-- A world holds the disjunction over `L` iff its type is in `L`.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma holds_typesDisj_iff (v : PCWorld) (L : List (↥A → Bool)) :
    v.Holds (typesDisj A L) ↔ typeOf A v ∈ L := by
  unfold typesDisj
  rw [holds_sentenceDisjunction]
  constructor
  · rintro ⟨ψ, hψ, h⟩
    rw [List.mem_map] at hψ
    obtain ⟨s, hs, rfl⟩ := hψ
    rw [holds_chi_iff] at h
    rw [h]; exact hs
  · intro h
    exact ⟨chi A (typeOf A v), List.mem_map.mpr ⟨_, h, rfl⟩, (holds_chi_iff A v _).mpr rfl⟩

/-- The disjunction over types is generated by `A`.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma genBy_typesDisj (L : List (↥A → Bool)) : GenBy A (typesDisj A L) := by
  apply GenBy.sentenceDisjunction
  intro ψ hψ
  rw [List.mem_map] at hψ
  obtain ⟨s, -, rfl⟩ := hψ
  exact genBy_chi A s

end Types

section Decomposition

variable {A : Finset Sentence} {V : Sentence → ℚ} {D : Finset Sentence}
  (hV : TwoAxiomCoherent V A D)
include hV

/-- A disjunction over a duplicate-free list of types prices as the sum of the types' prices
(the types are pairwise disjoint).
Source: none: infrastructure (finite additivity iterated)
Kind: L
Fidelity: n/a -/
lemma TwoAxiomCoherent.typesDisj_sum :
    ∀ (L : List (↥A → Bool)), L.Nodup → V (typesDisj A L) = (L.map fun s => V (chi A s)).sum
  | [], _ => by
      show V ⊥ = 0
      exact hV.falsum
  | s :: L, hL => by
      have hnd := List.nodup_cons.mp hL
      have hcontra : DContra D (chi A s ⋏ typesDisj A L) := by
        intro v _ h
        rw [PCWorld.holds_and, holds_chi_iff, holds_typesDisj_iff] at h
        exact hnd.1 (h.1 ▸ h.2)
      show V (chi A s ⋎ typesDisj A L) = _
      rw [hV.2.2 _ _ (genBy_chi A s) (genBy_typesDisj A L) hcontra, List.map_cons, List.sum_cons,
        TwoAxiomCoherent.typesDisj_sum L hnd.2]

/-- **Decomposition into types**: on the generated algebra, `V φ` is the sum of `V (chi s)` over
the types satisfying `φ`.
Source: mandate T3 route (`V φ = ∑_{σ ⊨ φ} V χ_σ`)
Kind: P
Fidelity: exact
Hyps: (a) none beyond the axioms -/
lemma TwoAxiomCoherent.eq_sum_types {φ : Sentence} (hφ : GenBy A φ) :
    V φ = ∑ s ∈ univ.filter (fun s => Sat A s φ), V (chi A s) := by
  set T := univ.filter (fun s : ↥A → Bool => Sat A s φ) with hT
  have hequiv : DEquiv D φ (typesDisj A T.toList) := by
    intro v _
    rw [holds_typesDisj_iff, Finset.mem_toList, hT, Finset.mem_filter]
    constructor
    · intro h; exact ⟨Finset.mem_univ _, (sat_typeOf_iff A hφ).mpr h⟩
    · intro h; exact (sat_typeOf_iff A hφ).mp h.2
  rw [hV.eq_of_dequiv hφ (genBy_typesDisj A _) hequiv, hV.typesDisj_sum _ (Finset.nodup_toList _),
    Finset.sum_map_toList]

end Decomposition

/-! ## The uniform spread over finite worlds -/

section Spread

variable (A D : Finset Sentence) (B : ℕ)

/-- The `D`-consistent finite worlds of type `s`.
Source: none: infrastructure
Kind: D
Fidelity: n/a -/
noncomputable def fiber (s : ↥A → Bool) : Finset (FiniteWorld B) :=
  univ.filter fun u => typeOf A (worldOf u) = s ∧ (worldOf u).ConsistentWith D

/-- The number of `D`-consistent finite worlds of type `s`, as a rational.
Source: none: infrastructure
Kind: D
Fidelity: n/a -/
noncomputable def typeCount (s : ↥A → Bool) : ℚ := ((fiber A D B s).card : ℚ)

/-- **The uniform spread**: the weight of a `D`-consistent finite world is `V (chi s) / N_s` for
its type `s` (`N_s` the number of such worlds of that type); inconsistent worlds get `0`.
Source: mandate T3 route ("spread each `V χ_σ` uniformly")
Kind: D
Fidelity: n/a -/
noncomputable def spreadWeight (V : Sentence → ℚ) (u : FiniteWorld B) : ℚ :=
  if (worldOf u).ConsistentWith D then
    V (chi A (typeOf A (worldOf u))) / typeCount A D B (typeOf A (worldOf u))
  else 0

variable {A D B} {V : Sentence → ℚ}

/-- The spread is nonnegative.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma spreadWeight_nonneg (hV : TwoAxiomCoherent V A D) (u : FiniteWorld B) :
    0 ≤ spreadWeight A D B V u := by
  unfold spreadWeight
  split_ifs
  · exact div_nonneg (hV.1 _ (genBy_chi A _)) (by unfold typeCount; positivity)
  · exact le_rfl

/-- The spread charges only `D`-consistent worlds.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma spreadWeight_consistent {u : FiniteWorld B} (h : spreadWeight A D B V u ≠ 0) :
    (worldOf u).ConsistentWith D := by
  unfold spreadWeight at h
  by_contra hc
  exact h (if_neg hc)

/-- **Where the atom bound enters.** If no `D`-consistent finite world has type `s`, then `chi s`
is a `D`-contradiction (a `D`-consistent `PCWorld` of type `s` would restrict to one), so
`V (chi s) = 0`.
Source: none: infrastructure (FAF `eval_toBoolPCWorld_restrict`)
Kind: L
Fidelity: n/a -/
lemma chi_eq_zero_of_typeCount_eq_zero (hV : TwoAxiomCoherent V A D)
    (hB : ∀ φ ∈ A ∪ D, atomBound φ ≤ B) (s : ↥A → Bool) (h : typeCount A D B s = 0) :
    V (chi A s) = 0 := by
  apply hV.contradiction_zero (genBy_chi A s)
  intro v hv hvs
  rw [holds_chi_iff] at hvs
  set u : FiniteWorld B := FiniteWorld.restrict (ofPCWorld v) B with hu
  have hmem : u ∈ fiber A D B s := by
    rw [fiber, Finset.mem_filter]
    refine ⟨Finset.mem_univ _, ?_, ?_⟩
    · rw [← hvs, typeOf_eq_iff]
      intro φ hφ
      exact holds_worldOf_restrict v (hB φ (Finset.mem_union_left _ hφ))
    · intro ψ hψ
      exact (holds_worldOf_restrict v (hB ψ (Finset.mem_union_right _ hψ))).mpr (hv ψ hψ)
  have hpos : 0 < (fiber A D B s).card := Finset.card_pos.mpr ⟨u, hmem⟩
  unfold typeCount at h
  have : (fiber A D B s).card = 0 := by exact_mod_cast h
  omega

/-- **The spread reproduces `V` on the generated algebra.**
Source: mandate T3 route
Kind: P
Fidelity: exact
Hyps: (a) the axioms; (a) `hB` -/
lemma sum_spreadWeight_mul_payoutRat (hV : TwoAxiomCoherent V A D)
    (hB : ∀ φ ∈ A ∪ D, atomBound φ ≤ B) {φ : Sentence} (hφ : GenBy A φ) :
    ∑ u, spreadWeight A D B V u * u.payoutRat φ = V φ := by
  rw [← Finset.sum_fiberwise univ (fun u : FiniteWorld B => typeOf A (worldOf u))
    (fun u => spreadWeight A D B V u * u.payoutRat φ), hV.eq_sum_types hφ, Finset.sum_filter]
  apply Finset.sum_congr rfl
  intro s _
  have hterm : ∀ u ∈ univ.filter (fun u : FiniteWorld B => typeOf A (worldOf u) = s),
      spreadWeight A D B V u * u.payoutRat φ =
        (if (worldOf u).ConsistentWith D then (1 : ℚ) else 0) *
          ((if Sat A s φ then (1 : ℚ) else 0) * (V (chi A s) / typeCount A D B s)) := by
    intro u hu
    rw [Finset.mem_filter] at hu
    have hu' := hu.2
    have hsat : (worldOf u).Holds φ ↔ Sat A s φ := by
      rw [← hu']; exact (sat_typeOf_iff A hφ).symm
    unfold spreadWeight
    rw [hu', payoutRat_eq_ite]
    by_cases hc : (worldOf u).ConsistentWith D <;> by_cases hs : Sat A s φ <;>
      simp [hc, hs, hsat]
  rw [Finset.sum_congr rfl hterm, ← Finset.sum_mul, Finset.sum_boole]
  have hN : ((univ.filter (fun u : FiniteWorld B => typeOf A (worldOf u) = s)).filter
      (fun u => (worldOf u).ConsistentWith D)).card = typeCount A D B s := by
    unfold typeCount fiber
    rw [Finset.filter_filter]
  rw [hN]
  by_cases hs : Sat A s φ
  · simp only [hs, if_true, one_mul]
    by_cases hz : typeCount A D B s = 0
    · rw [hz, div_zero, mul_zero, chi_eq_zero_of_typeCount_eq_zero hV hB s hz]
    · rw [mul_div_cancel₀ _ hz]
  · simp [hs]

/-- The spread is a probability.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma sum_spreadWeight (hV : TwoAxiomCoherent V A D) (hB : ∀ φ ∈ A ∪ D, atomBound φ ≤ B) :
    ∑ u, spreadWeight A D B V u = 1 := by
  have h := sum_spreadWeight_mul_payoutRat hV hB (B := B) GenBy.verum
  simp only [payoutRat_of_holds (PCWorld.holds_top _), mul_one] at h
  rw [h, hV.verum]

end Spread

/-! ## The headline -/

/-- **The hard direction (⟹): the two axioms (with non-negativity) give a world marginal.**
Source: bli-paper-030; bli-soto-a-001 (the paper asserts the readings coincide); mandate T3
Kind: P
Fidelity: exact
Hyps: (a) `hB` is the atom bound of the world type (mandate design decision 8) -/
theorem worldMarginal_of_twoAxiom {V : Sentence → ℚ} {A D : Finset Sentence} {B : ℕ}
    (hB : ∀ φ ∈ A ∪ D, atomBound φ ≤ B) (hV : TwoAxiomCoherent V A D) :
    IsWorldMarginal V A D B :=
  ⟨spreadWeight A D B V, spreadWeight_nonneg hV, sum_spreadWeight hV hB,
    fun _ h => spreadWeight_consistent h,
    fun _ hφ => (sum_spreadWeight_mul_payoutRat hV hB hφ).symm⟩

/-- **Finite de Finetti (T3, load-bearing).** A valuation satisfies Appendix B's two coherence
axioms plus non-negativity on `GenBy A`, relative to `D`, **iff** it is on `GenBy A` the
marginal of a rational probability on FAF's `FiniteWorld B` supported on `D`-consistent worlds
— for any atom bound `B` covering `A ∪ D`. With `D = ∅` and `B` large this is exactly the
paper's "propositionally coherent = Kolmogorov with finite additivity" (bli-paper-030,
bli-soto-a-001), proved rather than asserted.
Source: bli-paper-030 (`main.tex:412–421`); bli-slides-003; bli-soto-a-001
Kind: P
Fidelity: exact (non-negativity added to the paper's pair; `D`-relativized; over `GenBy A`)
Hyps: (a) `hB : ∀ φ ∈ A ∪ D, atomBound φ ≤ B` (the world type's atom bound; only the ⟹
direction uses it) -/
theorem twoAxiom_iff_worldMarginal {V : Sentence → ℚ} {A D : Finset Sentence} {B : ℕ}
    (hB : ∀ φ ∈ A ∪ D, atomBound φ ≤ B) :
    TwoAxiomCoherent V A D ↔ IsWorldMarginal V A D B :=
  ⟨worldMarginal_of_twoAxiom hB, twoAxiom_of_worldMarginal⟩

/-- **Coherence of a table in the two-axiom reading.** A day-`m` table is `CoherentOn t D B` iff
it extends to a valuation satisfying the two axioms (plus non-negativity) on the algebra
generated by the day's small sentences.
Source: bli-paper-030; [[bli-program]] §2.2 (`CoherentOn`, F4)
Kind: C
Fidelity: exact
Hyps: (a) `hB : ∀ φ ∈ 𝒮.S m ∪ D, atomBound φ ≤ B` -/
theorem coherentOn_iff_twoAxiom {𝒮 : SmallIndex} {m : ℕ} (t : Table 𝒮 m) (D : Finset Sentence)
    (B : ℕ) (hB : ∀ φ ∈ 𝒮.S m ∪ D, atomBound φ ≤ B) :
    CoherentOn t D B ↔
      ∃ V : Sentence → ℚ, (∀ φ : ↥(𝒮.S m), V φ.1 = t φ) ∧ TwoAxiomCoherent V (𝒮.S m) D := by
  constructor
  · rintro ⟨w, hw0, hw1, hwD, ht⟩
    exact ⟨fun φ => ∑ u, w u * u.payoutRat φ, fun φ => (ht φ).symm,
      twoAxiom_of_worldMarginal ⟨w, hw0, hw1, hwD, fun _ _ => rfl⟩⟩
  · rintro ⟨V, hVt, hV⟩
    obtain ⟨w, hw0, hw1, hwD, hV'⟩ := worldMarginal_of_twoAxiom hB hV
    exact ⟨w, hw0, hw1, hwD, fun φ => by rw [← hVt φ, hV' φ.1 (GenBy.base φ.2)]⟩

end Cleanroom.Bli.BliFinite
