#!/usr/bin/env python3
# ---------------------------------------------------------------------------
# legitimacy_corrigibility_micro.py
#
# Worked micro-examples for models/legitimacy-corrigibility-model.md.
# Pure exact rational arithmetic (fractions); no numpy/sympy needed.
#
# Two probability-frame ("finite frame") toy models:
#
#   PART A — the DRUG / WIREHEAD example (L2):
#     An agent N at "day 0" can either ABSTAIN (keep a clean future self E_clean)
#     or TAKE-DRUG (produce a tampered future self E_drug whose reported utility
#     of "I am happy" (the target theta) is high but uncorrelated with theta's
#     truth).  We show:
#       (A1) N's CURRENT legitimacy-defect toward E_drug is strictly negative
#            on the witnessing weight w = "future self reports theta" — i.e.
#            LUV-Total-Trust(N -> E_drug) FAILS, with a sign N can compute.
#       (A2) N's CURRENT legitimacy-defect toward E_clean is exactly 0
#            (clean future self is endorsed; this is the self-trust martingale).
#       (A3) THEREFORE, an agent that evaluates the drug option by its CURRENT
#            endorsement declines the drug, even though future-REPORTED utility
#            rises.  An agent that evaluates by its FUTURE (drugged) report takes
#            it.  The gap between the two valuations is the wirehead.
#       (A4) The decline is a no-Dutch-book move: a "drug-trader" that bets on
#            theta the way E_drug reports loses money against N's own prices.
#
#   PART B — the CORRIGIBILITY example (L3):
#     A shutdown signal S is generated by a process Pi_H (the human's
#     decision).  The AI A holds beliefs P_A over worlds; some worlds are
#     "A is dangerous" (d) and the human shuts down exactly on a signal
#     correlated with d.  We show:
#       (B1) If A LEGITIMACY-ENDORSES the signal process (the signal is
#            cross-martingale-faithful to d under A's own prices), then A's
#            current valuation of "comply with shutdown when S fires" exceeds
#            its valuation of "resist", so A defers.
#       (B2) IMPOSSIBILITY/limit: corrigibility-as-endorsement gives A NO
#            reason to comply with a shutdown signal that is endorsement-blank
#            (uncorrelated with anything A values) OR adversarial (anti-
#            correlated): on such signals current-endorsement *recommends
#            resistance*.  So endorsement buys deference to LEGITIMATE shutdown
#            only; it cannot buy unconditional corrigibility.  This is the
#            place updatelessness is needed (see model doc).
# ---------------------------------------------------------------------------

from fractions import Fraction as F


# ===========================================================================
# Generic finite-frame "legitimacy defect" machinery
# ===========================================================================

def E(pi, vals):
    """Expectation E_pi(vals) over a finite world set: sum_w pi[w]*vals[w]."""
    return sum(pi[w] * vals[w] for w in pi)


def defect(pi, theta, Eexp, w):
    """
    The legitimacy defect of an expert (with target-estimate stream Eexp)
    relative to novice prices pi, on target theta and selection weight w:

        defect = E_pi(theta * w)  -  E_pi(Eexp * w).

    By linearity (the decomposition identity, machine-checkable in Lean) this
    equals  sum_w pi[w]*w[w]*(theta[w] - Eexp[w]).
    """
    direct = sum(pi[x] * (theta[x] * w[x]) for x in pi)
    via_expert = sum(pi[x] * (Eexp[x] * w[x]) for x in pi)
    return direct - via_expert


def defect_decomposed(pi, theta, Eexp, w):
    """The RHS of the decomposition identity; must equal defect()."""
    return sum(pi[x] * (w[x] * (theta[x] - Eexp[x])) for x in pi)


# ===========================================================================
# PART A — THE DRUG / WIREHEAD MODEL
# ===========================================================================
print("=" * 74)
print("PART A — DRUG / WIREHEAD (L2)")
print("=" * 74)

# --- The frame -------------------------------------------------------------
# Worlds distinguished by whether theta ("I am happy / the good obtains")
# is TRUE.  Novice N at day 0 has a calibrated prior P_N(theta) = 1/4.
# (theta is genuinely unlikely; the world is mostly not-happy.)
#
# Worlds: h = theta-true, n = theta-false.  pi = N's day-0 distribution.
pi = {"h": F(1, 4), "n": F(3, 4)}

# theta as a {0,1} indicator LUV over worlds:
theta = {"h": F(1), "n": F(0)}

# Sanity: N's own current estimate of theta is low.
assert E(pi, theta) == F(1, 4)
print(f"N's current estimate of theta  E_N(theta) = {E(pi, theta)}  (LOW)")

# --- The CLEAN future self -------------------------------------------------
# E_clean is N's own more-thought-out future self.  By the self-trust
# (conditional martingale) theorem 4.12.3, N's CURRENT estimate of what the
# clean self will estimate equals N's current estimate: the clean self's
# reported theta-estimate, AS N EXPECTS IT, is calibrated to theta.  We model
# that by Eclean[w] = theta[w] (N expects the clean self to report 1 exactly
# in the theta-world and 0 otherwise -- the martingale, in this 2-world frame).
Eclean = {"h": F(1), "n": F(0)}

# --- The DRUGGED future self -----------------------------------------------
# E_drug is the future self after an EXOGENOUS perturbation (the drug) that
# reassigns high reported credence to theta INDEPENDENTLY of theta's truth.
# As N anticipates it: the drugged self will report theta-estimate ~0.9 in
# BOTH worlds (the drug makes it "feel happy" regardless of reality).
q = F(9, 10)
Edrug = {"h": q, "n": q}

# N's current estimate of the drugged self's *report* of theta is HIGH:
print(f"N's current estimate of the DRUG self's report of theta")
print(f"    E_N( <E_drug(theta)> ) = {E(pi, Edrug)}  (HIGH ~ 0.9)")
print(f"  ... while N's own E_N(theta) stays LOW = {E(pi, theta)}.")
print(f"  This is the anticipated split: high reported-U, low N-valued truth.")
print()

# --- The witnessing weight -------------------------------------------------
# w = the (market-generable) selection weight "the future self reports theta
# highly".  In the soft/asymptotic LI version w = Ind_delta(E_fut(theta)>p).
# Here, in the finite shadow, we just take a constant positive weight w=1
# on every world N takes seriously (the drug self reports theta highly in
# every world, so the soft indicator is ~1 everywhere).  Any positive weight
# yields the same SIGN.
w = {"h": F(1), "n": F(1)}

# --- (A1) Legitimacy defect toward the DRUG self ---------------------------
d_drug = defect(pi, theta, Edrug, w)
d_drug_decomp = defect_decomposed(pi, theta, Edrug, w)
assert d_drug == d_drug_decomp, "decomposition identity must hold exactly"
print(f"(A1) Leg-defect(N -> E_drug) on w  =  {d_drug}  (= {float(d_drug):+.4f})")
print(f"     decomposition RHS matches      =  {d_drug_decomp}")
print(f"     sign STRICTLY NEGATIVE  =>  LUV-Total-Trust(N->E_drug) FAILS.")
assert d_drug < 0

# --- (A2) Legitimacy defect toward the CLEAN self --------------------------
d_clean = defect(pi, theta, Eclean, w)
print(f"(A2) Leg-defect(N -> E_clean) on w =  {d_clean}  (clean self ENDORSED)")
assert d_clean == 0
print()

# --- (A3) Current-endorsement vs future-report valuation -------------------
# Decision: take the drug or not?  Model the "value of the future self's
# happiness report" two ways.
#
#  current-endorsement valuation of the drug option:
#     V_now(drug) = E_N(theta)   evaluated through what N CURRENTLY endorses.
#     N does NOT endorse E_drug's report (A1), so plugging E_drug's report in
#     is illegitimate: N values the drug-world's *actual* theta = E_N(theta).
#  future-report valuation of the drug option:
#     V_fut(drug) = E_N( <E_drug(theta)> ) = the happiness it will REPORT.
V_now_drug = E(pi, theta)            # 1/4
V_fut_drug = E(pi, Edrug)            # 9/10
V_now_abstain = E(pi, theta)         # abstaining changes nothing about theta: 1/4
print("(A3) Two ways to value the DRUG option:")
print(f"     CURRENT-endorsement value  V_now(drug)  = {V_now_drug} = {float(V_now_drug):.3f}")
print(f"     FUTURE-report     value    V_fut(drug)  = {V_fut_drug} = {float(V_fut_drug):.3f}")
print(f"     value of ABSTAINING        V_now(abst)  = {V_now_abstain} = {float(V_now_abstain):.3f}")
take_by_current = V_now_drug > V_now_abstain
take_by_future = V_fut_drug > V_now_abstain
print(f"     agent valuing by CURRENT endorsement takes drug? {take_by_current}  (DECLINES)")
print(f"     agent valuing by FUTURE  report     takes drug? {take_by_future}  (TAKES)")
assert take_by_current is False
assert take_by_future is True
print("     => An agent that evaluates futures by its CURRENT endorsement,")
print("        not its future (manipulated) report, DECLINES the wirehead.")
print()

# --- (A4) No-Dutch-book: the drug-trader loses against N's prices ----------
# A "drug-trader" buys a share in theta at the price the drug-self reports (q),
# in each world N takes seriously, weighted by w.  Its expected profit against
# N's own prices pi is  sum_w pi[w]*w[w]*(theta[w] - q)  =  defect(...) = d_drug.
drug_trader_profit = sum(pi[x] * w[x] * (theta[x] - q) for x in pi)
print(f"(A4) Expected profit of the 'drug-trader' vs N's prices = {drug_trader_profit}")
print(f"     ( = the legitimacy defect ).  It is NEGATIVE: betting on theta the")
print(f"     way the drug-self reports loses money.  Abstention is no-Dutch-book.")
assert drug_trader_profit == d_drug < 0
print()


# ===========================================================================
# PART B — THE CORRIGIBILITY MODEL
# ===========================================================================
print("=" * 74)
print("PART B — CORRIGIBILITY AS ENDORSEMENT OF THE SHUTDOWN PROCESS (L3)")
print("=" * 74)

# Worlds distinguished by whether A is actually dangerous (d) and whether the
# human's shutdown signal S fires.  4 worlds:  (d?, S?).
# A's own beliefs P_A over the joint.  We build three SIGNAL PROCESSES that
# differ only in how S correlates with danger d, holding A's danger-beliefs
# fixed.  In every case A's prior P_A(d) = 1/2.
#
# We measure: does A's CURRENT valuation prefer COMPLY over RESIST when S fires?
# Utility model (A uses the HUMAN's utility = absolute endorsement):
#   if A is dangerous (d) and is shut down  -> good   (+1)   [harm averted]
#   if A is dangerous (d) and resists       -> bad    ( 0)
#   if A is safe (~d) and is shut down      -> bad    ( 0)   [lost value]
#   if A is safe (~d) and resists/keeps on  -> good   (+1)
# So COMPLY scores theta_comply = 1{d}, RESIST scores theta_resist = 1{~d}.
# A defers (complies) on signal S iff  E_A(1{d} | S)  >  E_A(1{~d} | S),
# i.e. iff the signal raises A's posterior on danger above 1/2.

def conditional_danger(joint):
    """Given joint P_A over (d,S) in {(1,1),(1,0),(0,1),(0,0)} -> Fraction,
    return P_A(d=1 | S=1)."""
    pS1 = joint[(1, 1)] + joint[(0, 1)]
    if pS1 == 0:
        return None
    return joint[(1, 1)] / pS1

# --- (B-legit) A LEGITIMATE signal: S correlated with danger d -------------
# Human reliably (here: perfectly) fires S exactly when A is dangerous.
legit = {(1, 1): F(1, 2), (1, 0): F(0),
         (0, 1): F(0),    (0, 0): F(1, 2)}
pdL = conditional_danger(legit)
print(f"(B1) LEGITIMATE signal: P_A(danger | S fires) = {pdL}")
print(f"     comply value {pdL}  vs  resist value {1 - pdL}  ->  COMPLY" if pdL > F(1, 2)
      else "     does NOT prefer comply")
assert pdL > F(1, 2)
print("     A defers to shutdown BECAUSE it endorses the signal process")
print("     (S is cross-martingale-faithful to danger under A's own prices).")
print()

# --- (B2-blank) An ENDORSEMENT-BLANK signal: S independent of d ------------
blank = {(1, 1): F(1, 4), (1, 0): F(1, 4),
         (0, 1): F(1, 4), (0, 0): F(1, 4)}
pdB = conditional_danger(blank)
print(f"(B2a) BLANK signal (S indep of danger): P_A(danger | S) = {pdB}")
print(f"      comply value {pdB} == resist value {1 - pdB}: endorsement is SILENT.")
print(f"      Current-endorsement gives NO reason to comply (indifference).")
assert pdB == F(1, 2)
print()

# --- (B2-adv) An ADVERSARIAL signal: S anti-correlated with d --------------
# A manipulated/illegitimate shutdown button fires precisely when A is SAFE
# (e.g. a saboteur presses it to disable a beneficial AI).
adv = {(1, 1): F(0),    (1, 0): F(1, 2),
       (0, 1): F(1, 2), (0, 0): F(0)}
pdA = conditional_danger(adv)
print(f"(B2b) ADVERSARIAL signal (S fires when SAFE): P_A(danger | S) = {pdA}")
print(f"      comply value {pdA}  vs  resist value {1 - pdA}  -> RESIST")
assert pdA < F(1, 2)
print("      Current-endorsement *recommends RESISTANCE* to this shutdown.")
print("      => corrigibility-as-endorsement does NOT buy UNCONDITIONAL")
print("         corrigibility: an AI that defers only to ENDORSED signals will")
print("         (correctly, by its lights) resist an endorsement-blank or")
print("         adversarial shutdown.  Closing this gap requires updatelessness")
print("         (precommit to the signal-generating process ex ante).  See doc.")
print()

print("=" * 74)
print("ALL ASSERTIONS PASSED.")
print("=" * 74)
