#!/usr/bin/env python3
"""Fixture for value-change-as-epistemic-update.md (2026-09-29).

Every number quoted in the note's worked example is computed here with exact
fractions and asserted. Run:  python3 value_change_journey.py

Setup (the two-step modification problem, section 2.5 of the note):
  value hypotheses  theta in {A, B}, prior 1/2 each
  acts              a1, a2, a3 with u_A = (1, 0, s), u_B = (0, 1, s)
  source            emits i in {A, B} with P(i = theta) = r_true
  installed state   Q_i(theta = i) = r_inst   (r_inst = r_true is reflection)
  step 0            accept (get modified, then act) or decline (act now)
"""
from fractions import Fraction as F
from itertools import product

THETAS = ("A", "B")
ACTS = ("a1", "a2", "a3")


def u(theta, act, s):
    """Candidate utility functions u_theta(act)."""
    if act == "a3":
        return s
    return F(1) if (theta, act) in (("A", "a1"), ("B", "a2")) else F(0)


def joint(r_true, s):
    """The agent's joint P(theta, i) on Theta x I; utility U(theta, act)."""
    P = {}
    for theta, i in product(THETAS, THETAS):
        P[(theta, i)] = F(1, 2) * (r_true if i == theta else 1 - r_true)
    return P


def cond_theta_given_i(P, i):
    z = sum(P[(t, i)] for t in THETAS)
    return {t: P[(t, i)] / z for t in THETAS}


def installed(i, r_inst):
    return {t: (r_inst if t == i else 1 - r_inst) for t in THETAS}


def decline_value(P, s):
    """max_a E_P[U_a], acting on the prior over theta."""
    return max(sum(P[(t, i)] * u(t, a, s) for t, i in P) for a in ACTS)


def accept_value(P, s, r_inst, coin=False):
    """sum_i pi_i E_P[U_{a*_i} | E_i], where a*_i maximises the installed Q_i.

    coin=True: the signal is a fair coin independent of theta (the agent's own
    joint is the independent one) but the installed state is still Q_i.
    """
    total = F(0)
    for i in THETAS:
        pi_i = sum(P[(t, i)] for t in THETAS)
        Q = installed(i, r_inst)
        a_star = max(ACTS, key=lambda a: sum(Q[t] * u(t, a, s) for t in THETAS))
        if coin:
            true_cond = {t: F(1, 2) for t in THETAS}
        else:
            true_cond = cond_theta_given_i(P, i)
        total += pi_i * sum(true_cond[t] * u(t, a_star, s) for t in THETAS)
    return total


def martingale_ok(P, r_inst):
    """(M): prior over theta equals the pi-average of the installed states."""
    for t in THETAS:
        avg = sum(sum(P[(t2, i)] for t2 in THETAS) * installed(i, r_inst)[t]
                  for i in THETAS)
        if avg != F(1, 2):
            return False
    return True


def reflection_ok(P, r_inst):
    """P(theta | E_i) == Q_i for every i."""
    return all(cond_theta_given_i(P, i) == installed(i, r_inst) for i in THETAS)


def fine_kolmogorov(P, s):
    """The fine picture: world = I, current utility Ubar(a, i) = E[U_a | i].

    Returns (decline, accept, Ubar) where accept = learn i then act with the
    SAME utility function.
    """
    Ubar = {(a, i): sum(cond_theta_given_i(P, i)[t] * u(t, a, s) for t in THETAS)
            for a, i in product(ACTS, THETAS)}
    pi = {i: sum(P[(t, i)] for t in THETAS) for i in THETAS}
    decline = max(sum(pi[i] * Ubar[(a, i)] for i in THETAS) for a in ACTS)
    accept = sum(pi[i] * max(Ubar[(a, i)] for a in ACTS) for i in THETAS)
    return decline, accept, Ubar


def jeffrey_bolker(P, s):
    """JB on the algebra generated by (theta, i, act), act independent of the
    rest with a uniform self-model. Returns V on the propositions we use."""
    PJ = {(t, i, a): P[(t, i)] / len(ACTS) for t, i, a in product(THETAS, THETAS, ACTS)}
    U = {(t, i, a): u(t, a, s) for t, i, a in PJ}

    def V(prop):  # prop: predicate on atoms
        atoms = [x for x in PJ if prop(x)]
        mass = sum(PJ[x] for x in atoms)
        return sum(PJ[x] * U[x] for x in atoms) / mass

    # averaging axiom on a random disjoint pair
    A_ = lambda x: x[2] == "a1" and x[1] == "A"
    B_ = lambda x: x[2] == "a2" and x[1] == "B"
    lhs = V(lambda x: A_(x) or B_(x))
    pa = sum(PJ[x] for x in PJ if A_(x)); pb = sum(PJ[x] for x in PJ if B_(x))
    rhs = (pa * V(A_) + pb * V(B_)) / (pa + pb)
    assert lhs == rhs, "averaging axiom"
    return {
        "V(a1)": V(lambda x: x[2] == "a1"),
        "V(a1 & A)": V(lambda x: x[2] == "a1" and x[1] == "A"),
        "V(a1 & B)": V(lambda x: x[2] == "a1" and x[1] == "B"),
        "V(a3)": V(lambda x: x[2] == "a3"),
        "V(act on signal)": lhs,
        "V(a1 | A)  [conditioned state]": V(lambda x: x[2] == "a1" and x[1] == "A"),
    }


def representation_error(P, s, r_inst, coin=False, act="a1"):
    """E over (theta, i) of (installed utility - u_theta(act))^2, the mean-square
    distance of the installed representation from the values. With coin=True the
    agent's joint is the independent one (signal uninformative) but Q_i is still
    installed; with r_inst=None the current utility Ubar (no modification)."""
    total = F(0)
    for theta, i in P:
        if r_inst is None:
            rep = sum(F(1, 2) * u(t, act, s) for t in THETAS)
        else:
            Q = installed(i, r_inst)
            rep = sum(Q[t] * u(t, act, s) for t in THETAS)
        p = (F(1, 4) if coin else P[(theta, i)])
        total += p * (rep - u(theta, act, s)) ** 2
    return total


def decomposition(vK, branches):
    """Section 1.4: Val(C) - Val(K) = (A) choice + (B) adaptation + (C) level.

    vK: dict act -> v_K(a).  branches: list of (p_j, v_j dict, a_j) where a_j is
    the act the CHANGED agent takes in C_j.  a^K maximises v_K; \\hat a^j maximises v_j.
    """
    aK = max(ACTS, key=lambda a: vK[a])
    A = B = C = F(0)
    for p, vj, aj in branches:
        ahat = max(ACTS, key=lambda a: vj[a])
        A += p * (vj[aj] - vj[ahat])
        B += p * (vj[ahat] - vj[aK])
        C += p * (vj[aK] - vK[aK])
    return A, B, C


def total_trust_example():
    """The modest-source example from the 2026-09-29 chat (section 6.6).

    Two worlds, P = (0.3, 0.7); the source's opinion is Q_1 = (0.9, 0.1) in
    world 1 and Q_2 = (0.1, 0.9) in world 2. Checks: Total Trust holds on a
    grid of payoff vectors; the martingale condition fails; P is in the
    convex hull of {Q_1, Q_2} with weights (1/4, 3/4), not (0.3, 0.7).
    """
    P = (F(3, 10), F(7, 10))
    Q = {1: (F(9, 10), F(1, 10)), 2: (F(1, 10), F(9, 10))}
    grid = [F(k, 4) for k in range(-8, 9)]
    for x1, x2 in product(grid, grid):
        X = (x1, x2)
        Y = {w: Q[w][0] * x1 + Q[w][1] * x2 for w in (1, 2)}
        for t in set(Y.values()):
            worlds = [w for w in (1, 2) if Y[w] >= t]
            mass = sum(P[w - 1] for w in worlds)
            cond = sum(P[w - 1] * X[w - 1] for w in worlds) / mass
            assert cond >= t, ("Total Trust fails", X, t)
    m = P[0] * Q[1][0] + P[1] * Q[2][0]
    assert m == F(34, 100) and m != P[0], "martingale should fail"
    lam = (P[0] - Q[2][0]) / (Q[1][0] - Q[2][0])
    assert lam == F(1, 4)
    return m, lam


def main():
    s = F(6, 10)
    rows = []

    def row(name, P, r_inst, coin=False):
        d = decline_value(P, s)
        a = accept_value(P, s, r_inst, coin=coin)
        rows.append((name, d, a, martingale_ok(P, r_inst),
                     (not coin) and reflection_ok(P, r_inst)))
        return d, a

    # (1) trusted, informative source: reflection holds
    P = joint(F(9, 10), s)
    d, a = row("informative r=0.9, reflection", P, F(9, 10))
    assert (d, a) == (F(6, 10), F(9, 10))

    # (2) known target / pill: installed (0.9, 0.1) regardless of anything.
    # Modelled as a source whose signal is uninformative; both branches install
    # the same act ranking as far as a1 vs a3 goes, so the value is E_P[U_{a1}].
    d, a = row("pill to (0.9,0.1), uninformative", joint(F(1, 2), s), F(9, 10))
    assert (d, a) == (F(6, 10), F(1, 2))

    # (3) fair coin independent of theta, installed Q_i: (M) holds, reflection fails
    d, a = row("coin, (M) holds, reflection fails", joint(F(9, 10), s), F(9, 10), coin=True)
    assert (d, a) == (F(6, 10), F(1, 2))

    # (4) general formula: accept = max(r, s) vs decline = max(1/2, s) under reflection
    for r in [F(k, 20) for k in range(10, 21)]:
        Pr = joint(r, s)
        assert accept_value(Pr, s, r) == max(r, s)
        assert decline_value(Pr, s) == max(F(1, 2), s)

    # (5) mismatch: true reliability r, installed confidence r'
    #     future acts on the signal iff r' >= s; current self values that at r.
    for r, ri in product([F(k, 20) for k in range(10, 21)], repeat=2):
        Pr = joint(r, s)
        expected = r if ri >= s else s
        assert accept_value(Pr, s, ri) == expected, (r, ri)

    # (6) fine Kolmogorov: same utility function, conditioning on i
    fd, fa, Ubar = fine_kolmogorov(joint(F(9, 10), s), s)
    assert (fd, fa) == (F(6, 10), F(9, 10))
    assert Ubar[("a1", "A")] == F(9, 10) and Ubar[("a1", "B")] == F(1, 10)
    assert Ubar[("a3", "A")] == s
    # coarse marginal of the fine utility is the Gandhi agent's utility
    coarse = {a: sum(F(1, 2) * Ubar[(a, i)] for i in THETAS) for a in ACTS}
    assert coarse == {"a1": F(1, 2), "a2": F(1, 2), "a3": s}
    # value-side martingale (M^U) holds
    assert F(1, 2) * Ubar[("a1", "A")] + F(1, 2) * Ubar[("a1", "B")] == F(1, 2)

    # (7) Jeffrey-Bolker
    jb = jeffrey_bolker(joint(F(9, 10), s), s)
    assert jb["V(a1)"] == F(1, 2) and jb["V(a1 & A)"] == F(9, 10)
    assert jb["V(a3)"] == s and jb["V(act on signal)"] == F(9, 10)

    # (8) Total Trust vs martingale
    m, lam = total_trust_example()

    # (10) the three-term decomposition of section 1.4
    vK = {a: sum(F(1, 2) * u(t, a, s) for t in THETAS) for a in ACTS}      # (1/2, 1/2, 3/5)
    vj = lambda i: {a: sum(cond_theta_given_i(joint(F(9, 10), s), i)[t] * u(t, a, s) for t in THETAS) for a in ACTS}
    teacher = decomposition(vK, [(F(1, 2), vj("A"), "a1"), (F(1, 2), vj("B"), "a2")])
    pill = decomposition(vK, [(F(1), dict(vK), "a1")])                      # known target, uninformative
    coin = decomposition(vK, [(F(1, 2), dict(vK), "a1"), (F(1, 2), dict(vK), "a2")])
    shifted = lambda b: {a: vK[a] + b for a in ACTS}
    paid = decomposition(vK, [(F(1), shifted(F(1, 5)), "a1")])             # intrinsic, beta = 0.2
    underpaid = decomposition(vK, [(F(1), shifted(F(1, 20)), "a1")])       # intrinsic, beta = 0.05
    assert teacher == (F(0), F(3, 10), F(0))
    assert pill == (F(-1, 10), F(0), F(0)) and coin == (F(-1, 10), F(0), F(0))
    assert paid == (F(-1, 10), F(0), F(1, 5)) and sum(paid) == F(1, 10)
    assert underpaid == (F(-1, 10), F(0), F(1, 20)) and sum(underpaid) == F(-1, 20)

    # (9) representation accuracy: mean-square distance of the utility the agent
    #     acts on from the value random variable u_theta, act a1
    P9 = joint(F(9, 10), s)
    err_now = representation_error(P9, s, None)
    err_teacher = representation_error(P9, s, F(9, 10))
    err_coin = representation_error(P9, s, F(9, 10), coin=True)
    err_pill = representation_error(joint(F(1, 2), s), s, F(9, 10))
    assert (err_now, err_teacher, err_coin, err_pill) == (F(1, 4), F(9, 100), F(41, 100), F(41, 100))
    # Pythagoras under reflection: err_now = E[(Ubar - Ubar^(i))^2] + err_teacher
    gap = sum(F(1, 2) * (F(1, 2) - v) ** 2 for v in (F(9, 10), F(1, 10)))
    assert err_now == gap + err_teacher

    print(f"{'case':40s} {'decline':>8s} {'accept':>8s}  (M)  refl")
    for name, d, a, mo, ro in rows:
        print(f"{name:40s} {str(d):>8s} {str(a):>8s}  {str(mo):5s} {ro}")
    print("\nfine Kolmogorov: decline", fd, "accept", fa)
    print("  Ubar(a, i):", {k: str(v) for k, v in Ubar.items()})
    print("\nJeffrey-Bolker:", {k: str(v) for k, v in jb.items()})
    print("\nTotal-Trust example: E[Q(1)] =", m, "(P(1) = 3/10); hull weight on Q_1 =", lam)
    print("\nsection 1.4 decomposition (A, B, C): teacher", teacher, "| pill", pill, "| coin", coin,
          "| paid 0.2", paid, "| paid 0.05", underpaid)
    print("\nrepresentation error for a1 (mean square to u_theta): now", err_now,
          "| teacher", err_teacher, "| coin", err_coin, "| pill", err_pill)
    print("\nall assertions passed")


if __name__ == "__main__":
    main()
