/-
  UNCHECKED — for the Lean-verify agent.

  Candidate formalization of the algebraic core of the principal's proposed theorem
  (AGENDA, "Unbounded Embedded Agency / Updatelessness"):

      "if a UDT1.0 agent (1-δ)-believes its policy is UDT1.1, then it is ε-optimal,"
      with ε = O(δ) · (utility range).

  HONEST BOUND.  The exactly-provable inequality is
      (1 - δ) · (Vstar pstar - Vstar s)  ≤  δ · (hi - lo),
  i.e. the TRUE optimality gap satisfies  Vstar pstar - Vstar s ≤ δ/(1-δ) · (hi-lo).
  So ε(δ) = δ/(1-δ)·range, which is δ·range to leading order and ≤ 2δ·range for δ ≤ 1/2.
  The naive "ε = δ·range" is only the first-order approximation; the (1-δ) factor is real
  (the bad δ-world is weighed against the (1-δ) good-world mass, not against 1). The clean
  corollary `epsilon_optimal_clean` records the 2δ·range form for δ ≤ 1/2.

  WHAT THIS LEAN IS SUPPOSED TO SAY (read critically against the math):

  A UDT1.0 agent selects, at each decision point, a candidate full policy σ (or, equivalently
  for a fixed menu, an action that is part of one) so as to maximize the *believed* expected
  utility of σ. Its belief about WHO MAKES ITS DECISIONS is a (1-δ)/δ mixture:
    • with probability (1-δ) it believes its policy is generated by the optimal procedure
      UDT1.1, whose induced value-of-a-policy map is `Vstar : Pol → ℝ`;
    • with probability δ it believes its policy is generated by some OTHER (arbitrary, possibly
      adversarial) procedure, with value map `Vother : Pol → ℝ`.
  Hence the agent's believed value of a candidate policy σ is
      Bel σ = (1-δ) · Vstar σ + δ · Vother σ.
  The agent commits to a believed-maximizer `s` of `Bel`. We ask how good `s` actually is under
  the *true* (UDT1.1) value map `Vstar`. The claim: `Vstar s` is within `δ·(hi-lo)` of the true
  optimum `Vstar pstar`, where `pstar` is the genuine UDT1.1 policy (a `Vstar`-maximizer) and
  `[lo,hi]` bounds the value maps (bounded utility — the §6/Coin hygiene condition).

  This is the "Stag-Hunt cannot trap you if you believe a coordinator is choosing the whole
  policy" content: the (1-δ) belief that UDT1.1 (which optimizes the *whole policy at once*) is
  in charge does the work of Cole Wyeth's hand-constructed reflective oracle. The bound is
  linear in δ and in the utility range — exactly an ε(δ)-optimality statement, vacuous-free as
  long as hi>lo.

  It is PURE FINITE ALGEBRA: no reflective oracles, no LI, no fixed points. It mirrors the
  discipline of `lean-deference/LeanDeference.lean`'s `value_of_CM` (a clean δ=0-style bound
  taken under explicit boundedness + argmax hypotheses), and is meant to be the honest
  *shadow* of the real theorem, NOT the real theorem (which needs the reflective-oracle /
  rOSI apparatus to even define Vstar, Vother as believed continuations).

  FIDELITY CAVEATS (the gap the verify agent must weigh):
  - `Vother` is left completely arbitrary subject only to the bound. That is FAITHFUL: the whole
    point is that the (1-δ) mass on UDT1.1 dominates regardless of what the bad δ-world says.
  - We model the agent as choosing among *policies* σ with a single believed-value functional,
    which is the UDT1.1 ("choose whole policy") move. A genuine UDT1.0 agent chooses ACTIONS
    pointwise; the reduction "pointwise UDT1.0 that believes it is UDT1.1 = chooses the believed
    UDT1.1 policy" is the informal bridge this Lean ASSUMES, not proves. Flag: this is where the
    real subtlety (self-coordination / Stag Hunt) is smuggled into the hypothesis, honestly.
  - `pstar` is asserted to be a `Vstar`-maximizer by hypothesis `hpstar`; this is the definition
    of UDT1.1 (the optimal policy), not a smuggled conclusion.
-/
import Mathlib.Data.Real.Basic
import Mathlib.Algebra.Order.Field.Basic
import Mathlib.Tactic.Linarith

namespace UDT11Belief

variable {Pol : Type*}

/-- The agent's believed value of policy `σ`: a `(1-δ)/δ` mixture of the UDT1.1 value map
    `Vstar` and an arbitrary "other code" value map `Vother`. -/
def Bel (δ : ℝ) (Vstar Vother : Pol → ℝ) (σ : Pol) : ℝ :=
  (1 - δ) * Vstar σ + δ * Vother σ

/--
  ε-optimality from (1-δ)-belief that you are UDT1.1.

  Hypotheses:
  * `hδ0 : 0 ≤ δ`, `hδ1 : δ ≤ 1`     — `δ` is a probability (mass on the "wrong-code" world).
  * `hlo`, `hhi`                      — both value maps lie in `[lo, hi]` (bounded utility).
  * `hpstar : ∀ σ, Vstar σ ≤ Vstar pstar`   — `pstar` is a genuine UDT1.1 optimum (def. of UDT1.1).
  * `hsel : ∀ σ, Bel δ Vstar Vother σ ≤ Bel δ Vstar Vother s`  — `s` maximizes the BELIEVED value
        (this is what the UDT1.0-believing-it-is-UDT1.1 agent commits to).

  Conclusion: `Vstar pstar - δ * (hi - lo) ≤ Vstar s`,
  i.e. the agent's actually-chosen policy is within `δ·(hi-lo)` of the true optimum under the
  true (UDT1.1) value map. With `ε := δ*(hi-lo)` this is the ε-optimality claim.
-/
theorem epsilon_optimal_of_belief
    (δ lo hi : ℝ) (Vstar Vother : Pol → ℝ) (pstar s : Pol)
    (hδ0 : 0 ≤ δ)
    (hloO : ∀ σ, lo ≤ Vother σ) (hhiO : ∀ σ, Vother σ ≤ hi)
    (hsel : ∀ σ, Bel δ Vstar Vother σ ≤ Bel δ Vstar Vother s) :
    (1 - δ) * (Vstar pstar - Vstar s) ≤ δ * (hi - lo) := by
  -- Believed value of the chosen `s` is at least the believed value of the true optimum `pstar`.
  have key : Bel δ Vstar Vother pstar ≤ Bel δ Vstar Vother s := hsel pstar
  -- Unfold. Bel σ = (1-δ)*Vstar σ + δ*Vother σ.
  unfold Bel at key
  -- The δ-mass on the wrong-code world can swing by at most (hi - lo):
  --   δ*Vother pstar ≥ δ*lo,  δ*Vother s ≤ δ*hi.
  have hδloO : δ * lo ≤ δ * Vother pstar := mul_le_mul_of_nonneg_left (hloO pstar) hδ0
  have hδhiO : δ * Vother s ≤ δ * hi := mul_le_mul_of_nonneg_left (hhiO s) hδ0
  -- key : (1-δ)Vp + δ Op ≤ (1-δ)Vs + δ Os.  Subtracting,
  --   (1-δ)(Vp - Vs) ≤ δ(Os - Op) ≤ δ(hi - lo).
  nlinarith [hδloO, hδhiO, key]

/-- Clean ε-optimality for `δ ≤ 1/2` (so `1-δ ≥ 1/2`): the chosen policy's TRUE value is within
    `2δ·(hi-lo)` of the optimum.  This is the principal's "ε(δ)-optimal" with `ε = 2δ·range`. -/
theorem epsilon_optimal_clean
    (δ lo hi : ℝ) (Vstar Vother : Pol → ℝ) (pstar s : Pol)
    (hδ0 : 0 ≤ δ) (hδhalf : δ ≤ 1 / 2)
    (hpstar : ∀ σ, Vstar σ ≤ Vstar pstar)   -- pstar is the genuine UDT1.1 optimum
    (hloO : ∀ σ, lo ≤ Vother σ) (hhiO : ∀ σ, Vother σ ≤ hi)
    (hsel : ∀ σ, Bel δ Vstar Vother σ ≤ Bel δ Vstar Vother s) :
    Vstar pstar - 2 * δ * (hi - lo) ≤ Vstar s := by
  have core := epsilon_optimal_of_belief δ lo hi Vstar Vother pstar s hδ0 hloO hhiO hsel
  -- core : (1-δ)(Vp - Vs) ≤ δ(hi-lo);  pstar optimal gives Vp - Vs ≥ 0;  1-δ ≥ 1/2.
  have hgap : 0 ≤ Vstar pstar - Vstar s := by linarith [hpstar s]
  -- For the bound we only need the range nonnegative as well:
  have hrange : 0 ≤ hi - lo := by linarith [hloO s, hhiO s]
  -- (1/2 - δ) ≥ 0 and (Vp - Vs) ≥ 0, so their product is ≥ 0; combine with core.
  nlinarith [core, hgap, hrange, mul_nonneg hgap (by linarith : (0:ℝ) ≤ 1/2 - δ)]

/-- The δ = 0 corner: certainty that you are UDT1.1 gives EXACT optimality (no gap). -/
theorem optimal_of_certain
    (Vstar Vother : Pol → ℝ) (pstar s : Pol)
    (hsel : ∀ σ, Bel 0 Vstar Vother σ ≤ Bel 0 Vstar Vother s) :
    Vstar pstar ≤ Vstar s := by
  have key := hsel pstar
  unfold Bel at key
  simp only [sub_zero, one_mul, zero_mul, add_zero] at key
  exact key

#print axioms epsilon_optimal_of_belief
#print axioms epsilon_optimal_clean
#print axioms optimal_of_certain

end UDT11Belief
