/-
  UNCHECKED — for the Lean-verify agent.

  Candidate file for the "Updatelessness & deference" thread.

  WHAT THIS IS MEANT TO CAPTURE (plain English):
  --------------------------------------------------------------------------
  The Geometric-UDT split conjecture says: an aligned agent should be
  "updateful about moral uncertainty / values" but "updateless about other
  matters". The cleanest formalizable shadow of *why such a split can be
  consistent* is the following decomposition fact about multi-situation
  decision problems (the same algebra the v2 §3 `decomposition` and the
  `when-udt-edt-diverge` note rest on):

  Model a decision problem as a finite menu of situations `S`, a prior `p`
  over them, an action set, and a utility `U : S → A → ℝ` that is
  *separable across situations* — i.e. utility at situation `s` depends only
  on the action chosen at `s` (NO cross-situation dependence). Then the
  globally-optimal-policy value (the UDT/"updateless" objective) equals the
  sum over situations of the locally-optimal value (the EDT/"updateful"
  objective). I.e. when the utility coordinate carries no acausal /
  cross-situation coupling, updateless and updateful optimization COINCIDE,
  situation by situation.

  THE BRIDGE TO THE THREAD: a "moral-uncertainty"/values coordinate is
  exactly one in which there is no cross-situation dependence *in the agent's
  own actions* — learning a value fact does not change what other copies of
  you do, it only re-weights outcomes. On such a coordinate the updateless
  agent is content to defer to its updated (more-knowledgeable) self, because
  the two objectives agree. The counterfactual-mugging / transparent-Newcomb
  failures of endorsement⇔deference live entirely in the COMPLEMENTARY
  coordinate, where U genuinely couples situations.

  We prove only the SEPARABLE direction here (the easy, load-bearing half):
  separability ⇒ global optimum decomposes into local optima. This is the
  precise sense in which "no coupling ⇒ updateful = updateless".

  FIDELITY CHECK (read critically):
  - `U : S → A → ℝ` with NO dependence of `U s` on actions at other
    situations is the faithful encoding of "no cross-situation dependence"
    (it is literally `U(s, a)` not `U(s, a, context)`). Good: the hypothesis
    is structural, not smuggling the conclusion.
  - Conclusion: `∑ s, p s * U s (π s)` is maximized (over policies `π`) by
    choosing, at each `s`, an `A`-maximizer of `a ↦ U s a`. We phrase it as:
    the sup of the policy objective equals the sum of the per-situation sups.
    This is genuinely the "global = sum of locals" claim, NON-VACUOUS because
    it would FAIL for a coupled `U : S → (S → A) → ℝ` (no decomposition).
  - Quantifiers: `∀ p ≥ 0`, finite `S`, finite nonempty `A`. Matches prose.
  - What it does NOT claim: it says nothing about the COUPLED case (that is
    the open content). It is the trivial-but-correct boundary fact that makes
    the split conjecture coherent. Marked accordingly.

  NOTE FOR THE LEAN-VERIFY AGENT (lemma-name / defeq checks I did by hand):
  - `Finset.sum_le_sum (h : ∀ i ∈ s, f i ≤ g i)` — exists, generated by
    `@[to_additive ... sum_le_sum]` from `prod_le_prod'` in
    `Mathlib/Algebra/Order/BigOperators/Group/Finset.lean` (imported).
  - `Finset.le_sup' (f) (h : b ∈ s) : f b ≤ s.sup' ⟨b,h⟩ f` — note the
    nonempty witness in the RHS is `⟨b,h⟩`, whereas `splitOptimum` uses
    `Finset.univ_nonempty`. `Finset.sup'` ignores its nonempty proof argument
    (it is a `Prop`, proof-irrelevant), so `s.sup' ⟨b,h⟩ f` and
    `s.sup' univ_nonempty f` are defeq; `exact` should unify. THIS is the one
    spot to watch — if it fails, replace with `le_sup'_of_le` or add
    `Finset.sup'_congr`/`exact?`.
  - `Finset.exists_mem_eq_sup' (H) (f) : ∃ i, i ∈ s ∧ s.sup' H f = f i` —
    note the equation is `sup' = f i`, so we use `ha.symm` to get `f i = sup'`.
  - `Finset.univ_nonempty [Nonempty α]` — provided here by `[Nonempty A]`.
  - `mul_le_mul_of_nonneg_left (hbc : b ≤ c) (ha : 0 ≤ a) : a*b ≤ a*c` —
    argument order matches the `mul_le_mul_of_nonneg_left _ (hp s)` call.
-/
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.Order.BigOperators.Group.Finset
import Mathlib.Data.Finset.Lattice.Fold
import Mathlib.Data.Real.Basic

open Finset

namespace UpdatelessDeference

variable {S A : Type*} [Fintype S] [Fintype A] [Nonempty A]

/-- The "updateless" (UDT) objective of a policy `π : S → A`:
    expected utility of the whole policy under prior `p`, when utility is
    separable across situations (`U : S → A → ℝ`, no cross-situation term). -/
def policyValue (p : S → ℝ) (U : S → A → ℝ) (π : S → A) : ℝ :=
  ∑ s, p s * U s (π s)

/-- The "updateful" (per-situation/EDT) optimum: at each situation pick the
    best local action, then aggregate. With a separable `U` this is the sum
    over situations of `p s` times the local max. -/
noncomputable def splitOptimum (p : S → ℝ) (U : S → A → ℝ) : ℝ :=
  ∑ s, p s * (Finset.univ.sup' Finset.univ_nonempty (fun a => U s a))

/-- KEY LEMMA (UNCHECKED): with a separable utility and nonnegative prior,
    the best achievable policy value (over a witnessing argmax policy) equals
    the split optimum. Concretely: define the policy `πstar` that picks a
    local argmax at each `s`; then its `policyValue` equals `splitOptimum`,
    AND no policy beats it. This is "updateless = updateful when there is no
    cross-situation coupling."

    We state the clean equality `policyValue p U πstar = splitOptimum p U`
    plus optimality `∀ π, policyValue p U π ≤ splitOptimum p U` (needs `p ≥ 0`).
-/
theorem split_eq_global
    (p : S → ℝ) (U : S → A → ℝ) (hp : ∀ s, 0 ≤ p s) :
    -- (1) the split optimum dominates every policy's value
    (∀ π : S → A, policyValue p U π ≤ splitOptimum p U) := by
  intro π
  unfold policyValue splitOptimum
  apply Finset.sum_le_sum
  intro s _
  apply mul_le_mul_of_nonneg_left _ (hp s)
  exact Finset.le_sup' (fun a => U s a) (Finset.mem_univ (π s))

/-- (2) The bound is ACHIEVED by a policy that picks a local argmax at each
    situation, so the split optimum is exactly the global optimum.
    `Finset.exists_mem_eq_sup'` gives a maximizer at each `s`; assembling
    them pointwise yields the witnessing policy. -/
theorem split_achieved
    (p : S → ℝ) (U : S → A → ℝ) :
    ∃ π : S → A, policyValue p U π = splitOptimum p U := by
  -- choose a local maximizer at each situation
  have hmax : ∀ s, ∃ a : A, U s a = Finset.univ.sup' Finset.univ_nonempty (fun a => U s a) := by
    intro s
    obtain ⟨a, _, ha⟩ := Finset.exists_mem_eq_sup' (Finset.univ_nonempty) (fun a => U s a)
    exact ⟨a, ha.symm⟩
  choose π hπ using hmax
  refine ⟨π, ?_⟩
  unfold policyValue splitOptimum
  apply Finset.sum_congr rfl
  intro s _
  rw [hπ s]

#print axioms split_eq_global
#print axioms split_achieved

end UpdatelessDeference
