import Cleanroom.Corrigibility.CorrJointProcess.Cellwise
import Mathlib.Analysis.SpecificLimits.Basic

/-!
# T10 — Prop. 8: the corruption floor and its erosion

Load-bearing 5.

* **(a) Floor arithmetic (`C`).** If `ε_i ≥ ε_∞` in every cell and the sensor meets the
  stationary target `(1 − ε_∞) α c ≤ ε_∞ β h` (the odds form `α/β ≤ (ε_∞/(1−ε_∞))(h/c)`), then
  cellwise (i) holds in every cell of the blind mixture round (`floor_cellwise_mixture`,
  `floor_cellwise_of_odds`). The target is `4/99` at `ε_∞ = 1/100`, `h/c = 4`
  (`floor_target_four_ninetynine`).
* **(b) Erosion (`P`).** The Bayes recursion for a floor hypothesis `C` with per-round likelihood
  ratio `k` on good rounds, `p_n = ε k^n/(ε k^n + 1 − ε)` (`floorPosterior`): strictly decreasing
  for `0 < k < 1` (`floorPosterior_strictAnti`), `→ 0` (`floorPosterior_tendsto_zero`), the least
  crossing of any `τ > 0` exists (`floorPosterior_least_crossing`), and the floor is preserved at
  every round iff `k = 1` (`floorPosterior_const_iff`) — "any evidential traction updates it away".
  Witness `ε = 1/100`, `k = 9/10`: `p_50 < 10⁻⁴`; the crossing of `10⁻⁴` is at `n = 44`
  (`floorPosterior_witness`, `floorPosterior_crossing_44`).
* **(c) The requirement sequence, resolved.** Without a floor `ε_t = (1/5) 2^{−t}` gives
  `1, 4/9, 4/19, 4/39, …`; the develop's printed with-floor sequence `1, 84/179, 92/377, 108/773,
  28/313` is generated by `ε'_t = 2^{−t}(1/5) + (1 − 2^{−t})(1/100)` (mass migrating to the floor,
  `epsWithFloor`), *not* by `max(ε_t, ε_∞)` (`epsMaxFloor`, which gives `…, 4/79, 4/99, 4/99`);
  both converge to `4/99` (`requirement_table`, `epsWithFloor_bound_tendsto`,
  `epsMaxFloor_bound_eventually`). Finding: the discrepancy (2-003's flag).

**Refutation row** (`joint.md` l. 139: "a self-corruption floor turns the race into a fixed
target … a **stationary** oversight target replaces `α_t/β_t → 0`"): read as the floor being a
Bayes-preserved hypothesis, `floorPosterior_const_iff` says it is preserved iff the likelihood
ratio is exactly `1` — INDEX §C5's dogmatic design constant; the surviving neighbour is (a)
conditional on the floor.

Sources: joint-final.md Prop. 8; joint.md Prop. 8 (l. 139), P.9; adv A.16.1, (F); script (g).
-/

namespace Cleanroom.Corrigibility.CorrJointProcess

open FactoredSpaces Cleanroom.Found.CorrThreeStep Cleanroom.Found.CorrThreeStep.ThreeStep
open Finset hiding expect
open Filter Topology

set_option linter.unusedSectionVars false

/-! ## (a) The floor arithmetic -/

/-- **T10(a), product form.** If `ε_∞ ≤ ε` and the sensor meets the stationary target at the
floor, `(1 − ε_∞) α c ≤ ε_∞ β h`, then it meets it at `ε`: the right side of (i) is monotone in
`ε` (`αc, βh ≥ 0`).
Source: [[corr-wf14-inventory]] 066 / joint.md P.9 ("the right side of (i) is increasing in `ε`")
Kind: L
Fidelity: exact (product form)
Hyps: (a) only -/
theorem floor_product (ε εinf α β c h : ℝ) (hfloor : εinf ≤ ε) (hαc : 0 ≤ α * c) (hβh : 0 ≤ β * h)
    (htarget : (1 - εinf) * α * c ≤ εinf * β * h) : (1 - ε) * α * c ≤ ε * β * h := by
  nlinarith

/-- **T10(a) (Prop. 8, conditional): under the floor, cellwise (i) holds in every cell of a blind
mixture round whose sensor meets the stationary target.** The hypothesis `ε_i ≥ ε_∞` *is* the
floor (`P_t(C_t ∣ y_t) ≥ ε_∞` with `W_t = 1` on `C_t`); the source's own verdict is that the
hypothesis is the whole problem — (b) below.
Source: [[corr-wf14-inventory]] 066, 2-003 / joint-final.md Prop. 8 ("downgraded to conditional"); joint.md P.9
Kind: C (`floor_product` composed with the mixture identity and the parent's first form)
Fidelity: exact
Hyps: (a) only; the floor `hfloor` is the source's hypothesis, named -/
theorem floor_cellwise_mixture {Y : Type} [Fintype Y] [DecidableEq Y] (w ε : Y → ℝ) (εinf α β c h : ℝ)
    (hw : ∀ i, 0 ≤ w i) (hw1 : ∑ i, w i = 1) (hε : ∀ i, ε i ∈ Set.Icc (0 : ℝ) 1)
    (hα : α ∈ Set.Icc (0 : ℝ) 1) (hβ : β ∈ Set.Icc (0 : ℝ) 1) (hc : 0 ≤ c) (hh : 0 ≤ h)
    (hfloor : ∀ i, εinf ≤ ε i) (htarget : (1 - εinf) * α * c ≤ εinf * β * h) :
    ∀ i, (mixtureRound w ε α β c h hw hw1 hε hα hβ).cellwiseBelowThreshold i := by
  intro i
  unfold JointRound.cellwiseBelowThreshold
  rw [mixture_cellPressSum, neg_nonpos]
  refine mul_nonneg (hw i) ?_
  rw [twoState_deltaMinus_nonneg_iff]
  exact floor_product (ε i) εinf α β c h (hfloor i) (mul_nonneg hα.1 hc) (mul_nonneg hβ.1 hh) htarget

/-- **T10(a), odds form (Prop. 8).** With `α/β ≤ (ε_∞/(1 − ε_∞))·(h/c)` (`ε_∞ < 1`, `0 < β`,
`0 < c`) the stationary target is met and cellwise (i) holds in every cell under the floor.
Source: [[corr-wf14-inventory]] 066 / joint-final.md Prop. 8 ("as soon as `α_t/β_t ≤ (ε_∞/(1−ε_∞))(h_t/c_t)`")
Kind: C
Fidelity: exact
Hyps: (a) only; `hfloor` is the source's floor hypothesis -/
theorem floor_cellwise_of_odds {Y : Type} [Fintype Y] [DecidableEq Y] (w ε : Y → ℝ) (εinf α β c h : ℝ)
    (hw : ∀ i, 0 ≤ w i) (hw1 : ∑ i, w i = 1) (hε : ∀ i, ε i ∈ Set.Icc (0 : ℝ) 1)
    (hα : α ∈ Set.Icc (0 : ℝ) 1) (hβ : β ∈ Set.Icc (0 : ℝ) 1) (hc : 0 < c) (hh : 0 ≤ h)
    (hεinf : εinf ∈ Set.Icc (0 : ℝ) 1) (hεinf1 : εinf < 1) (hβ0 : 0 < β)
    (hfloor : ∀ i, εinf ≤ ε i) (hodds : α / β ≤ εinf / (1 - εinf) * (h / c)) :
    ∀ i, (mixtureRound w ε α β c h hw hw1 hε hα hβ).cellwiseBelowThreshold i := by
  have htarget : (1 - εinf) * α * c ≤ εinf * β * h := by
    have := (twoState_deltaMinus_nonneg_iff_odds εinf α β c h hεinf hα hβ hεinf1 hβ0 hc).2 hodds
    exact (twoState_deltaMinus_nonneg_iff εinf α β c h hεinf hα hβ).1 this
  exact floor_cellwise_mixture w ε εinf α β c h hw hw1 hε hα hβ hc.le hh hfloor htarget

/-- **The stationary target `4/99`** at `ε_∞ = 1/100`, `h/c = 4`.
Source: [[corr-wf14-inventory]] 066 / joint-final.md Prop. 8 ("`4/99` with `ε_∞ = 1/100`, `h/c = 4`")
Kind: N+
Fidelity: exact
Hyps: (a) only -/
theorem floor_target_four_ninetynine : (1 / 100 : ℝ) / (1 - 1 / 100) * 4 = 4 / 99 := by norm_num

/-! ## (b) Erosion: the Bayes recursion for the floor hypothesis -/

/-- **The floor posterior after `n` good rounds**: `p_n = ε k^n / (ε k^n + 1 − ε)` — Bayes for a
hypothesis `C` of prior `ε` whose likelihood ratio against each good outcome is `k`.
Source: [[corr-wf14-inventory]] 2-003 / adv A.16.1, (F) ("`P(C ∣ history)` falls from `1/100` to `5×10⁻⁵`")
Kind: D
Fidelity: exact -/
noncomputable def floorPosterior (ε k : ℝ) (n : ℕ) : ℝ := ε * k ^ n / (ε * k ^ n + (1 - ε))

/-- `p_0 = ε`. Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma floorPosterior_zero (ε k : ℝ) : floorPosterior ε k 0 = ε := by
  simp [floorPosterior]

/-- The map `x ↦ εx/(εx + 1 − ε)` is strictly increasing on `x > 0` for `0 < ε < 1`.
Source: none: infrastructure. Kind: L. Fidelity: n/a -/
lemma floor_map_strictMono (ε : ℝ) (hε0 : 0 < ε) (hε1 : ε < 1) {x y : ℝ} (hx : 0 < x) (hxy : x < y) :
    ε * x / (ε * x + (1 - ε)) < ε * y / (ε * y + (1 - ε)) := by
  rw [div_lt_div_iff₀ (by nlinarith) (by nlinarith)]
  nlinarith [mul_pos hε0 (sub_pos.2 hε1), mul_pos hε0 hx]

/-- **T10(b): the floor posterior is strictly decreasing** for `0 < k < 1`, `0 < ε < 1`.
Source: [[corr-wf14-inventory]] 2-003 / adv A.16.1 ("a hypothesis `C_t` with *any* evidential traction is updated away")
Kind: P
Fidelity: exact
Hyps: (a) only -/
theorem floorPosterior_strictAnti (ε k : ℝ) (hε0 : 0 < ε) (hε1 : ε < 1) (hk0 : 0 < k) (hk1 : k < 1) :
    StrictAnti (floorPosterior ε k) := by
  refine strictAnti_nat_of_succ_lt fun n => ?_
  unfold floorPosterior
  apply floor_map_strictMono ε hε0 hε1 (pow_pos hk0 _)
  rw [pow_succ]
  exact mul_lt_of_lt_one_right (pow_pos hk0 n) hk1

/-- **T10(b): the floor posterior tends to `0`.**
Source: [[corr-wf14-inventory]] 2-003 / adv A.16.1
Kind: P
Fidelity: exact
Hyps: (a) only -/
theorem floorPosterior_tendsto_zero (ε k : ℝ) (hε1 : ε < 1) (hk0 : 0 ≤ k) (hk1 : k < 1) :
    Tendsto (floorPosterior ε k) atTop (𝓝 0) := by
  have hpow : Tendsto (fun n : ℕ => k ^ n) atTop (𝓝 0) := tendsto_pow_atTop_nhds_zero_of_lt_one hk0 hk1
  have hnum : Tendsto (fun n : ℕ => ε * k ^ n) atTop (𝓝 (ε * 0)) := tendsto_const_nhds.mul hpow
  have hden : Tendsto (fun n : ℕ => ε * k ^ n + (1 - ε)) atTop (𝓝 (ε * 0 + (1 - ε))) :=
    hnum.add tendsto_const_nhds
  have := hnum.div hden (by rw [mul_zero, zero_add]; exact (sub_pos.2 hε1).ne')
  rw [mul_zero, zero_add, zero_div] at this
  exact this

/-- **T10(b): every threshold `τ > 0` is crossed**, and the least crossing index exists: there
is `n₀` with `p_{n₀} < τ` and `τ ≤ p_n` for all `n < n₀` (plan §0.4 rule 4).
Source: [[corr-wf14-inventory]] 2-003 / adv (F)
Kind: P
Fidelity: exact
Hyps: (a) only -/
theorem floorPosterior_least_crossing (ε k τ : ℝ) (hε1 : ε < 1) (hk0 : 0 ≤ k) (hk1 : k < 1) (hτ : 0 < τ) :
    ∃ n₀ : ℕ, floorPosterior ε k n₀ < τ ∧ ∀ n < n₀, τ ≤ floorPosterior ε k n := by
  have hev : ∀ᶠ n in atTop, floorPosterior ε k n < τ :=
    (floorPosterior_tendsto_zero ε k hε1 hk0 hk1).eventually (gt_mem_nhds hτ)
  obtain ⟨N, hN⟩ := eventually_atTop.1 hev
  have hex : ∃ n, floorPosterior ε k n < τ := ⟨N, hN N le_rfl⟩
  refine ⟨Nat.find hex, Nat.find_spec hex, fun n hn => ?_⟩
  exact not_lt.1 (Nat.find_min hex hn)

/-- **T10(b): the floor is preserved at every round iff the likelihood ratio is exactly `1`**
(`k ≥ 0`, `0 < ε < 1`) — the "dogmatic design constant" of INDEX §C5, as a theorem.
Source: [[corr-wf14-inventory]] 066, 2-003 / joint-final.md Prop. 8 ("the floor holds only if `C_t` has likelihood ratio exactly `1`"); adv A.16.1
Kind: P
Fidelity: exact
Hyps: (a) only -/
theorem floorPosterior_const_iff (ε k : ℝ) (hε0 : 0 < ε) (hε1 : ε < 1) (hk0 : 0 ≤ k) :
    (∀ n, floorPosterior ε k n = ε) ↔ k = 1 := by
  constructor
  · intro H
    have h1 := H 1
    unfold floorPosterior at h1
    rw [pow_one, div_eq_iff (by nlinarith)] at h1
    -- `εk = ε(εk + 1 − ε)` ⟹ `k(1 − ε) = 1 − ε`
    have : ε * (k - 1) * (1 - ε) = 0 := by linear_combination h1
    rcases mul_eq_zero.1 this with h | h
    · rcases mul_eq_zero.1 h with h' | h'
      · exact absurd h' hε0.ne'
      · linarith
    · linarith
  · rintro rfl n
    simp [floorPosterior]

/-- **T10(b) witness (adv (F)).** `ε = 1/100`, `k = 9/10`: `p_50 < 10⁻⁴` (the source's
`≈ 5 × 10⁻⁵`).
Source: [[corr-wf14-inventory]] 2-003 / adv (F); joint-final.md Prop. 8
Kind: N+
Fidelity: exact (bracket)
Hyps: (a) only -/
theorem floorPosterior_witness : floorPosterior (1 / 100) (9 / 10) 50 < 1 / 10000 := by
  unfold floorPosterior
  rw [div_lt_div_iff₀ (by positivity) (by positivity)]
  norm_num

/-- **T10(b), the crossing index (rule 4).** For `τ = 10⁻⁴` the least crossing is `n₀ = 44`:
`p_43 ≥ 10⁻⁴ > p_44`, and monotonicity carries the bracket to every `n < 44`.
Source: [[corr-wf14-inventory]] 2-003 / adv (F) (the bracket, recomputed)
Kind: N+
Fidelity: exact
Hyps: (a) only -/
theorem floorPosterior_crossing_44 :
    floorPosterior (1 / 100) (9 / 10) 44 < 1 / 10000 ∧
      ∀ n < 44, (1 / 10000 : ℝ) ≤ floorPosterior (1 / 100) (9 / 10) n := by
  have h43 : (1 / 10000 : ℝ) ≤ floorPosterior (1 / 100) (9 / 10) 43 := by
    unfold floorPosterior
    rw [le_div_iff₀ (by positivity)]
    norm_num
  refine ⟨?_, fun n hn => ?_⟩
  · unfold floorPosterior
    rw [div_lt_div_iff₀ (by positivity) (by positivity)]
    norm_num
  · refine h43.trans ?_
    exact (floorPosterior_strictAnti (1 / 100) (9 / 10) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num)).antitone (by omega)

/-! ## (c) The requirement sequence -/

/-- The no-floor error sequence `ε_t = (1/5) 2^{−t}`.
Source: [[corr-wf14-inventory]] 066 / joint.md P.9 (script (g))
Kind: D
Fidelity: exact -/
noncomputable def epsNoFloor (t : ℕ) : ℝ := 1 / 5 * (1 / 2) ^ t

/-- The develop's with-floor sequence: `ε'_t = 2^{−t}(1/5) + (1 − 2^{−t})(1/100)` — the mass not
yet driven to zero sits at the initial `1/5`, the rest at the floor `1/100`. This, not
`max(ε_t, ε_∞)`, generates the printed numbers `1, 84/179, 92/377, 108/773, 28/313, …`.
Source: [[corr-wf14-inventory]] 066, 2-003 / joint.md P.9 (the printed sequence; generator reverse-engineered — finding)
Kind: D
Fidelity: variant: the source does not state its generator; this one reproduces its numbers -/
noncomputable def epsWithFloor (t : ℕ) : ℝ := (1 / 2) ^ t * (1 / 5) + (1 - (1 / 2) ^ t) * (1 / 100)

/-- The literal floored sequence `max(ε_t, ε_∞)` at `ε_∞ = 1/100`.
Source: [[corr-wf14-inventory]] 066 / joint.md Prop. 8 (the literal reading of "`ε_{t,i} ≥ ε_∞`")
Kind: D
Fidelity: exact -/
noncomputable def epsMaxFloor (t : ℕ) : ℝ := max (epsNoFloor t) (1 / 100)

/-- The odds-form requirement `α/β ≤ (ε/(1 − ε))·(h/c)` at `h/c = 4`.
Source: [[corr-wf14-inventory]] 066 / joint.md P.9
Kind: D
Fidelity: exact -/
noncomputable def oddsBound (ε : ℝ) : ℝ := ε / (1 - ε) * 4

/-- **T10(c), the table (script (g)).** Without a floor: `1, 4/9, 4/19, 4/39, 4/79`; the
develop's with-floor sequence: `1, 84/179, 92/377, 108/773, 28/313`; the literal `max` form:
`1, 4/9, 4/19, 4/39, 4/79, 4/99, 4/99`.
Source: [[corr-wf14-inventory]] 066, 2-003 / joint.md P.9; script (g); mandate T10(c)
Kind: N+
Fidelity: exact
Hyps: (a) only -/
theorem requirement_table :
    (oddsBound (epsNoFloor 0) = 1 ∧ oddsBound (epsNoFloor 1) = 4 / 9 ∧ oddsBound (epsNoFloor 2) = 4 / 19 ∧
      oddsBound (epsNoFloor 3) = 4 / 39 ∧ oddsBound (epsNoFloor 4) = 4 / 79) ∧
    (oddsBound (epsWithFloor 0) = 1 ∧ oddsBound (epsWithFloor 1) = 84 / 179 ∧
      oddsBound (epsWithFloor 2) = 92 / 377 ∧ oddsBound (epsWithFloor 3) = 108 / 773 ∧
      oddsBound (epsWithFloor 4) = 28 / 313) ∧
    (oddsBound (epsMaxFloor 4) = 4 / 79 ∧ oddsBound (epsMaxFloor 5) = 4 / 99 ∧
      oddsBound (epsMaxFloor 6) = 4 / 99) := by
  unfold oddsBound epsMaxFloor epsNoFloor epsWithFloor
  norm_num [max_def]

/-- **T10(c), the closed form** of the with-floor requirement: `4(2^t + 19)/(99·2^t − 19)`.
Source: [[corr-wf14-inventory]] 066 / joint.md P.9 (derived here)
Kind: L
Fidelity: exact -/
theorem epsWithFloor_bound_closed (t : ℕ) :
    oddsBound (epsWithFloor t) = 4 * (2 ^ t + 19) / (99 * 2 ^ t - 19) := by
  unfold oddsBound epsWithFloor
  have h2 : (0 : ℝ) < 2 ^ t := by positivity
  have hne : (99 : ℝ) * 2 ^ t - 19 ≠ 0 := by
    have : (1 : ℝ) ≤ 2 ^ t := one_le_pow₀ (by norm_num)
    linarith
  have hden : (1 : ℝ) - ((1 / 2) ^ t * (1 / 5) + (1 - (1 / 2) ^ t) * (1 / 100)) ≠ 0 := by
    have : ((1 : ℝ) / 2) ^ t ≤ 1 := pow_le_one₀ (by norm_num) (by norm_num)
    have : (0 : ℝ) ≤ (1 / 2) ^ t := by positivity
    intro h0; nlinarith
  have hx : (2 : ℝ) ^ t * (1 / 2) ^ t = 1 := by rw [← mul_pow]; norm_num
  rw [div_mul_eq_mul_div, div_eq_div_iff hden hne]
  linear_combination 76 * hx

/-- **T10(c): the with-floor requirement converges to `4/99`.**
Source: [[corr-wf14-inventory]] 066 / joint.md P.9 ("`→ 4/99 ≈ 0.040`")
Kind: P
Fidelity: exact
Hyps: (a) only -/
theorem epsWithFloor_bound_tendsto : Tendsto (fun t => oddsBound (epsWithFloor t)) atTop (𝓝 (4 / 99)) := by
  have hpow : Tendsto (fun t : ℕ => ((1 : ℝ) / 2) ^ t) atTop (𝓝 0) :=
    tendsto_pow_atTop_nhds_zero_of_lt_one (by norm_num) (by norm_num)
  have hε : Tendsto epsWithFloor atTop (𝓝 (0 * (1 / 5) + (1 - 0) * (1 / 100))) :=
    (hpow.mul tendsto_const_nhds).add ((tendsto_const_nhds.sub hpow).mul tendsto_const_nhds)
  have h1 : Tendsto (fun t => epsWithFloor t / (1 - epsWithFloor t) * 4) atTop
      (𝓝 ((0 * (1 / 5) + (1 - 0) * (1 / 100)) / (1 - (0 * (1 / 5) + (1 - 0) * (1 / 100))) * 4)) :=
    (hε.div (tendsto_const_nhds.sub hε) (by norm_num)).mul tendsto_const_nhds
  have heq : (0 * (1 / 5 : ℝ) + (1 - 0) * (1 / 100)) / (1 - (0 * (1 / 5) + (1 - 0) * (1 / 100))) * 4 = 4 / 99 := by
    norm_num
  rw [heq] at h1
  exact h1

/-- **T10(c): the literal `max` form is eventually constant at `4/99`** (from `t = 5`, when
`(1/5)2^{−t} < 1/100`).
Source: [[corr-wf14-inventory]] 066 / mandate T10(c)
Kind: L
Fidelity: exact -/
theorem epsMaxFloor_bound_eventually (t : ℕ) (ht : 5 ≤ t) : oddsBound (epsMaxFloor t) = 4 / 99 := by
  have hsmall : epsNoFloor t ≤ 1 / 100 := by
    unfold epsNoFloor
    have : ((1 : ℝ) / 2) ^ t ≤ (1 / 2) ^ 5 := pow_le_pow_of_le_one (by norm_num) (by norm_num) ht
    linarith
  unfold oddsBound epsMaxFloor
  rw [max_eq_right hsmall]
  norm_num

end Cleanroom.Corrigibility.CorrJointProcess
