import Cleanroom.Bli.BliMeasure.Measure

/-!
# `bli-measure` · Coherence: `𝐏_n` is a probability measure on worlds (target 1)

**The stage** `b3Stage n := DP.D n ∪ (state literals of days ≤ n)` — the base's day-`n` stage with
the realized states of every day *up to and including* `n` (`bliDP`'s stage `n` has days `< n`
only; `bliDP_D_subset_b3Stage`).

**1(a)+(b), one theorem** (`b3History_coherentOn`): for every `n` and every finite atom set `A`,
`𝐏_n` restricted to the Boolean algebra generated by `A` is a convex combination of the payouts
of the charged B3 worlds, each **consistent with `b3Stage n`** — every propositional identity holds
on every finite algebra, relative to the stage. The world family is the charged `(τ, u)` pairs at
a horizon covering `A` (the real construction, not `Classical.choice` of worlds); the horizon is
immaterial by `b3History_eq`. Consistency with `DP.D n` is **pinning along the chain**
(`ctraj_zero_persists`: the face kernel never charges a vector leaving the support of the
rounded base measure, which is `DP.D n`-supported) — so the stage-free kernel does respect the
*whole* stage, large theorems included (the mandate expected this to be open or refuted; it holds
because the stage lies within the day's atom bound, `B_stage`). The state literals hold by the
world's realized-past convention. Hypothesis (a): `hfree : TagFreeProcess stateTag DP` (the base
process mentions no state atom; `paperDP_tagFree` discharges it) — used only for consistency with
the stage, so the family lemma `b3History_coherentOn_of_holds` (the convex combination, relative
to any stage the charged worlds hold) and the pure-coherence instance `b3History_coherentOn_empty`
(1(a) alone) take no hypothesis (repair round 2).

Corollaries as separate rows: `b3History_top`, `b3History_add_neg` (every `φ`),
`b3History_add_of_exclusive`, `b3History_mono`, and `PCP` for the stage process `b3StageDP` and
for `bliDP DP states actual` (whose stages are smaller).
-/

namespace Cleanroom.Bli.BliMeasure

open LogicalInduction LO.Propositional Finset BoolPCWorld Cleanroom.Bli.BliFinite
  Cleanroom.Bli.BliFound Cleanroom.Bli.BliTrajectory

variable {DP : DeductiveProcess} (base : CoherentBase DP) (𝓜 : Mesh)

/-! ## The B3 stage -/

/-- The state literals of days `≤ n` (the realized states known on day `n`).
Source: [[bli-measure-mandate]] target 1(b) ("the state literals of days `≤ n`")
Kind: D
Fidelity: exact -/
noncomputable def stateLits (n : ℕ) : Finset Sentence :=
  (stateEntries (wstates base.𝔅 𝓜) (b3Actual base 𝓜) (n + 1)).image literalOf

/-- **The B3 stage**: the base's day-`n` stage with the state literals of days `≤ n`.
Source: [[bli-measure-mandate]] target 1(b) (`DP'`), with the whole `DP.D n` (not only its small
part) since the stage lies within the atom bound
Kind: D
Fidelity: stronger: whole stage, days `≤ n` -/
noncomputable def b3Stage (n : ℕ) : Finset Sentence := DP.D n ∪ stateLits base 𝓜 n

/-- The B3 stage, as a deductive process.
Source: [[bli-measure-mandate]] target 1(b)
Kind: D
Fidelity: exact -/
noncomputable def b3StageDP : DeductiveProcess where
  D := b3Stage base 𝓜
  mono n := Finset.union_subset_union (DP.mono n)
    (Finset.image_subset_image ((stateSchedule (wstates base.𝔅 𝓜) (b3Actual base 𝓜)).mono (n + 1)))

/-- `bliDP`'s day-`n` stage (state literals of days `< n`) is contained in the B3 stage.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma bliDP_D_subset_b3Stage (n : ℕ) :
    (bliDP DP (wstates base.𝔅 𝓜) (b3Actual base 𝓜)).D n ⊆ b3Stage base 𝓜 n := by
  rw [bliDP_D]
  exact Finset.union_subset_union (Finset.Subset.refl _)
    (Finset.image_subset_image ((stateSchedule (wstates base.𝔅 𝓜) (b3Actual base 𝓜)).mono n))

/-- Coherence is antitone in the stage.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma coherentOn_mono_stage {D D' : Finset Sentence} (hD : D' ⊆ D) {A : Finset ℕ}
    {p : Sentence → ℝ} (h : Cleanroom.Bli.BliFound.CoherentOn D A p) :
    Cleanroom.Bli.BliFound.CoherentOn D' A p := by
  obtain ⟨k, W, w, hW, hw0, hw1, hp⟩ := h
  exact ⟨k, W, w, fun i φ hφ => hW i φ (hD hφ), hw0, hw1, hp⟩

/-! ## Charged worlds are consistent with the stage -/

/-- A charged last-day world restricts to a world charged by the rounded measure (pinning along
the chain).
Source: [[bli-measure-mandate]] target 1(b) (design note: "along the chain no charged world
refutes it")
Kind: P
Fidelity: exact
Hyps: (a) `hτ`, `hw` -/
theorem measureRound_ne_zero_of_b3Weight_ne_zero {n h : ℕ} {τ : Traj (wIndex base.𝔅.B) n h}
    (hτ : τ ∈ ctrajGrid (cgrid base.𝔅 𝓜) n h) {u : FiniteWorld (base.𝔅.B (n + h))}
    (hw : b3Weight base 𝓜 n h τ u ≠ 0) :
    measureRound base 𝓜 n (restrFW (base.𝔅.B_le (Nat.le_add_right n h)) u) ≠ 0 := by
  have hrt := roundedTable_mem_cgrid base 𝓜 n
  have hlast := Traj.last_mem hrt hτ
  unfold b3Weight at hw
  have hL : 0 < ctrajLaw (faceSkeleton base.𝔅 𝓜) n h (roundedTable base 𝓜 n) τ :=
    lt_of_le_of_ne (ctrajLaw_nonneg _ _ _) (fun h0 => hw (by rw [← h0, zero_mul]))
  have hu : 0 < (τ.last (roundedTable base 𝓜 n)) (wcSelf (n + h) u) :=
    lt_of_le_of_ne (vecOf_nonneg base.𝔅 𝓜 hlast u) (fun h0 => hw (by rw [← h0, mul_zero]))
  intro h0
  have hrt0 : (roundedTable base 𝓜 n) (wcSelf n (restrFW (base.𝔅.B_le (Nat.le_add_right n h)) u)) = 0 := by
    have := congrFun (vecOf_roundedTable base 𝓜 n) (restrFW (base.𝔅.B_le (Nat.le_add_right n h)) u)
    rw [h0] at this
    exact this
  have hpin := ctraj_zero_persists (faceSkeleton base.𝔅 𝓜) (cgrid_inUnit base.𝔅 𝓜) hrt
    (wcSelf n (restrFW (base.𝔅.B_le (Nat.le_add_right n h)) u)) hrt0 τ hτ hL
  have hle := vecOf_le_apply_wcAt base.𝔅 𝓜 hlast (Nat.le_add_right n h) u
  have heq : (τ.last (roundedTable base 𝓜 n))
      (wcAt (Nat.le_add_right n h) (restrFW (base.𝔅.B_le (Nat.le_add_right n h)) u)) = 0 := hpin
  rw [heq] at hle
  exact absurd (lt_of_lt_of_le hu hle) (lt_irrefl 0)

/-- **Every charged B3 world is consistent with the B3 stage.**
Source: [[bli-measure-mandate]] target 1(b)
Kind: P
Fidelity: stronger: the whole `DP.D n` (within the atom bound), state literals of days `≤ n`
Hyps: (a) `hfree` (the base process mentions no state atom; `paperDP_tagFree`); (a) `hτ`, `hw` -/
theorem b3World_consistent (hfree : TagFreeProcess stateTag DP) {n h : ℕ}
    {τ : Traj (wIndex base.𝔅.B) n h} (hτ : τ ∈ ctrajGrid (cgrid base.𝔅 𝓜) n h)
    {u : FiniteWorld (base.𝔅.B (n + h))} (hw : b3Weight base 𝓜 n h τ u ≠ 0) :
    (b3World base 𝓜 n h τ u.toBoolPCWorld).ConsistentWith (b3Stage base 𝓜 n) := by
  intro φ hφ
  rw [b3Stage, Finset.mem_union] at hφ
  rcases hφ with hφ | hφ
  · -- the base stage
    have hB := base.B_stage n φ hφ
    have hfr : TagFreeSentence stateTag φ := hfree n φ hφ
    have hru := measureRound_ne_zero_of_b3Weight_ne_zero base 𝓜 hτ hw
    have hcons := base.w_supp n _ (w_ne_zero_of_measureRound_ne_zero base 𝓜 n hru) φ hφ
    show (toPCWorld (b3Bits base 𝓜 n h τ u.toBoolPCWorld)).Holds φ
    rw [← eval_eq_true_iff_holds, eval_b3Bits_of_tagFree base 𝓜 τ _ hfr, eval_eq_true_iff_holds]
    exact (holds_worldOf_restrFW (base.𝔅.B_le (Nat.le_add_right n h)) u hB).mp hcons
  · -- the state literals
    unfold stateLits at hφ
    rw [Finset.mem_image] at hφ
    obtain ⟨x, hx, rfl⟩ := hφ
    rw [mem_stateEntries] at hx
    obtain ⟨m, hm, hx | ⟨q, hq, hx⟩⟩ := hx
    · subst hx
      rw [literalOf_true]
      show (toPCWorld (b3Bits base 𝓜 n h τ u.toBoolPCWorld)).Holds (stateAtom m (b3Actual base 𝓜 m))
      rw [← eval_eq_true_iff_holds, eval_b3Bits_stateAtom,
        b3Bits_past base 𝓜 (sysState_of_mem base 𝓜 (b3Actual_mem base 𝓜 m)) (by omega)]
      simp
    · subst hx
      have hs := sysState_of_mem base 𝓜 hq
      by_cases hqa : q = b3Actual base 𝓜 m
      · rw [decide_eq_true hqa, literalOf_true]
        show (toPCWorld (b3Bits base 𝓜 n h τ u.toBoolPCWorld)).Holds (stateAtom m q)
        rw [← eval_eq_true_iff_holds, eval_b3Bits_stateAtom, b3Bits_past base 𝓜 hs (by omega)]
        simp [hqa]
      · rw [decide_eq_false hqa, literalOf_false]
        show (toPCWorld (b3Bits base 𝓜 n h τ u.toBoolPCWorld)).Holds (∼stateAtom m q)
        rw [PCWorld.holds_neg, ← eval_eq_true_iff_holds, eval_b3Bits_stateAtom,
          b3Bits_past base 𝓜 hs (by omega)]
        simp [hqa]

/-! ## Covering a finite atom set -/

/-- A horizon covering a finite atom set.
Source: none: infrastructure
Kind: D
Fidelity: n/a -/
def CoversSet (n h : ℕ) (A : Finset ℕ) : Prop :=
  ∀ a ∈ A, (∀ m q, sysState base 𝓜 a = some (m, q) → m ≤ n + h) ∧
    (sysState base 𝓜 a = none → a < base.𝔅.B (n + h))

/-- Every finite atom set has a covering horizon.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma exists_coversSet (n : ℕ) (A : Finset ℕ) : ∃ h, CoversSet base 𝓜 n h A := by
  refine ⟨A.sup (coverFor base 𝓜), ?_⟩
  intro a ha
  have hle : coverFor base 𝓜 a ≤ A.sup (coverFor base 𝓜) := Finset.le_sup ha
  constructor
  · intro m q hs
    have : coverFor base 𝓜 a = m := by unfold coverFor; rw [hs]
    omega
  · intro hs
    have hc : coverFor base 𝓜 a = Classical.choose (base.𝔅.B_unbounded a) := by
      unfold coverFor; rw [hs]
    have hspec := Classical.choose_spec (base.𝔅.B_unbounded a)
    rw [← hc] at hspec
    exact lt_of_lt_of_le hspec (base.𝔅.B_le (by omega))

/-- A sentence over a covered atom set is covered.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma covers_of_coversSet {n h : ℕ} {A : Finset ℕ} (hc : CoversSet base 𝓜 n h A) {ψ : Sentence}
    (hψ : sentenceAtomCodes ψ ⊆ A) : Covers base 𝓜 n h ψ :=
  fun a ha => hc a (hψ ha)

/-! ## The headline: coherence on every finite algebra -/

/-- The charged pairs at a horizon.
Source: none: infrastructure
Kind: D
Fidelity: n/a -/
noncomputable def chargedPairs (n h : ℕ) :
    Finset (Traj (wIndex base.𝔅.B) n h × FiniteWorld (base.𝔅.B (n + h))) :=
  (ctrajGrid (cgrid base.𝔅 𝓜) n h ×ˢ univ).filter fun p => b3Weight base 𝓜 n h p.1 p.2 ≠ 0

/-- The mass at a horizon is the sum over the charged pairs.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma b3Mass_eq_sum_chargedPairs (n h : ℕ) (ψ : Sentence) :
    b3Mass base 𝓜 n h ψ = ∑ p ∈ chargedPairs base 𝓜 n h,
      b3Weight base 𝓜 n h p.1 p.2 * (if eval (b3Bits base 𝓜 n h p.1 p.2.toBoolPCWorld) ψ then 1 else 0) := by
  unfold b3Mass chargedPairs
  rw [Finset.sum_filter, ← Finset.sum_product']
  apply Finset.sum_congr rfl
  intro p _
  by_cases h0 : b3Weight base 𝓜 n h p.1 p.2 = 0
  · rw [if_neg (not_not.mpr h0), h0, zero_mul]
  · rw [if_pos h0]

/-- The charged weights sum to one.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma sum_chargedPairs_weight (n h : ℕ) :
    ∑ p ∈ chargedPairs base 𝓜 n h, b3Weight base 𝓜 n h p.1 p.2 = 1 := by
  unfold chargedPairs
  rw [Finset.sum_filter]
  calc ∑ p ∈ ctrajGrid (cgrid base.𝔅 𝓜) n h ×ˢ univ,
        (if b3Weight base 𝓜 n h p.1 p.2 ≠ 0 then b3Weight base 𝓜 n h p.1 p.2 else 0)
      = ∑ p ∈ ctrajGrid (cgrid base.𝔅 𝓜) n h ×ˢ univ, b3Weight base 𝓜 n h p.1 p.2 := by
        apply Finset.sum_congr rfl
        intro p _
        by_cases h0 : b3Weight base 𝓜 n h p.1 p.2 = 0
        · rw [if_neg (not_not.mpr h0), h0]
        · rw [if_pos h0]
    _ = ∑ τ ∈ ctrajGrid (cgrid base.𝔅 𝓜) n h, ∑ u : FiniteWorld (base.𝔅.B (n + h)),
          b3Weight base 𝓜 n h τ u := Finset.sum_product _ _ _
    _ = 1 := b3Weight_sum base 𝓜 n h

/-- **The coherence family of record, relative to any stage every charged B3 world holds**: for
every finite atom set `A`, `𝐏_n` on the sentences over `A` is the convex combination of the
payouts of the charged B3 worlds at a covering horizon (weights `b3Weight`, sum `1`), each
consistent with `D` by the hypothesis `hD`. The world family is the construction's own
`b3World`s. The headline `b3History_coherentOn` instantiates it at the B3 stage through the
pinning argument `b3World_consistent`; `b3History_coherentOn_empty` at `∅` with nothing to show
(factored out in repair round 2, audit r2 adversarial N1: the pure-coherence instance needs no
hypothesis).
Source: [[bli-measure-mandate]] target 1 (the family); [[bli-program-construction]] §2.7
Kind: P
Fidelity: exact (the family, parametric in the stage)
Hyps: (a) `hD` -/
theorem b3History_coherentOn_of_holds (n : ℕ) (A : Finset ℕ) (D : Finset Sentence)
    (hD : ∀ {h : ℕ} {τ : Traj (wIndex base.𝔅.B) n h}, τ ∈ ctrajGrid (cgrid base.𝔅 𝓜) n h →
      ∀ {u : FiniteWorld (base.𝔅.B (n + h))}, b3Weight base 𝓜 n h τ u ≠ 0 →
      (b3World base 𝓜 n h τ u.toBoolPCWorld).ConsistentWith D) :
    Cleanroom.Bli.BliFound.CoherentOn D A (b3History base 𝓜 n) := by
  obtain ⟨h, hc⟩ := exists_coversSet base 𝓜 n A
  let e := Fintype.equivFin ↥(chargedPairs base 𝓜 n h)
  have hmem : ∀ i, (e.symm i).1.1 ∈ ctrajGrid (cgrid base.𝔅 𝓜) n h ∧
      b3Weight base 𝓜 n h (e.symm i).1.1 (e.symm i).1.2 ≠ 0 := by
    intro i
    have hp := Finset.mem_filter.mp (e.symm i).2
    exact ⟨(Finset.mem_product.mp hp.1).1, hp.2⟩
  refine ⟨Fintype.card ↥(chargedPairs base 𝓜 n h),
    fun i => b3World base 𝓜 n h (e.symm i).1.1 (e.symm i).1.2.toBoolPCWorld,
    fun i => (b3Weight base 𝓜 n h (e.symm i).1.1 (e.symm i).1.2 : ℝ), ?_, ?_, ?_, ?_⟩
  · intro i
    exact hD (hmem i).1 (hmem i).2
  · intro i
    show (0 : ℝ) ≤ ((b3Weight base 𝓜 n h (e.symm i).1.1 (e.symm i).1.2 : ℚ) : ℝ)
    exact_mod_cast b3Weight_nonneg base 𝓜 (hmem i).1 (e.symm i).1.2
  · rw [Fintype.sum_equiv e.symm (fun i => (b3Weight base 𝓜 n h (e.symm i).1.1 (e.symm i).1.2 : ℝ))
      (fun p => (b3Weight base 𝓜 n h p.1.1 p.1.2 : ℝ)) (fun _ => rfl)]
    rw [Finset.sum_coe_sort (chargedPairs base 𝓜 n h) (fun p => (b3Weight base 𝓜 n h p.1 p.2 : ℝ))]
    exact_mod_cast sum_chargedPairs_weight base 𝓜 n h
  · intro φ hφ
    rw [b3History_eq base 𝓜 (covers_of_coversSet base 𝓜 hc hφ), b3Mass_eq_sum_chargedPairs]
    rw [Fintype.sum_equiv e.symm _
      (fun p : ↥(chargedPairs base 𝓜 n h) => (b3Weight base 𝓜 n h p.1.1 p.1.2 : ℝ) *
        (b3World base 𝓜 n h p.1.1 p.1.2.toBoolPCWorld).payout φ) (fun _ => rfl)]
    rw [Finset.sum_coe_sort (chargedPairs base 𝓜 n h) (fun p => (b3Weight base 𝓜 n h p.1 p.2 : ℝ) *
      (b3World base 𝓜 n h p.1 p.2.toBoolPCWorld).payout φ)]
    push_cast
    apply Finset.sum_congr rfl
    intro p _
    congr 1
    unfold PCWorld.payout b3World
    rw [← eval_eq_true_iff_holds]
    split_ifs <;> simp_all

/-- **`𝐏_n` is coherent on every finite algebra, relative to the B3 stage** (targets 1(a) and
1(b)): for every finite atom set `A`, `𝐏_n` on the sentences over `A` is a convex combination of
the payouts of the charged B3 worlds at a covering horizon, each consistent with
`DP.D n ∪ {state literals of days ≤ n}`. With the empty stage this is 1(a) ("every propositional
identity holds on every finite algebra"); with the stage it is 1(b). The world family is the
construction's own `b3World`s; the content is the family `b3History_coherentOn_of_holds` (P) and
the pinning argument `b3World_consistent` (P), composed.
Source: [[bli-measure-mandate]] target 1(a)/(b); [[bli-program-construction]] §2.7
Kind: C (regraded from P in repair round 2, when the family was factored out into
`b3History_coherentOn_of_holds`; the two P lemmas carry the content)
Fidelity: stronger: relative to the whole stage within the atom bound, days `≤ n`
Hyps: (a) `hfree` (`TagFreeProcess stateTag DP`; `paperDP_tagFree`) -/
theorem b3History_coherentOn (hfree : TagFreeProcess stateTag DP) (n : ℕ) (A : Finset ℕ) :
    Cleanroom.Bli.BliFound.CoherentOn (b3Stage base 𝓜 n) A (b3History base 𝓜 n) :=
  b3History_coherentOn_of_holds base 𝓜 n A _
    (fun {_h} {_τ} hτ {_u} hw => b3World_consistent base 𝓜 hfree hτ hw)

/-- **1(a), pure coherence**: relative to the empty stage, with **no hypothesis** — the mandate's
1(a) has none (repair round 2, audit r2 adversarial N1: the stage-relative form's `hfree` is used
only for consistency with the stage, which is vacuous at `∅`).
Source: [[bli-measure-mandate]] target 1(a)
Kind: C
Fidelity: exact
Hyps: (a) none -/
theorem b3History_coherentOn_empty (n : ℕ) (A : Finset ℕ) :
    Cleanroom.Bli.BliFound.CoherentOn ∅ A (b3History base 𝓜 n) :=
  b3History_coherentOn_of_holds base 𝓜 n A ∅
    (fun {_h} {_τ} _ {_u} _ φ hφ => absurd hφ (Finset.notMem_empty φ))

/-! ## Corollaries -/

/-- `𝐏_n ⊤ = 1`.
Source: [[bli-measure-mandate]] target 1(a) corollary
Kind: L
Fidelity: exact -/
theorem b3History_top (n : ℕ) : b3History base 𝓜 n ⊤ = 1 := by
  unfold b3History
  rw [b3Mass_top, Rat.cast_one]

/-- **`𝐏_n φ + 𝐏_n (∼φ) = 1` for every sentence** (contrast `bli-superbelief`'s
`lia_not_coherent_of_offSupport_pair` for FAF's LIA).
Source: [[bli-measure-mandate]] target 1(a) corollary
Kind: C (unfolding at a common covering horizon plus an indicator identity; regraded from P in
repair round 2, audit r2 fidelity N7)
Fidelity: exact
Hyps: (a) none -/
theorem b3History_add_neg (n : ℕ) (φ : Sentence) :
    b3History base 𝓜 n φ + b3History base 𝓜 n (∼φ) = 1 := by
  have hc := covers_hor base 𝓜 n φ
  have hc' : Covers base 𝓜 n (hor base 𝓜 n φ) (∼φ) := by
    intro a ha; rw [sentenceAtomCodes_neg] at ha; exact hc a ha
  rw [b3History_eq base 𝓜 hc, b3History_eq base 𝓜 hc', ← Rat.cast_add]
  have key : (b3Mass base 𝓜 n (hor base 𝓜 n φ) φ + b3Mass base 𝓜 n (hor base 𝓜 n φ) (∼φ)) = 1 := by
    unfold b3Mass
    rw [← Finset.sum_add_distrib]
    calc ∑ τ ∈ ctrajGrid (cgrid base.𝔅 𝓜) n (hor base 𝓜 n φ),
          (∑ u : FiniteWorld (base.𝔅.B (n + hor base 𝓜 n φ)), b3Weight base 𝓜 n _ τ u *
              (if eval (b3Bits base 𝓜 n _ τ u.toBoolPCWorld) φ then 1 else 0) +
            ∑ u : FiniteWorld (base.𝔅.B (n + hor base 𝓜 n φ)), b3Weight base 𝓜 n _ τ u *
              (if eval (b3Bits base 𝓜 n _ τ u.toBoolPCWorld) (∼φ) then 1 else 0))
        = ∑ τ ∈ ctrajGrid (cgrid base.𝔅 𝓜) n (hor base 𝓜 n φ),
            ∑ u : FiniteWorld (base.𝔅.B (n + hor base 𝓜 n φ)), b3Weight base 𝓜 n _ τ u := by
          apply Finset.sum_congr rfl; intro τ _
          rw [← Finset.sum_add_distrib]
          apply Finset.sum_congr rfl; intro u _
          rw [← mul_add]
          have hneg : eval (b3Bits base 𝓜 n _ τ u.toBoolPCWorld) (∼φ) =
              !eval (b3Bits base 𝓜 n _ τ u.toBoolPCWorld) φ := by
            rw [Formula.neg_def]
            show (!eval _ φ || eval _ ⊥) = _
            simp [eval]
          rw [hneg]
          cases eval (b3Bits base 𝓜 n _ τ u.toBoolPCWorld) φ <;> simp
      _ = 1 := b3Weight_sum base 𝓜 n _
  rw [key, Rat.cast_one]

/-- **Additivity on exclusive sentences**: if no world holds both, `𝐏_n (φ ⋎ ψ) = 𝐏_n φ + 𝐏_n ψ`.
Source: [[bli-measure-mandate]] target 1(a) corollary
Kind: C (regraded from P in repair round 2, audit r2 fidelity N7)
Fidelity: exact
Hyps: (a) `hex` (propositional exclusivity, in every world) -/
theorem b3History_add_of_exclusive (n : ℕ) {φ ψ : Sentence}
    (hex : ∀ v : PCWorld, ¬ (v.Holds φ ∧ v.Holds ψ)) :
    b3History base 𝓜 n (φ ⋎ ψ) = b3History base 𝓜 n φ + b3History base 𝓜 n ψ := by
  obtain ⟨h, hc⟩ := exists_coversSet base 𝓜 n (sentenceAtomCodes φ ∪ sentenceAtomCodes ψ)
  have hφ : Covers base 𝓜 n h φ := covers_of_coversSet base 𝓜 hc Finset.subset_union_left
  have hψ : Covers base 𝓜 n h ψ := covers_of_coversSet base 𝓜 hc Finset.subset_union_right
  have hor' : Covers base 𝓜 n h (φ ⋎ ψ) := by
    intro a ha; rw [sentenceAtomCodes_or] at ha; exact hc a ha
  rw [b3History_eq base 𝓜 hor', b3History_eq base 𝓜 hφ, b3History_eq base 𝓜 hψ, ← Rat.cast_add]
  congr 1
  unfold b3Mass
  rw [← Finset.sum_add_distrib]
  apply Finset.sum_congr rfl; intro τ _
  rw [← Finset.sum_add_distrib]
  apply Finset.sum_congr rfl; intro u _
  rw [← mul_add]
  congr 1
  set v := b3Bits base 𝓜 n h τ u.toBoolPCWorld
  have hv := hex (toPCWorld v)
  rw [← eval_eq_true_iff_holds, ← eval_eq_true_iff_holds] at hv
  show (if (eval v φ || eval v ψ) then (1 : ℚ) else 0) = _
  cases hφ' : eval v φ <;> cases hψ' : eval v ψ <;> simp_all

/-- **Monotonicity**: if every world holding `φ` holds `ψ`, `𝐏_n φ ≤ 𝐏_n ψ`.
Source: [[bli-measure-mandate]] target 1(a) corollary
Kind: C (regraded from P in repair round 2, audit r2 fidelity N7)
Fidelity: exact
Hyps: (a) `himp` -/
theorem b3History_mono (n : ℕ) {φ ψ : Sentence} (himp : ∀ v : PCWorld, v.Holds φ → v.Holds ψ) :
    b3History base 𝓜 n φ ≤ b3History base 𝓜 n ψ := by
  obtain ⟨h, hc⟩ := exists_coversSet base 𝓜 n (sentenceAtomCodes φ ∪ sentenceAtomCodes ψ)
  have hφ : Covers base 𝓜 n h φ := covers_of_coversSet base 𝓜 hc Finset.subset_union_left
  have hψ : Covers base 𝓜 n h ψ := covers_of_coversSet base 𝓜 hc Finset.subset_union_right
  rw [b3History_eq base 𝓜 hφ, b3History_eq base 𝓜 hψ]
  have : b3Mass base 𝓜 n h φ ≤ b3Mass base 𝓜 n h ψ := by
    unfold b3Mass
    apply Finset.sum_le_sum; intro τ hτ
    apply Finset.sum_le_sum; intro u _
    apply mul_le_mul_of_nonneg_left _ (b3Weight_nonneg base 𝓜 hτ u)
    set v := b3Bits base 𝓜 n h τ u.toBoolPCWorld
    have hv := himp (toPCWorld v)
    rw [← eval_eq_true_iff_holds, ← eval_eq_true_iff_holds] at hv
    cases hφ' : eval v φ <;> cases hψ' : eval v ψ <;> simp_all
  exact_mod_cast this

/-! ## `PCP` -/

/-- **`PCP` for the B3 stage process**, every horizon function: `bli-found`'s finite coherence of
`𝐏_n` on `smallSet n` and the state atoms of days `≤ h n`, relative to `b3StageDP`.
Source: [[bli-measure-mandate]] target 1(b) (`PCP h coherentStateSystem DP' (b3History)`)
Kind: C
Fidelity: stronger: `DP'` carries the whole `DP.D n`, not only its small part
Hyps: (a) `hfree` -/
theorem b3History_PCP_stage (hfree : TagFreeProcess stateTag DP) (hh : ℕ → ℕ) :
    PCP hh (b3StateSystem base 𝓜) (b3StageDP base 𝓜) (b3History base 𝓜) :=
  fun n => b3History_coherentOn base 𝓜 hfree n _

/-- **`PCP` for `bliDP DP states actual`**, every horizon function: the full-stage `PCP` the
mandate expected to be open or refuted holds, since `bliDP`'s stages are contained in the B3
stages.
Source: [[bli-measure-mandate]] target 1(b) ("the full-stage `PCP` is stated OPEN or refuted")
Kind: C
Fidelity: exact
Hyps: (a) `hfree` -/
theorem b3History_PCP_bliDP (hfree : TagFreeProcess stateTag DP) (hh : ℕ → ℕ) :
    PCP hh (b3StateSystem base 𝓜) (bliDP DP (wstates base.𝔅 𝓜) (b3Actual base 𝓜))
      (b3History base 𝓜) :=
  fun n => coherentOn_mono_stage (bliDP_D_subset_b3Stage base 𝓜 n)
    (b3History_coherentOn base 𝓜 hfree n _)

end Cleanroom.Bli.BliMeasure
