import Cleanroom.Bli.BliMeasure.Worlds
import Cleanroom.Bli.BliFinite.WorldRound
import Cleanroom.Bli.BliFound.Size
import Mathlib.Algebra.BigOperators.Field

/-!
# `bli-measure` · Grid: the world-vector index, the coherent grid of record, the state coding
(target 0)

**Design decision (finding F1 of [[bli-measure-findings]]).** The mandate's grid of record is the
coherent grid of *tables on `smallSet m`* with a canonical world-weight selection
`canonWeights`. That object is **not** a world measure across horizons: the selection at day
`m+1` is independent of the selection at day `m`, so the horizon-`h` and horizon-`(h+1)` prices
of a large base sentence differ, and additivity fails on the algebra generated by one large base
atom and the day-`(n+1)` state atoms. B3 of record therefore takes **the rounded world measure
itself as the state**: the day-`m` state is a weight vector in `(1/d m)·ℕ` on
`FiniteWorld (B m)`, coded as a table over the index `wIndex B` of world conjunctions `φ_u`
(`worldConj`, days `≤ m`), so that `bli-finite`'s `coherentGrid` and `bli-superbelief`'s face
machinery apply verbatim, the selection disappears (`vecOf` reads the vector off the table,
`cgrid_apply_eq_wMarginal`), and balance on `wIndex B` *is* balance on worlds.

* `wIndex B` — the `SmallIndex` whose day-`m` sentences are the `φ_u` for `u : FiniteWorld (B k)`,
  `k ≤ m`; `wcAt`/`wcSelf` name those coordinates.
* `AtomBounds` — the atom-bound data `B` of the mandate's `CoherentMesh` (monotone, covering
  `smallSet m`, unbounded); the mesh `d` is `bli-finite`'s `Mesh`.
* `cgrid 𝔅 𝓜 m := coherentGrid (wIndex 𝔅.B) 𝓜.d m ∅ (𝔅.B m)` — relative to the empty stage
  (the design note's stage-free grid).
* `mem_cgrid_of_vec` / `cgrid_apply_eq_wMarginal` — the grid *is* the set of `(1/d m)·ℕ`
  probability vectors on `FiniteWorld (B m)`, read through their marginals.
* `extTable` — the **extension lemma**: a day-`m` grid table extended by `false` on the new atoms
  is a day-`(m+1)` grid table restricting to it (needs `d m ∣ d (m+1)`, `B m ≤ B (m+1)`).
* `wcode`/`wdecode`/`wstates` — an injective, large coding of grid tables (code
  `4 ^ sizeBound m + index`), with a disclosed junk default for `wdecode` off the image.
-/

namespace Cleanroom.Bli.BliMeasure

open LogicalInduction LO.Propositional Finset BoolPCWorld Cleanroom.Bli.BliFinite
  Cleanroom.Bli.BliFound

/-! ## The world-vector index -/

/-- **The index of world conjunctions**: on day `m`, the sentences `φ_u` for `u : FiniteWorld (B k)`,
`k ≤ m`. Nested in `m` by construction.
Source: [[bli-measure-mandate]] target 0 (grid of record), redesigned (finding F1)
Kind: D
Fidelity: variant: the state is the world vector, not the table on `smallSet m` (disclosed) -/
def wIndex (B : ℕ → ℕ) : SmallIndex where
  S m := (Finset.range (m + 1)).biUnion fun k =>
    (Finset.univ : Finset (FiniteWorld (B k))).image worldConj
  mono _ := Finset.biUnion_subset_biUnion_of_subset_left _
    (fun _ hk => Finset.mem_range.mpr (lt_of_lt_of_le (Finset.mem_range.mp hk) (Nat.le_succ _)))

/-- Membership in the world-vector index.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma mem_wIndex {B : ℕ → ℕ} {m : ℕ} {φ : Sentence} :
    φ ∈ (wIndex B).S m ↔ ∃ k ≤ m, ∃ u : FiniteWorld (B k), worldConj u = φ := by
  simp only [wIndex, Finset.mem_biUnion, Finset.mem_range, Finset.mem_image, Finset.mem_univ,
    true_and]
  constructor
  · rintro ⟨k, hk, u, hu⟩; exact ⟨k, by omega, u, hu⟩
  · rintro ⟨k, hk, u, hu⟩; exact ⟨k, by omega, u, hu⟩

/-- The day-`k` conjunction `φ_u` is a day-`m` coordinate for `k ≤ m`.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma worldConj_mem_wIndex {B : ℕ → ℕ} {k m : ℕ} (hk : k ≤ m) (u : FiniteWorld (B k)) :
    worldConj u ∈ (wIndex B).S m :=
  mem_wIndex.mpr ⟨k, hk, u, rfl⟩

/-- The coordinate `φ_u` of day `k ≤ m`, as an element of the day-`m` index.
Source: none: infrastructure
Kind: D
Fidelity: n/a -/
def wcAt {B : ℕ → ℕ} {k m : ℕ} (hk : k ≤ m) (u : FiniteWorld (B k)) : ↥((wIndex B).S m) :=
  ⟨worldConj u, worldConj_mem_wIndex hk u⟩

/-- The day-`m` coordinate `φ_u` for `u : FiniteWorld (B m)`.
Source: none: infrastructure
Kind: D
Fidelity: n/a -/
abbrev wcSelf {B : ℕ → ℕ} (m : ℕ) (u : FiniteWorld (B m)) : ↥((wIndex B).S m) := wcAt le_rfl u

/-- `wcAt` is independent of the membership proof.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma wcAt_eq {B : ℕ → ℕ} {k m : ℕ} (hk : k ≤ m) (u : FiniteWorld (B k))
    (φ : ↥((wIndex B).S m)) (h : φ.1 = worldConj u) : φ = wcAt hk u :=
  Subtype.ext h

/-! ## Atom bounds and the coherent grid of record -/

/-- **The atom-bound data of the mandate's `CoherentMesh`**: monotone, covering every day-`m`
small sentence, unbounded (every atom is eventually within the bound — needed so that every
sentence has a covering horizon, `Measure.lean`).
Source: [[bli-measure-mandate]] target 0 (`CoherentMesh`, the `B` part)
Kind: D
Fidelity: exact (plus `B_unbounded`, needed for the horizon of a large base sentence) -/
structure AtomBounds where
  /-- The day-`m` atom bound. -/
  B : ℕ → ℕ
  /-- Nondecreasing. -/
  B_mono : ∀ m, B m ≤ B (m + 1)
  /-- Every day-`m` small sentence lies within the day-`m` bound. -/
  B_cover : ∀ m, ∀ φ ∈ smallSet m, atomBound φ ≤ B m
  /-- Every atom is eventually within the bound. -/
  B_unbounded : ∀ a, ∃ m, a < B m

/-- Monotonicity along `≤`.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma AtomBounds.B_le (𝔅 : AtomBounds) {m m' : ℕ} (h : m ≤ m') : 𝔅.B m ≤ 𝔅.B m' := by
  induction h with
  | refl => exact le_rfl
  | step _ ih => exact ih.trans (𝔅.B_mono _)

variable (𝔅 : AtomBounds) (𝓜 : Mesh)

/-- **The grid of record**: the day-`m` tables on `wIndex 𝔅.B` that are marginals of world weights
in `(1/𝓜.d m)·ℕ` over `𝔅.B m` atoms, **relative to the empty stage** (every propositionally
coherent grid vector; design note).
Source: [[bli-measure-mandate]] target 0 (`cgrid`); bli-paper-033 (world-measure rounding)
Kind: D
Fidelity: variant: the index is `wIndex 𝔅.B` (states are world vectors), not `smallIndex`
(finding F1) -/
noncomputable def cgrid (m : ℕ) : Finset (Table (wIndex 𝔅.B) m) :=
  coherentGrid (wIndex 𝔅.B) 𝓜.d m ∅ (𝔅.B m)

/-- The weight vector of a table on the world-vector index: its value at `φ_u`.
Source: [[bli-measure-mandate]] target 0 (`canonWeights`, made a read-off rather than a selection)
Kind: D
Fidelity: stronger: no selection — the table determines the vector -/
def vecOf {B : ℕ → ℕ} {m : ℕ} (Q : Table (wIndex B) m) : FiniteWorld (B m) → ℚ :=
  fun u => Q (wcSelf m u)

/-- The weight vector of integer world weights, in units of `1/d`.
Source: none: infrastructure
Kind: D
Fidelity: n/a -/
def vecOfC {B d : ℕ} (c : FiniteWorld B → Fin (d + 1)) : FiniteWorld B → ℚ :=
  fun u => ((c u).val : ℚ) / d

/-- `marginalOf` is the marginal of `vecOfC`.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma marginalOf_eq_wMarginal {B : ℕ → ℕ} (m : ℕ) {d : ℕ} (c : FiniteWorld (B m) → Fin (d + 1))
    (φ : ↥((wIndex B).S m)) :
    marginalOf (wIndex B) m d c φ = wMarginal (vecOfC c) φ.1 := rfl

/-- **Membership in the grid of record**: `Q ∈ cgrid m` iff `Q` is the marginal of integer world
weights summing to `d m` (the empty-stage consistency clause is vacuous).
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma mem_cgrid_iff {m : ℕ} {Q : Table (wIndex 𝔅.B) m} :
    Q ∈ cgrid 𝔅 𝓜 m ↔
      ∃ c : FiniteWorld (𝔅.B m) → Fin (𝓜.d m + 1),
        (∑ u, (c u).val = 𝓜.d m) ∧ marginalOf (wIndex 𝔅.B) m (𝓜.d m) c = Q := by
  classical
  unfold cgrid coherentGrid worldWeights
  rw [Finset.mem_image]
  constructor
  · rintro ⟨c, hc, rfl⟩
    rw [Finset.mem_filter] at hc
    exact ⟨c, hc.2.1, rfl⟩
  · rintro ⟨c, hsum, rfl⟩
    refine ⟨c, ?_, rfl⟩
    rw [Finset.mem_filter]
    refine ⟨Fintype.mem_piFinset.mpr fun _ => Finset.mem_univ _, hsum, ?_⟩
    intro u _ φ hφ
    simp at hφ

/-- The vector of a grid table is the vector of its integer weights.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma vecOf_marginalOf {B : ℕ → ℕ} (m : ℕ) {d : ℕ} (c : FiniteWorld (B m) → Fin (d + 1)) :
    vecOf (marginalOf (wIndex B) m d c) = vecOfC c := by
  funext u
  show marginalOf (wIndex B) m d c (wcSelf m u) = _
  rw [marginalOf_eq_wMarginal]
  exact wMarginal_worldConj _ u

/-- **A grid table is the marginal of its own vector** (no selection).
Source: [[bli-measure-mandate]] target 0 (`canonWeights … marginalOf = Q`), strengthened
Kind: L
Fidelity: stronger: the vector is read off the table -/
theorem cgrid_apply_eq_wMarginal {m : ℕ} {Q : Table (wIndex 𝔅.B) m} (hQ : Q ∈ cgrid 𝔅 𝓜 m)
    (φ : ↥((wIndex 𝔅.B).S m)) : Q φ = wMarginal (vecOf Q) φ.1 := by
  obtain ⟨c, -, rfl⟩ := (mem_cgrid_iff 𝔅 𝓜).mp hQ
  rw [vecOf_marginalOf, marginalOf_eq_wMarginal]

/-- The vector of a grid table is nonnegative.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma vecOf_nonneg {m : ℕ} {Q : Table (wIndex 𝔅.B) m} (hQ : Q ∈ cgrid 𝔅 𝓜 m)
    (u : FiniteWorld (𝔅.B m)) : 0 ≤ vecOf Q u := by
  obtain ⟨c, -, rfl⟩ := (mem_cgrid_iff 𝔅 𝓜).mp hQ
  rw [vecOf_marginalOf]
  unfold vecOfC
  positivity

/-- The vector of a grid table has mass one.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma vecOf_sum {m : ℕ} {Q : Table (wIndex 𝔅.B) m} (hQ : Q ∈ cgrid 𝔅 𝓜 m) :
    ∑ u, vecOf Q u = 1 := by
  obtain ⟨c, hsum, rfl⟩ := (mem_cgrid_iff 𝔅 𝓜).mp hQ
  rw [vecOf_marginalOf]
  unfold vecOfC
  have hd : (𝓜.d m : ℚ) ≠ 0 := by exact_mod_cast (𝓜.d_pos m).ne'
  rw [← Finset.sum_div, ← Nat.cast_sum, hsum, div_self hd]

/-- The vector of a grid table takes values in `(1/d m)·ℕ`.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma vecOf_grid {m : ℕ} {Q : Table (wIndex 𝔅.B) m} (hQ : Q ∈ cgrid 𝔅 𝓜 m)
    (u : FiniteWorld (𝔅.B m)) : ∃ k : ℕ, vecOf Q u = (k : ℚ) / 𝓜.d m := by
  obtain ⟨c, -, rfl⟩ := (mem_cgrid_iff 𝔅 𝓜).mp hQ
  rw [vecOf_marginalOf]
  exact ⟨(c u).val, rfl⟩

/-- A grid table's earlier-day coordinate `φ_u` is the mass of the fiber over `u`.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma cgrid_apply_wcAt {m : ℕ} {Q : Table (wIndex 𝔅.B) m} (hQ : Q ∈ cgrid 𝔅 𝓜 m) {k : ℕ}
    (hk : k ≤ m) (u : FiniteWorld (𝔅.B k)) :
    Q (wcAt hk u) =
      ∑ u' ∈ univ.filter (fun u' : FiniteWorld (𝔅.B m) => restrFW (𝔅.B_le hk) u' = u),
        vecOf Q u' := by
  rw [cgrid_apply_eq_wMarginal 𝔅 𝓜 hQ]
  exact wMarginal_worldConj_restr (𝔅.B_le hk) _ u

/-- A grid table's earlier-day coordinate is at least the weight of any world in the fiber.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma vecOf_le_apply_wcAt {m : ℕ} {Q : Table (wIndex 𝔅.B) m} (hQ : Q ∈ cgrid 𝔅 𝓜 m) {k : ℕ}
    (hk : k ≤ m) (u' : FiniteWorld (𝔅.B m)) :
    vecOf Q u' ≤ Q (wcAt hk (restrFW (𝔅.B_le hk) u')) := by
  rw [cgrid_apply_wcAt 𝔅 𝓜 hQ]
  exact Finset.single_le_sum (fun u _ => vecOf_nonneg 𝔅 𝓜 hQ u)
    (Finset.mem_filter.mpr ⟨Finset.mem_univ _, rfl⟩)

/-- **The grid is the set of `(1/d m)·ℕ` probability vectors**: the marginal table of such a
vector is a grid table.
Source: none: infrastructure (mandate target 0, the grid of record)
Kind: L
Fidelity: n/a -/
theorem mem_cgrid_of_vec {m : ℕ} (w : FiniteWorld (𝔅.B m) → ℚ) (h0 : ∀ u, 0 ≤ w u)
    (h1 : ∑ u, w u = 1) (hg : ∀ u, ∃ k : ℕ, w u = (k : ℚ) / 𝓜.d m) :
    (fun φ : ↥((wIndex 𝔅.B).S m) => wMarginal w φ.1) ∈ cgrid 𝔅 𝓜 m := by
  have hd : (0 : ℚ) < 𝓜.d m := by exact_mod_cast 𝓜.d_pos m
  classical
  let k : FiniteWorld (𝔅.B m) → ℕ := fun u => Classical.choose (hg u)
  have hk : ∀ u, w u = (k u : ℚ) / 𝓜.d m := fun u => Classical.choose_spec (hg u)
  have hkle : ∀ u, k u ≤ 𝓜.d m := by
    intro u
    have hw1 : w u ≤ 1 := by
      rw [← h1]; exact Finset.single_le_sum (fun v _ => h0 v) (Finset.mem_univ u)
    rw [hk u, div_le_one hd] at hw1
    exact_mod_cast hw1
  let c : FiniteWorld (𝔅.B m) → Fin (𝓜.d m + 1) := fun u => ⟨k u, Nat.lt_succ_of_le (hkle u)⟩
  rw [mem_cgrid_iff]
  refine ⟨c, ?_, ?_⟩
  · have : ((∑ u, k u : ℕ) : ℚ) = 𝓜.d m := by
      push_cast
      calc ∑ u, (k u : ℚ) = ∑ u, w u * 𝓜.d m := by
            apply Finset.sum_congr rfl; intro u _; rw [hk u]; field_simp
        _ = 𝓜.d m := by rw [← Finset.sum_mul, h1, one_mul]
    exact_mod_cast this
  · funext φ
    rw [marginalOf_eq_wMarginal]
    unfold wMarginal vecOfC
    apply Finset.sum_congr rfl
    intro u _
    rw [hk u]

/-- Every grid table lies in the unit cube.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma cgrid_inUnit (m : ℕ) : ∀ Q ∈ cgrid 𝔅 𝓜 m, Q.InUnit := fun _ hQ =>
  (coherentOn_of_mem_coherentGrid (𝓜.d_pos m) hQ).inUnit

/-- The point mass at a world is a grid table.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma pointTable_mem_cgrid (m : ℕ) (u₀ : FiniteWorld (𝔅.B m)) :
    (fun φ : ↥((wIndex 𝔅.B).S m) =>
      wMarginal (fun u => if u = u₀ then (1 : ℚ) else 0) φ.1) ∈ cgrid 𝔅 𝓜 m := by
  classical
  apply mem_cgrid_of_vec
  · intro u; split_ifs <;> norm_num
  · simp
  · intro u
    have hd : (𝓜.d m : ℚ) ≠ 0 := by exact_mod_cast (𝓜.d_pos m).ne'
    split_ifs
    · exact ⟨𝓜.d m, by rw [div_self hd]⟩
    · exact ⟨0, by simp⟩

/-- The grid of record is nonempty.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma cgrid_nonempty (m : ℕ) : (cgrid 𝔅 𝓜 m).Nonempty :=
  ⟨_, pointTable_mem_cgrid 𝔅 𝓜 m (fun _ => false)⟩

/-! ## The extension lemma -/

/-- The day-`(m+1)` vector obtained from a day-`m` table by extending every world by `false`.
Source: [[bli-measure-mandate]] target 0 (extension lemma)
Kind: D
Fidelity: n/a -/
def extVec {m : ℕ} (Q : Table (wIndex 𝔅.B) m) : FiniteWorld (𝔅.B (m + 1)) → ℚ :=
  fun u' => if extFW (𝔅.B_mono m) (restrFW (𝔅.B_mono m) u') = u'
    then vecOf Q (restrFW (𝔅.B_mono m) u') else 0

/-- The day-`(m+1)` table obtained from a day-`m` table by extension by `false`.
Source: [[bli-measure-mandate]] target 0 (extension lemma)
Kind: D
Fidelity: n/a -/
def extTable {m : ℕ} (Q : Table (wIndex 𝔅.B) m) : Table (wIndex 𝔅.B) (m + 1) :=
  fun φ => wMarginal (extVec 𝔅 Q) φ.1

/-- The extended vector has the same marginals as the original.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma wMarginal_extVec {m : ℕ} (Q : Table (wIndex 𝔅.B) m) (φ : Sentence) :
    wMarginal (extVec 𝔅 Q) φ = wMarginal (vecOf Q) φ :=
  wMarginal_extend (𝔅.B_mono m) (vecOf Q) φ

/-- **The extension lemma, part 1**: the extension of a grid table is a grid table.
Source: [[bli-measure-mandate]] target 0 (extension lemma)
Kind: P
Fidelity: exact
Hyps: (a) none -/
theorem extTable_mem_cgrid {m : ℕ} {Q : Table (wIndex 𝔅.B) m} (hQ : Q ∈ cgrid 𝔅 𝓜 m) :
    extTable 𝔅 Q ∈ cgrid 𝔅 𝓜 (m + 1) := by
  apply mem_cgrid_of_vec
  · intro u'
    unfold extVec
    split_ifs
    · exact vecOf_nonneg 𝔅 𝓜 hQ _
    · exact le_rfl
  · have := wMarginal_extVec 𝔅 Q ⊤
    rw [wMarginal_top, wMarginal_top, vecOf_sum 𝔅 𝓜 hQ] at this
    exact this
  · intro u'
    unfold extVec
    split_ifs
    · obtain ⟨k, hk⟩ := vecOf_grid 𝔅 𝓜 hQ (restrFW (𝔅.B_mono m) u')
      obtain ⟨r, hr⟩ := 𝓜.d_dvd m
      refine ⟨k * r, ?_⟩
      rw [hk, hr]
      have hd : (𝓜.d m : ℚ) ≠ 0 := by exact_mod_cast (𝓜.d_pos m).ne'
      have hr0 : (r : ℚ) ≠ 0 := by
        intro h0
        have : r = 0 := by exact_mod_cast h0
        rw [this, mul_zero] at hr
        exact (𝓜.d_pos (m + 1)).ne' hr
      push_cast
      field_simp
    · exact ⟨0, by simp⟩

/-- **The extension lemma, part 2**: the extension restricts to the original.
Source: [[bli-measure-mandate]] target 0 (extension lemma)
Kind: P
Fidelity: exact
Hyps: (a) none -/
theorem extTable_restrict {m : ℕ} {Q : Table (wIndex 𝔅.B) m} (hQ : Q ∈ cgrid 𝔅 𝓜 m) :
    (extTable 𝔅 Q).restrict = Q := by
  funext φ
  rw [Table.restrict_apply]
  show wMarginal (extVec 𝔅 Q) φ.1 = Q φ
  rw [wMarginal_extVec, cgrid_apply_eq_wMarginal 𝔅 𝓜 hQ]

/-! ## The state coding -/

/-- **The write-out code of a day-`m` grid table**: `4 ^ sizeBound m` plus its index in the
grid (so it is large on day `m`), `0` off the grid (junk, disclosed).
Source: [[bli-measure-mandate]] target 0 (`coherentStateSystem`, "an injective large coding");
[[bli-program]] §2.3
Kind: D
Fidelity: variant: any injective large coding; this one is by enumeration (disclosed) -/
noncomputable def wcode (m : ℕ) (Q : Table (wIndex 𝔅.B) m) : ℕ :=
  if h : Q ∈ cgrid 𝔅 𝓜 m then
    4 ^ sizeBound m + (Fintype.equivFin ↥(cgrid 𝔅 𝓜 m) ⟨Q, h⟩).val
  else 0

/-- **Decoding**: the grid table with the given code if there is one, else the **junk zero
table** (disclosed; `coherentStateSystem` reads it only on `wstates m`).
Source: [[bli-measure-mandate]] target 0 (`decode` with a disclosed junk default)
Kind: D
Fidelity: n/a (junk value disclosed) -/
noncomputable def wdecode (m q : ℕ) : Table (wIndex 𝔅.B) m :=
  if h : ∃ Q ∈ cgrid 𝔅 𝓜 m, wcode 𝔅 𝓜 m Q = q then Classical.choose h else fun _ => 0

/-- **The candidate state codes of day `m`**: the codes of the grid tables.
Source: [[bli-measure-mandate]] target 0 (`states m := (cgrid m).image (code m)`)
Kind: D
Fidelity: exact -/
noncomputable def wstates (m : ℕ) : Finset ℕ := (cgrid 𝔅 𝓜 m).image (wcode 𝔅 𝓜 m)

/-- The coding is injective on the grid.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma wcode_injOn (m : ℕ) : Set.InjOn (wcode 𝔅 𝓜 m) ↑(cgrid 𝔅 𝓜 m) := by
  intro Q₁ h₁ Q₂ h₂ h
  rw [Finset.mem_coe] at h₁ h₂
  unfold wcode at h
  rw [dif_pos h₁, dif_pos h₂] at h
  have := (Fintype.equivFin ↥(cgrid 𝔅 𝓜 m)).injective (Fin.ext (Nat.add_left_cancel h))
  exact Subtype.ext_iff.mp this

/-- Codes of grid tables are large on their day: `sizeBound m ≤ Nat.log 4 (wcode m Q)`.
Source: [[bli-program]] §2.3; `bli-found` `stateAtom_large`
Kind: L
Fidelity: exact -/
lemma wcode_large {m : ℕ} {Q : Table (wIndex 𝔅.B) m} (hQ : Q ∈ cgrid 𝔅 𝓜 m) :
    sizeBound m ≤ Nat.log 4 (wcode 𝔅 𝓜 m Q) := by
  unfold wcode
  rw [dif_pos hQ]
  calc sizeBound m = Nat.log 4 (4 ^ sizeBound m) := (Nat.log_pow (by norm_num) _).symm
    _ ≤ _ := Nat.log_mono_right (Nat.le_add_right _ _)

/-- Decoding a grid table's code gives it back.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma wdecode_wcode {m : ℕ} {Q : Table (wIndex 𝔅.B) m} (hQ : Q ∈ cgrid 𝔅 𝓜 m) :
    wdecode 𝔅 𝓜 m (wcode 𝔅 𝓜 m Q) = Q := by
  unfold wdecode
  have h : ∃ Q' ∈ cgrid 𝔅 𝓜 m, wcode 𝔅 𝓜 m Q' = wcode 𝔅 𝓜 m Q := ⟨Q, hQ, rfl⟩
  rw [dif_pos h]
  obtain ⟨hmem, heq⟩ := Classical.choose_spec h
  exact wcode_injOn 𝔅 𝓜 m hmem hQ heq

/-- Membership in the candidate codes.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma mem_wstates_iff {m q : ℕ} :
    q ∈ wstates 𝔅 𝓜 m ↔ ∃ Q ∈ cgrid 𝔅 𝓜 m, wcode 𝔅 𝓜 m Q = q := by
  unfold wstates; rw [Finset.mem_image]

/-- The code of a grid table is a candidate code.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma wcode_mem_wstates {m : ℕ} {Q : Table (wIndex 𝔅.B) m} (hQ : Q ∈ cgrid 𝔅 𝓜 m) :
    wcode 𝔅 𝓜 m Q ∈ wstates 𝔅 𝓜 m :=
  (mem_wstates_iff 𝔅 𝓜).mpr ⟨Q, hQ, rfl⟩

/-- The decoding of a candidate code is a grid table.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma wdecode_mem_cgrid {m q : ℕ} (hq : q ∈ wstates 𝔅 𝓜 m) : wdecode 𝔅 𝓜 m q ∈ cgrid 𝔅 𝓜 m := by
  obtain ⟨Q, hQ, rfl⟩ := (mem_wstates_iff 𝔅 𝓜).mp hq
  rw [wdecode_wcode 𝔅 𝓜 hQ]; exact hQ

/-- Coding the decoding of a candidate code gives it back.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma wcode_wdecode {m q : ℕ} (hq : q ∈ wstates 𝔅 𝓜 m) :
    wcode 𝔅 𝓜 m (wdecode 𝔅 𝓜 m q) = q := by
  obtain ⟨Q, hQ, rfl⟩ := (mem_wstates_iff 𝔅 𝓜).mp hq
  rw [wdecode_wcode 𝔅 𝓜 hQ]

/-- Candidate codes are large on their day.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma large_of_mem_wstates {m q : ℕ} (hq : q ∈ wstates 𝔅 𝓜 m) : sizeBound m ≤ Nat.log 4 q := by
  obtain ⟨Q, hQ, rfl⟩ := (mem_wstates_iff 𝔅 𝓜).mp hq
  exact wcode_large 𝔅 𝓜 hQ

/-- A sum over candidate codes is a sum over the grid.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma sum_wstates (m : ℕ) (f : ℕ → ℚ) :
    ∑ q ∈ wstates 𝔅 𝓜 m, f q = ∑ Q ∈ cgrid 𝔅 𝓜 m, f (wcode 𝔅 𝓜 m Q) := by
  unfold wstates
  rw [Finset.sum_image (wcode_injOn 𝔅 𝓜 m)]

/-- The real-valued form of `sum_wstates`.
Source: none: infrastructure
Kind: L
Fidelity: n/a -/
lemma sum_wstates_real (m : ℕ) (f : ℕ → ℝ) :
    ∑ q ∈ wstates 𝔅 𝓜 m, f q = ∑ Q ∈ cgrid 𝔅 𝓜 m, f (wcode 𝔅 𝓜 m Q) := by
  unfold wstates
  rw [Finset.sum_image (wcode_injOn 𝔅 𝓜 m)]

end Cleanroom.Bli.BliMeasure
